Repository tensorflow/tfjs, pull requests merged in 2019-09, with the labels that each got.

#1960 [tfjs-core] Upstream the closure fixes
  tfjs-core/src/backends/webgl/backend_webgl.ts
  tfjs-core/src/backends/webgl/conv_backprop_gpu_depthwise.ts
  tfjs-core/src/backends/webgl/conv_gpu_depthwise.ts
  tfjs-core/src/ops/browser.ts
Labels: cla: yes

#1961 webgpu: Change benchmark logs directory.
  tfjs-backend-webgpu/benchmarks/main.js
Labels: cla: yes

#1962 webgpu: Bump dependency and version.
  tfjs-backend-webgpu/package.json
  tfjs-backend-webgpu/src/setup_test.ts
  tfjs-backend-webgpu/yarn.lock
Labels: cla: yes

#1922 Fix the release script to work with other repos (website).
  scripts/release.ts
Labels: cla: yes

#1963 Remove the systemFetch export from platform_node
  tfjs-core/src/platforms/platform_node.ts
  tfjs-core/src/platforms/platform_node_test.ts
Labels: cla: yes

#1966 [tfjs] Fix security vulnerability for tfjs.
  tfjs/yarn.lock
Labels: cla: yes

#1947 [tfjs-core] Fix browser.fromPixels to work without needing readyState === 'complete'.
  tfjs-core/src/backends/cpu/backend_cpu.ts
  tfjs-core/src/backends/webgl/backend_webgl.ts
  tfjs-core/src/ops/array_ops_test.ts
  tfjs-core/src/ops/browser.ts
  tfjs-core/test.html
Labels: cla: yes

#1965 Throw a better error message when using negative begin indexing.
  tfjs-core/src/ops/slice.ts
  tfjs-core/src/ops/slice_test.ts
Labels: cla: yes

#1964 core: Fuse elu activations.
  tfjs-core/src/backends/cpu/backend_cpu.ts
  tfjs-core/src/backends/webgl/backend_webgl.ts
  tfjs-core/src/backends/webgl/unaryop_packed_gpu.ts
  tfjs-core/src/ops/fused_test.ts
  tfjs-core/src/ops/fused_util.ts
Labels: PERF, cla: yes

#1973 Increase Cloud CI timeout so integration tests can run
  cloudbuild.yml
Labels: cla: yes

#1974 [tfjs-core] Fix caching on cpu with async reads
  tfjs-core/src/backends/webgl/backend_webgl.ts
  tfjs-core/src/backends/webgl/backend_webgl_test.ts
  tfjs-core/src/ops/image_ops.ts
Labels: cla: yes

#1929 Update tfjs-core to 1.2.9.
  tfjs-core/package.json
  tfjs-core/src/version.ts
Labels: INTERNAL, cla: yes

#1968 [WebGPU] Don't release the uniform buffer under delayed mode
  tfjs-backend-webgpu/src/backend_webgpu.ts
  tfjs-backend-webgpu/src/backend_webgpu_test.ts
Labels: cla: yes

#1953 [converter] Fix bazel BUILD rules for wizard
  tfjs-converter/python/tensorflowjs/BUILD
  tfjs-converter/python/tensorflowjs/__init__.py
  tfjs-converter/python/tensorflowjs/converters/BUILD
  tfjs-converter/python/tensorflowjs/converters/converter.py
  tfjs-converter/python/tensorflowjs/converters/wizard.py
  tfjs-converter/python/tensorflowjs/converters/wizard_test.py
Labels: cla: yes

#1885 fix: python 2.7 is required for osx aswell
  tfjs-node/README.md
Labels: cla: yes

#1979 [tfjs-data] Update webcam tests for tfjs-core@1.2.9
  tfjs-data/package.json
  tfjs-data/src/iterators/webcam_iterator_test.ts
  tfjs-data/src/readers_test.ts
  tfjs-data/src/util/test_utils.ts
  tfjs-data/yarn.lock
Labels: cla: yes

#1978 Update tfjs-layers, tfjs-converter, tfjs-data to 1.2.9, 1.2.9, 1.2.9.
  tfjs-converter/package.json
  tfjs-converter/python/tensorflowjs/version.py
  tfjs-converter/src/version.ts
  tfjs-converter/yarn.lock
  tfjs-data/package.json
  tfjs-data/src/version.ts
  tfjs-layers/package.json
  tfjs-layers/src/version.ts
  tfjs-layers/yarn.lock
Labels: INTERNAL, cla: yes

#1982 Update tfjs to 1.2.9.
  tfjs/package.json
  tfjs/src/version.ts
  tfjs/yarn.lock
Labels: INTERNAL, cla: yes

#1980 [tfjs-vis] Upgrade vega
  tfjs-vis/karma.conf.js
  tfjs-vis/package.json
  tfjs-vis/scripts/test-ci.sh
  tfjs-vis/src/components/surface.tsx
  tfjs-vis/src/index.ts
  tfjs-vis/src/render/barchart.ts
  tfjs-vis/src/render/confusion_matrix.ts
  tfjs-vis/src/render/heatmap.ts
  tfjs-vis/src/render/histogram.ts
  tfjs-vis/src/render/linechart.ts
  tfjs-vis/src/render/scatterplot.ts
  tfjs-vis/src/util/dom.ts
  tfjs-vis/src/version.ts
  tfjs-vis/tsconfig.json
  tfjs-vis/yarn.lock
Labels: cla: yes

#1977 core: Add fused depthwiseConv with bias and activation kernel.
  tfjs-core/src/backends/backend.ts
  tfjs-core/src/backends/cpu/backend_cpu.ts
  tfjs-core/src/backends/webgl/backend_webgl.ts
  tfjs-core/src/backends/webgl/conv_gpu_depthwise.ts
  tfjs-core/src/backends/webgl/conv_packed_gpu_depthwise.ts
  tfjs-core/src/ops/conv.ts
  tfjs-core/src/ops/fused_ops.ts
  tfjs-core/src/ops/fused_test.ts
  tfjs-core/src/ops/fused_util.ts
Labels: PERF, cla: yes

#1981 Fix bug in converter to load saved model
  tfjs-converter/python/run-python-tests.sh
  tfjs-converter/python/tensorflowjs/converters/tf_saved_model_conversion_v2.py
  tfjs-converter/python/tensorflowjs/converters/tf_saved_model_conversion_v2_test.py
Labels: cla: yes

#1983 Update tfjs-node to 1.2.9.
  tfjs-node/package.json
  tfjs-node/src/nodejs_kernel_backend.ts
  tfjs-node/src/version.ts
  tfjs-node/yarn.lock
Labels: INTERNAL, cla: yes

#1952 added userDefinedMetadata to http store
  tfjs-core/src/io/http.ts
Labels: cla: yes

#1992 core: Do not export conv gradient ops.
  tfjs-core/src/ops/ops.ts
Labels: DEV, cla: yes

#2002 webgpu: Fix the compile error in conv2d_naive shader
  tfjs-backend-webgpu/src/kernels/conv2d_naive_webgpu.ts
Labels: cla: yes

#1990 Update the diff script to be smarter and diff against the merge base.
  cloudbuild.yml
  scripts/diff.js
Labels: cla: yes

#2013 webgpu: Use (16, 1, 1) as the work group size for binary and unary ops
  tfjs-backend-webgpu/src/kernels/binary_op_webgpu.ts
  tfjs-backend-webgpu/src/kernels/unary_op_webgpu.ts
Labels: cla: yes

#2016 core: Add relu6
  tfjs-core/src/backends/backend.ts
  tfjs-core/src/backends/cpu/backend_cpu.ts
  tfjs-core/src/backends/webgl/backend_webgl.ts
  tfjs-core/src/backends/webgl/unaryop_gpu.ts
  tfjs-core/src/backends/webgl/unaryop_packed_gpu.ts
  tfjs-core/src/ops/relu_ops.ts
  tfjs-core/src/ops/unary_ops_test.ts
  tfjs-core/src/tensor.ts
Labels: cla: yes

#2035 webgpu: Improve benchmarks page readability.
  tfjs-backend-webgpu/benchmarks/main.css
  tfjs-backend-webgpu/benchmarks/main.js
  tfjs-backend-webgpu/package.json
Labels: DEV, cla: yes

#2037 core: Fuse relu6 activation
  tfjs-core/src/backends/cpu/backend_cpu.ts
  tfjs-core/src/backends/webgl/backend_webgl.ts
  tfjs-core/src/ops/fused_test.ts
  tfjs-core/src/ops/fused_util.ts
Labels: FEATURE, PERF, cla: yes

#2038 webgpu: Upgrade tfjs-core dependency.
  tfjs-backend-webgpu/package.json
  tfjs-backend-webgpu/src/backend_webgpu.ts
  tfjs-backend-webgpu/src/backend_webgpu_test.ts
  tfjs-backend-webgpu/src/index.ts
  tfjs-backend-webgpu/src/setup_test.ts
  tfjs-backend-webgpu/yarn.lock
Labels: DEV, cla: yes

#2027 fix incorrect Erf op output
  tfjs-core/src/backends/cpu/backend_cpu.ts
  tfjs-core/src/backends/webgl/unaryop_gpu.ts
  tfjs-core/src/ops/unary_ops_test.ts
Labels: cla: yes

#2032 Lazily instantiate the TextEncoder in platform_browser
  tfjs-core/src/platforms/platform_browser.ts
Labels: cla: yes

#2039 Bring back the dist importing lint rule
  package.json
  tfjs-backend-webgpu/cloudbuild.yml
  tfjs-backend-webgpu/src/setup_test.ts
  tfjs-backend-webgpu/src/test_util.ts
  tfjs-converter/cloudbuild.yml
  tfjs-converter/scripts/test_snippets.ts
  tfjs-data/cloudbuild.yml
  tfjs-data/src/test_node.ts
  tfjs-data/src/util/test_utils.ts
  tfjs-layers/cloudbuild.yml
  tfjs-layers/src/engine/training.ts
  tfjs-layers/src/models.ts
  tfjs-layers/src/models_test.ts
  tfjs-layers/src/types.ts
  tfjs-layers/src/utils/test_utils.ts
  tfjs-node-gpu/package.json
  tfjs-node/package.json
  tfjs-node/src/io/file_system_test.ts
  tfjs-node/src/nodejs_kernel_backend.ts
  tfjs-node/src/nodejs_kernel_backend_test.ts
  tfjs-node/src/run_tests.ts
  tfjs-node/src/tfjs_binding.ts
  tfjs-react-native/cloudbuild.yml
  tfjs-react-native/yarn.lock
  tfjs-vis/cloudbuild.yml
  tfjs-vis/src/show/history.ts
  tfjs-vis/src/show/model.ts
  tfjs/cloudbuild.yml
  tslint.json
  yarn.lock
Labels: cla: yes

#2040 Fix access to proto enum fields
  tfjs-converter/python/requirements.txt
  tfjs-converter/python/tensorflowjs/converters/fuse_prelu.py
Labels: cla: yes

#2028 Implement greater and greaterEqual
  tfjs-backend-webgpu/src/backend_webgpu.ts
  tfjs-backend-webgpu/src/kernels/binary_op_webgpu.ts
  tfjs-backend-webgpu/src/setup_test.ts
  tfjs-backend-webgpu/src/shader_preprocessor.ts
  tfjs-backend-webgpu/src/webgpu_util.ts
Labels: cla: yes

#2047 Replace mul+add with fma
  tfjs-backend-webgpu/src/kernels/depthwise_conv2d_webgpu.ts
  tfjs-backend-webgpu/src/kernels/matmul_webgpu.ts
Labels: cla: yes

#2045 [docs] Update setup instructions to reflect mandatory async-storage for React Native
  tfjs-react-native/README.md
Labels: cla: yes

#2052 Resolve to absolute paths before reading json files
  tfjs-converter/python/tensorflowjs/converters/tf_saved_model_conversion_v2.py
Labels: cla: yes

#2053 Bump automl alpha version
  tfjs-automl/package.json
  tfjs-automl/src/version.ts
Labels: cla: yes

#2051 core: Prevent eager unpacking of output for the packed reshape kernel.
  tfjs-core/src/backends/webgl/backend_webgl.ts
Labels: cla: yes

#2056 core: Fix tf.where on CPU to broadcast scalar condition.
  tfjs-core/src/backends/cpu/backend_cpu.ts
  tfjs-core/src/ops/logical_ops_test.ts
Labels: BUG, cla: yes

#2060 Revert "Replace mul+add with fma"
  tfjs-backend-webgpu/src/kernels/depthwise_conv2d_webgpu.ts
  tfjs-backend-webgpu/src/kernels/matmul_webgpu.ts
Labels: cla: yes

#2015 Add chrome on android to CI tests
  tfjs-core/karma.conf.js
  tfjs-core/scripts/test-ci.sh
  tfjs-core/src/backends/webgl/concat_packed_gpu.ts
  tfjs-core/src/backends/webgl/glsl_version.ts
  tfjs-core/src/backends/webgl/shader_compiler.ts
  tfjs-core/src/backends/webgl/unaryop_gpu.ts
  tfjs-core/src/ops/unary_ops_test.ts
Labels: cla: yes

#1995 Minor README fix for tfjs-react-native
  tfjs-react-native/README.md
Labels: cla: yes

#2012 [tfjs-vis] Support custom tickLabels with duplicate values in heatmaps
  tfjs-vis/demos/api/index.html
  tfjs-vis/src/render/confusion_matrix.ts
  tfjs-vis/src/render/heatmap.ts
  tfjs-vis/src/render/heatmap_test.ts
Labels: cla: yes

#2059 Add more Saved model integration tests
  tfjs/integration_tests/models/validation.ts
  tfjs/integration_tests/package.json
  tfjs/integration_tests/python/requirements.txt
  tfjs/integration_tests/python/requirements_gpu.txt
  tfjs/integration_tests/python/validation.py
  tfjs/integration_tests/yarn.lock
Labels: cla: yes

#2067 Add resource loader for reading resources
  tfjs-converter/python/setup.py
  tfjs-converter/python/tensorflowjs/BUILD
  tfjs-converter/python/tensorflowjs/converters/BUILD
  tfjs-converter/python/tensorflowjs/converters/tf_saved_model_conversion_v2.py
  tfjs-converter/python/tensorflowjs/resource_loader.py
  tfjs-converter/python/tensorflowjs/resource_loader_test.py
Labels: cla: yes

#2064 ArrayBuffer should not be deep cloned
  tfjs-data/src/dataset_test.ts
  tfjs-data/src/util/deep_map.ts
Labels: cla: yes

#2066 Add documentation for emsdk in home dir
  tfjs-backend-wasm/README.md
  tfjs-backend-wasm/toolchain/emcc.sh
Labels: cla: yes

#1997 [benchmarks] Upgrade to tfjs and tfjs-node 1.2.9
  tfjs/integration_tests/yarn.lock
Labels: cla: yes

#2072 Update tfjs-vis to 1.2.0.
  tfjs-vis/package.json
  tfjs-vis/src/version.ts
Labels: INTERNAL, cla: yes

#2058 [tfjs-converter] Strip unused ops during model conversion
  tfjs-converter/python/tensorflowjs/converters/tf_saved_model_conversion_v2.py
Labels: cla: yes

#2081 [tfjs-react-native] Update readme
  tfjs-react-native/README.md
  tfjs-react-native/package.json
Labels: cla: yes

#2083 [layers] Create utility function that maps fusable activation name to layers identifier, and add elu activation.
  tfjs-layers/integration_tests/tfjs2keras/package.json
  tfjs-layers/src/layers/convolutional.ts
  tfjs-layers/src/layers/core.ts
  tfjs-layers/src/utils/generic_utils.ts
Labels: cla: yes

#2088 [AutoML] Fix a bug when fetching `dict.txt` where path to `model.json` is relative
  tfjs-automl/package.json
  tfjs-automl/src/img_classification_test.ts
  tfjs-automl/src/object_detection_test.ts
  tfjs-automl/src/test_browser.ts
  tfjs-automl/src/test_node.ts
  tfjs-automl/src/util.ts
  tfjs-automl/src/util_test.ts
  tfjs-automl/src/version.ts
Labels: cla: yes

#2033 broken links
  CONTRIBUTING.md
  README.md
  tfjs-automl/README.md
  tfjs-core/README.md
  tfjs-layers/README.md
  tfjs-node/WINDOWS_TROUBLESHOOTING.md
  tfjs-react-native/README.md
Labels: cla: yes

#2087 webgpu: Fix argMax benchmark doesn't work
  tfjs-backend-webgpu/src/benchmark_ops_test.ts
Labels: cla: yes

#2092 [tfjs-vis] update vis demos to latest version
  tfjs-vis/demos/api/package.json
  tfjs-vis/demos/api/yarn.lock
  tfjs-vis/demos/mnist/package.json
  tfjs-vis/demos/mnist/yarn.lock
  tfjs-vis/demos/mnist_internals/package.json
  tfjs-vis/demos/mnist_internals/yarn.lock
Labels: cla: yes

#2085 webgpu: Lazily upload tensor data to SSBOs.
  tfjs-backend-webgpu/src/backend_webgpu.ts
  tfjs-backend-webgpu/src/backend_webgpu_test.ts
Labels: FEATURE, cla: yes, comp:webgpu

#2094 Only call register_prelu_op with open-source TensorFlow 1.X
  tfjs-converter/python/tensorflowjs/converters/fuse_prelu.py
Labels: cla: yes

#2095 webgpu: Use DataStorage class for storing tensor map.
  tfjs-backend-webgpu/src/backend_webgpu.ts
  tfjs-backend-webgpu/src/backend_webgpu_test.ts
  tfjs-core/src/globals.ts
  tfjs-node/src/nodejs_kernel_backend.ts
Labels: cla: yes

#1865 [tfjs-layers] Fix memory leak with loaded models containing nested Sequential layers
  tfjs-layers/src/engine/container.ts
  tfjs-layers/src/models_test.ts
Labels: cla: yes

#2097 Build node addon module from source in tfjs/integration
  tfjs/integration_tests/benchmark_layers.sh
  tfjs/integration_tests/yarn.lock
Labels: cla: yes

#2096 [converter] Remove standalone keras a dependency
  tfjs-converter/python/requirements.txt
Labels: cla: yes

#2073 Add protocol option to release script
  package.json
  scripts/release.ts
  yarn.lock
Labels: cla: yes

#2107 Export webcam and microphone config type in tf.data
  tfjs-data/src/index.ts
Labels: cla: yes

#2105 [layers] Fix RNNCell weight serialization
  tfjs-layers/src/layers/recurrent.ts
  tfjs-layers/src/layers/recurrent_test.ts
Labels: cla: yes

#2112 webgpu: Optimize maxpool with groupsize(4, 4, 4)
  tfjs-backend-webgpu/src/benchmark_ops_test.ts
  tfjs-backend-webgpu/src/kernels/conv2d_naive_webgpu.ts
  tfjs-backend-webgpu/src/kernels/depthwise_conv2d_webgpu.ts
  tfjs-backend-webgpu/src/kernels/maxpool_webgpu.ts
Labels: cla: yes

#2061 Fallback to cpu when the inputs size is small
  tfjs-backend-webgpu/src/backend_webgpu.ts
Labels: cla: yes

#2103 [Converter] Fix bug with aggressive closure minification
  tfjs-converter/src/data/compiled_api.ts
Labels: cla: yes

#2102 Update tfjs-core to 1.2.10.
  tfjs-core/package.json
  tfjs-core/scripts/test-integration.sh
  tfjs-core/src/version.ts
Labels: cla: yes

#2121 Update tfjs-layers, tfjs-converter, tfjs-data to 1.2.10, 1.2.10, 1.2.10.
  tfjs-converter/package.json
  tfjs-converter/python/tensorflowjs/version.py
  tfjs-converter/src/version.ts
  tfjs-converter/yarn.lock
  tfjs-data/package.json
  tfjs-data/src/version.ts
  tfjs-data/yarn.lock
  tfjs-layers/package.json
  tfjs-layers/src/version.ts
  tfjs-layers/yarn.lock
Labels: cla: yes

#2106 Fix an internal tfjs conversion failure for prelu fusing
  tfjs-converter/python/tensorflowjs/converters/fuse_prelu.py
  tfjs-converter/python/tensorflowjs/converters/tf_saved_model_conversion_v2_test.py
Labels: cla: yes
