Repository tensorflow/tfjs, pull requests merged in 2019-08, with the labels that each got.

#1786 Update tfjs to 1.2.6.
  package.json
  src/version.ts
  yarn.lock
Labels: cla: yes

#1797 Update tfjs to 1.2.7.
  package.json
  src/version.ts
  yarn.lock
Labels: INTERNAL, cla: yes

#1800 Add NSFW JS library/demo/GitHub
  GALLERY.md
Labels: cla: yes

#1799 Add Rock Paper Scissors example blog post
  GALLERY.md
Labels: cla: yes

#1812 Cleanup markdown files after monorepo merge & add tfjs cloudbuild.yml config.
  .gitignore
  CONTRIBUTING.md
  DEVELOPMENT.md
  cloudbuild.yml
  pull_request_template.md
Labels: cla: yes

#1815 Add build timeout and log dir settings to top-level cloudbuild.yml
  cloudbuild.yml
Labels: cla: yes

#1814 [tfjs-core] Fix the test-bundle-size script in core to work with the monorepo.
  tfjs-core/scripts/test-bundle-size.js
Labels: cla: yes

#1813 tfjs-core: Add input shapes to debug info.
  tfjs-core/benchmarks/index.html
  tfjs-core/src/engine.ts
  tfjs-core/src/profiler.ts
  tfjs-core/src/profiler_test.ts
Labels: cla: yes

#1822 tfjs-core: Clean up benchmarking page.
  tfjs-core/benchmarks/index.html
  tfjs-core/benchmarks/main.css
  tfjs-core/benchmarks/modelConfig.js
  tfjs-core/benchmarks/util.js
Labels: DEV, cla: yes

#1824 Add a prefix to the tfjs-core tag so we can do a release.
  tfjs-core/scripts/tag-version.js
Labels: cla: yes

#1828 Migrate more scripts to the monorepo setup.
  cloudbuild.yml
  scripts/diff.js
  tfjs-core/cloudbuild.yml
  tfjs-core/package.json
  tfjs-core/scripts/test-integration.js
  tfjs/cloudbuild.yml
  tfjs/integration_tests/models/common.ts
  tfjs/package.json
  tfjs/src/version.ts
  tfjs/tsconfig.json
  tfjs/tslint.json
  tfjs/yarn.lock
Labels: cla: yes

#1827 Fix release script to work with the monorepo.
  package.json
  scripts/release.ts
  tfjs/package.json
  yarn.lock
Labels: cla: yes

#1826 Update tfjs-core to 1.2.8.
  tfjs-core/package.json
  tfjs-core/src/version.ts
Labels: INTERNAL, cla: yes

#1831 Fix publish-npm script to work with the new repo.
  tfjs-core/scripts/publish-npm.sh
Labels: cla: yes

#1832 Use a dash instead of a space in the tag name.
  tfjs-core/scripts/tag-version.js
Labels: cla: yes

#1817 tfjs-webgpu: Add backend.time
  tfjs-core/src/debug_mode_test.ts
  tfjs-core/src/index.ts
  tfjs-core/src/profiler.ts
  tfjs-core/src/profiler_test.ts
  tfjs-core/src/util.ts
  tfjs-core/src/util_test.ts
  tfjs-webgpu/package.json
  tfjs-webgpu/rollup.config.js
  tfjs-webgpu/src/backend_webgpu.ts
  tfjs-webgpu/tsconfig.json
  tfjs-webgpu/yarn.lock
Labels: cla: yes

#1833 Get tfjs-core ready for TS 3.5
  tfjs-core/src/tensor.ts
Labels: cla: yes

#1836 Fix integration test
  tfjs-core/scripts/test-integration.js
  tfjs-core/src/ops/array_ops_test.ts
Labels: cla: yes

#1834 [tfjs-core] Ignore worker_node_test in webgpu karma's bundler
  tfjs-webgpu/karma.conf.js
Labels: cla: yes

#1837 Add tfjs-converter to the top-level cloudbuild.yml.
  cloudbuild.yml
Labels: cla: yes

#1823 tfjs-webgpu: Improved timing in benchmarks.
  tfjs-webgpu/karma.conf.js
  tfjs-webgpu/src/benchmark_ops_test.ts
Labels: FEATURE, cla: yes

#1829 [tfjs-core] Support newAxisMask in stridedSlice and make squeeze consistent with TF Py
  tfjs-core/src/backends/backend.ts
  tfjs-core/src/backends/cpu/backend_cpu.ts
  tfjs-core/src/backends/webgl/backend_webgl.ts
  tfjs-core/src/backends/webgl/strided_slice_gpu.ts
  tfjs-core/src/ops/slice_util.ts
  tfjs-core/src/ops/strided_slice.ts
  tfjs-core/src/ops/strided_slice_test.ts
  tfjs-core/src/tensor_test.ts
  tfjs-core/src/util.ts
Labels: cla: yes

#1839 tfjs-webgpu: Rename tfjs-webgpu to tfjs-backend-webgpu.
  cloudbuild.yml
  tfjs-backend-webgpu/.npmignore
  tfjs-backend-webgpu/.vscode/settings.json
  tfjs-backend-webgpu/README.md
  tfjs-backend-webgpu/cloudbuild.yml
  tfjs-backend-webgpu/karma.conf.js
  tfjs-backend-webgpu/package.json
  tfjs-backend-webgpu/rollup.config.js
  tfjs-backend-webgpu/scripts/test-ci.sh
  tfjs-backend-webgpu/src/backend_webgpu.ts
  tfjs-backend-webgpu/src/backend_webgpu_test.ts
  tfjs-backend-webgpu/src/benchmark_ops_test.ts
  tfjs-backend-webgpu/src/buffer_manager.ts
  tfjs-backend-webgpu/src/flags_webgpu.ts
  tfjs-backend-webgpu/src/index.ts
  tfjs-backend-webgpu/src/kernels/argminmax_webgpu.ts
  tfjs-backend-webgpu/src/kernels/binary_op_webgpu.ts
  tfjs-backend-webgpu/src/kernels/concat_webgpu.ts
  tfjs-backend-webgpu/src/kernels/conv2d_mm_webgpu.ts
  tfjs-backend-webgpu/src/kernels/conv2d_naive_webgpu.ts
  tfjs-backend-webgpu/src/kernels/from_pixels_webgpu.ts
  tfjs-backend-webgpu/src/kernels/matmul_packed_webgpu.ts
  tfjs-backend-webgpu/src/kernels/matmul_webgpu.ts
  tfjs-backend-webgpu/src/kernels/maxpool_webgpu.ts
  tfjs-backend-webgpu/src/kernels/pad_webgpu.ts
  tfjs-backend-webgpu/src/kernels/resize_bilinear_webgpu.ts
  tfjs-backend-webgpu/src/kernels/transpose_webgpu.ts
  tfjs-backend-webgpu/src/kernels/unary_op_webgpu.ts
  tfjs-backend-webgpu/src/kernels/webgpu_program.ts
  tfjs-backend-webgpu/src/matmul_test.ts
  tfjs-backend-webgpu/src/setup_test.ts
  tfjs-backend-webgpu/src/shader_preprocessor.ts
  tfjs-backend-webgpu/src/shader_util.ts
  tfjs-backend-webgpu/src/shader_util_test.ts
  tfjs-backend-webgpu/src/test_util.ts
  tfjs-backend-webgpu/src/webgpu_util.ts
  tfjs-backend-webgpu/src/webgpu_util_test.ts
  tfjs-backend-webgpu/tsconfig.json
  tfjs-backend-webgpu/tslint.json
  tfjs-backend-webgpu/yarn.lock
  tfjs-core/.npmignore
  tfjs.code-workspace
Labels: INTERNAL, cla: yes

#1835 Update release script to send a single PR for multiple pkgs.
  scripts/release.ts
Labels: cla: yes

#1841 Add cloudbuild.yml entry for tfjs-layers.
  cloudbuild.yml
Labels: cla: yes

#1849 Fix typo in doc and test suite title
  tfjs-core/src/globals.ts
  tfjs-core/src/ops/slice_test.ts
  tfjs-core/src/optimizers/rmsprop_optimizer_test.ts
Labels: cla: yes

#1855 Add uncommited changes to the release script to support multi-package PR version bumps.
  scripts/release.ts
Labels: cla: yes

#1852 Fix document state check error suggests a Inappropriate event
  tfjs-core/src/backends/webgl/backend_webgl.ts
Labels: cla: yes

#1856 Add the dir field to cloudbuild.yml files.
  tfjs-backend-webgpu/cloudbuild.yml
  tfjs-converter/cloudbuild.yml
  tfjs-data/cloudbuild.yml
  tfjs-layers/cloudbuild.yml
  tfjs-react-native/cloudbuild.yml
Labels: cla: yes

#1854 Update tfjs-layers, tfjs-converter, tfjs-data to 1.2.8, 1.2.8, 1.2.8.
  tfjs-converter/package.json
  tfjs-converter/python/tensorflowjs/version.py
  tfjs-converter/src/version.ts
  tfjs-data/package.json
  tfjs-data/src/version.ts
  tfjs-data/yarn.lock
  tfjs-layers/package.json
  tfjs-layers/src/version.ts
Labels: INTERNAL, cla: yes

#1860 Consolidate publish-npm.sh scripts.
  scripts/publish-npm.sh
  tfjs-converter/scripts/publish-npm.sh
  tfjs-data/scripts/publish-npm.sh
  tfjs-layers/scripts/publish-npm.sh
  tfjs/scripts/publish-npm.sh
Labels: cla: yes

#1859 tfjs-layers: Call fused conv2d kernel when possible.
  tfjs-layers/src/layers/convolutional.ts
  tfjs-layers/src/layers/convolutional_test.ts
  tfjs-layers/src/layers/core.ts
Labels: cla: yes

#1861 [tfjs-layers] Fix a silent error in L1/L2/L1L2 regularizer constructor
  tfjs-layers/src/regularizers.ts
  tfjs-layers/src/regularizers_test.ts
Labels: cla: yes

#1845 webgpu: Increase work per thread for binary / unary ops.
  tfjs-backend-webgpu/src/backend_webgpu.ts
  tfjs-backend-webgpu/src/kernels/binary_op_webgpu.ts
  tfjs-backend-webgpu/src/kernels/unary_op_webgpu.ts
  tfjs-backend-webgpu/src/setup_test.ts
  tfjs-backend-webgpu/src/shader_preprocessor.ts
Labels: cla: yes

#1862 Consolidate make-version, and tag-version scripts.
  scripts/make-version.js
  scripts/publish-npm.sh
  scripts/tag-version.js
  tfjs-backend-wasm/package.json
  tfjs-converter/scripts/make-version
  tfjs-core/package.json
  tfjs-core/scripts/make-version
  tfjs-data/package.json
  tfjs-data/scripts/build-npm.sh
  tfjs-data/scripts/make-version
  tfjs-data/scripts/tag-version
  tfjs-data/src/version.ts
  tfjs-layers/package.json
  tfjs-layers/scripts/build-npm.sh
  tfjs-layers/scripts/make-version
  tfjs-layers/scripts/tag-version
  tfjs-layers/src/version.ts
  tfjs/scripts/make-version
  tfjs/scripts/tag-version
  tfjs/yarn.lock
Labels: cla: yes

#1868 Chmod +x build-npm scripts.
  tfjs-data/scripts/build-npm.sh
  tfjs-layers/scripts/build-npm.sh
Labels: cla: yes

#1848 Fix incompatibility of signal.frame
  tfjs-core/src/ops/signal_ops.ts
  tfjs-core/src/ops/signal_ops_test.ts
Labels: cla: yes

#1870 Final fixes for publish-npm.
  scripts/publish-npm.sh
  scripts/tag-version.js
Labels: cla: yes

#1871 Update the tfjs-data => tfjs-layers dev dep to 1.2.8
  tfjs-data/package.json
  tfjs-data/yarn.lock
Labels: cla: yes

#1873 Have the release script call the new make-version script.
  scripts/release.ts
Labels: cla: yes

#1842 add proper comment to doc
  tfjs-core/src/util.ts
Labels: cla: yes

#1879 [tfjs] Fix integration tests and benchmarks to work with the monorepo.
  tfjs-node/scripts/build-npm-gpu.sh
  tfjs/integration_tests/benchmark_cloud.sh
  tfjs/integration_tests/benchmark_layers.sh
  tfjs/integration_tests/validate_converter.sh
Labels: cla: yes

#1863 Enable Cloud Build CI for tfjs-node
  cloudbuild.yml
  tfjs-node/cloudbuild.yml
Labels: cla: yes

#1874 Add tfjs-vis to cloudbuild.yml and setup whitelist for files to trigger all builds.
  .gitignore
  cloudbuild.yml
  scripts/diff.js
  tfjs-vis/cloudbuild.yml
  tfjs-vis/karma.conf.js
Labels: cla: yes

#1888 webgpu: Increase WPT for pad.
  tfjs-backend-webgpu/src/kernels/pad_webgpu.ts
Labels: cla: yes

#1872 Update tfjs to 1.2.8.
  tfjs/package.json
  tfjs/src/version.ts
  tfjs/yarn.lock
Labels: INTERNAL, cla: yes

#1889 Have publish-npm call yarn.
  scripts/publish-npm.sh
Labels: cla: yes

#1892 Follow up cleanup from pr/1879
  tfjs/integration_tests/benchmark_cloud.sh
  tfjs/integration_tests/benchmark_layers.sh
  tfjs/integration_tests/validate_converter.sh
Labels: cla: yes

#1890 tfjs-node: Update fusedMatMul interface to take config, exclude NHCW from tests.
  tfjs-core/src/ops/diag_test.ts
  tfjs-node/package.json
  tfjs-node/src/nodejs_kernel_backend.ts
  tfjs-node/src/run_tests.ts
  tfjs-node/yarn.lock
Labels: cla: yes

#1883 interactive CLI for converter
  tfjs-converter/python/requirements.txt
  tfjs-converter/python/setup.py
  tfjs-converter/python/tensorflowjs/BUILD
  tfjs-converter/python/tensorflowjs/__init__.py
  tfjs-converter/python/tensorflowjs/converters/BUILD
  tfjs-converter/python/tensorflowjs/converters/common.py
  tfjs-converter/python/tensorflowjs/converters/converter.py
  tfjs-converter/python/tensorflowjs/wizard.py
  tfjs-converter/python/tensorflowjs/wizard_test.py
Labels: cla: yes

#1901 Update tfjs-node to 1.2.8.
  tfjs-node/package.json
  tfjs-node/src/version.ts
Labels: INTERNAL, cla: yes

#1895 Fix flaky dropout test
  tfjs-layers/src/layers/core_test.ts
Labels: cla: yes

#1869 webgpu: Filter tests by env.specFilter.
  tfjs-backend-webgpu/karma.conf.js
  tfjs-backend-webgpu/package.json
  tfjs-backend-webgpu/src/setup_test.ts
Labels: DEV, cla: yes

#1887 tfjs-core: Pack additional unary ops for performance.
  tfjs-core/src/backends/webgl/backend_webgl.ts
  tfjs-core/src/backends/webgl/flags_webgl.ts
Labels: PERF, cla: yes, type:performance

#1899 [tfjs-node] Adds encodeJpeg and encodePng
  tfjs-node/binding/tfjs_backend.cc
  tfjs-node/src/image.ts
  tfjs-node/src/image_test.ts
  tfjs-node/src/node.ts
  tfjs-node/src/nodejs_kernel_backend.ts
Labels: cla: yes

#1938 [tfjs-react-native] webcam demo
  tfjs-react-native/integration_rn59/App.tsx
  tfjs-react-native/integration_rn59/android/app/src/main/java/com/integration_rn59/generated/BasePackageList.java
  tfjs-react-native/integration_rn59/android/build.gradle
  tfjs-react-native/integration_rn59/components/webcam/image_utils.ts
  tfjs-react-native/integration_rn59/components/webcam/style_transfer.ts
  tfjs-react-native/integration_rn59/components/webcam/webcam_demo.tsx
  tfjs-react-native/integration_rn59/ios/Podfile.lock
  tfjs-react-native/integration_rn59/package.json
  tfjs-react-native/integration_rn59/yarn.lock
Labels: cla: yes

#1944 [tfjs-react-native] RN alpha release
  tfjs-react-native/README.md
  tfjs-react-native/images/rn-styletransfer_1.jpg
  tfjs-react-native/images/rn-styletransfer_2.jpg
  tfjs-react-native/images/rn-styletransfer_3.jpg
  tfjs-react-native/images/rn-styletransfer_4.jpg
  tfjs-react-native/integration_rn59/components/diagnostic.tsx
  tfjs-react-native/integration_rn59/components/ml.ts
  tfjs-react-native/integration_rn59/components/webcam/webcam_demo.tsx
  tfjs-react-native/integration_rn59/package.json
  tfjs-react-native/integration_rn59/yarn.lock
  tfjs-react-native/karma.conf.js
  tfjs-react-native/package.json
  tfjs-react-native/src/bundle_resource_io.ts
  tfjs-react-native/src/bundle_resource_io_test.ts
  tfjs-react-native/src/platform_react_native.ts
  tfjs-react-native/yarn.lock
Labels: cla: yes

#1946 Add AutoML Edge library
  .gitignore
  tfjs-automl/.vscode/settings.json
  tfjs-automl/.vscode/tasks.json
  tfjs-automl/README.md
  tfjs-automl/demo/img_classification/.babelrc
  tfjs-automl/demo/img_classification/index.html
  tfjs-automl/demo/img_classification/index.js
  tfjs-automl/demo/img_classification/package.json
  tfjs-automl/demo/img_classification/yarn.lock
  tfjs-automl/karma.conf.js
  tfjs-automl/package.json
  tfjs-automl/rollup.config.js
  tfjs-automl/scripts/build-npm.sh
  tfjs-automl/src/img_classification.ts
  tfjs-automl/src/img_classification_test.ts
  tfjs-automl/src/index.ts
  tfjs-automl/src/index_test.ts
  tfjs-automl/src/test_browser.ts
  tfjs-automl/src/test_node.ts
  tfjs-automl/src/types.ts
  tfjs-automl/src/version.ts
  tfjs-automl/tsconfig.json
  tfjs-automl/tslint.json
  tfjs-automl/yarn.lock
Labels: cla: yes

#1949 Add .npmignore to the automl package
  tfjs-automl/.npmignore
Labels: cla: yes

#1939 Fuse ops for Prelu in TF graph
  tfjs-converter/python/setup.py
  tfjs-converter/python/tensorflowjs/converters/BUILD
  tfjs-converter/python/tensorflowjs/converters/common.py
  tfjs-converter/python/tensorflowjs/converters/fold_batch_norms.py
  tfjs-converter/python/tensorflowjs/converters/fuse_prelu.py
  tfjs-converter/python/tensorflowjs/converters/fuse_prelu_test.py
  tfjs-converter/python/tensorflowjs/converters/tf_saved_model_conversion_v2.py
  tfjs-converter/python/tensorflowjs/converters/tf_saved_model_conversion_v2_test.py
  tfjs-converter/python/tensorflowjs/op_list/basic_math.json
  tfjs-converter/src/executor/graph_executor.ts
  tfjs-converter/src/executor/graph_model.ts
  tfjs-converter/src/executor/graph_model_test.ts
  tfjs-converter/src/executor/model_rewrite.ts
  tfjs-converter/src/executor/model_rewrite_test.ts
  tfjs-converter/src/operations/executors/convolution_executor.ts
  tfjs-converter/src/operations/executors/convolution_executor_test.ts
  tfjs-converter/src/operations/op_list/basic_math.ts
Labels: cla: yes
