Repository tensorflow/tfjs, pull requests merged in 2019-11, with the labels that each got.

#2306 fix the versions missing from the model topology json
  tfjs-converter/python/tensorflowjs/converters/converter_test.py
  tfjs-converter/python/tensorflowjs/converters/fold_batch_norms.py
  tfjs-converter/python/tensorflowjs/converters/fuse_prelu.py
  tfjs-converter/python/tensorflowjs/converters/tf_saved_model_conversion_v2.py
  tfjs-converter/python/tensorflowjs/converters/tf_saved_model_conversion_v2_test.py
  tfjs-converter/python/test_pip_package.py
Labels: cla: yes

#2308 sync g3 change to github
  tfjs-converter/python/tensorflowjs/converters/tf_saved_model_conversion_v2_test.py
Labels: cla: yes

#2310 fix g3 errors
  tfjs-converter/python/tensorflowjs/converters/converter_test.py
  tfjs-converter/python/tensorflowjs/converters/fuse_prelu.py
  tfjs-converter/python/tensorflowjs/converters/tf_saved_model_conversion_v2_test.py
  tfjs-converter/python/test_pip_package.py
Labels: cla: yes

#2311 Fix g3 errors
  tfjs-converter/python/tensorflowjs/converters/converter_test.py
  tfjs-converter/python/tensorflowjs/converters/tf_saved_model_conversion_v2_test.py
  tfjs-converter/python/test_pip_package.py
Labels: cla: yes

#2303 [WASM] Add `Concat` and `Transpose` kernels
  .vscode/settings.json
  tfjs-backend-wasm/scripts/cpplint.js
  tfjs-backend-wasm/src/backend_wasm.ts
  tfjs-backend-wasm/src/cc/BUILD
  tfjs-backend-wasm/src/cc/backend.cc
  tfjs-backend-wasm/src/cc/backend.h
  tfjs-backend-wasm/src/cc/kernels/BatchMatMul.cc
  tfjs-backend-wasm/src/cc/kernels/Transpose.cc
  tfjs-backend-wasm/src/cc/util.cc
  tfjs-backend-wasm/src/cc/util.h
  tfjs-backend-wasm/src/cc/util_test.cc
  tfjs-backend-wasm/src/kernels/Cast.ts
  tfjs-backend-wasm/src/kernels/Concat.ts
  tfjs-backend-wasm/src/kernels/Slice.ts
  tfjs-backend-wasm/src/kernels/Transpose.ts
  tfjs-backend-wasm/src/kernels/all_kernels.ts
  tfjs-backend-wasm/src/setup_test.ts
  tfjs-core/src/jasmine_util.ts
  tfjs-core/src/ops/concat_split.ts
  tfjs-core/src/ops/transpose.ts
  tfjs-core/src/ops/transpose_test.ts
Labels: cla: yes

#2316 [WASM] Update to latest emsdk
  tfjs-backend-wasm/.bazelrc
  tfjs-backend-wasm/.vscode/c_cpp_properties.json
  tfjs-backend-wasm/README.md
  tfjs-backend-wasm/scripts/build-ci.sh
  tfjs-backend-wasm/src/cc/kernels/FusedBatchNorm.cc
  tfjs-backend-wasm/toolchain/cc_toolchain_config.bzl
  tfjs-backend-wasm/toolchain/emar.sh
  tfjs-backend-wasm/toolchain/emcc.sh
Labels: cla: yes

#2318 Update tfjs-vis to 1.3.0.
  tfjs-vis/package.json
  tfjs-vis/src/version.ts
Labels: INTERNAL, cla: yes

#2228 Docs improvement, better label to point out 'Good places to start'
  CONTRIBUTING.md
Labels: cla: yes

#2319 [tfjs-vis] Update vis demos to v1.3.0
  tfjs-vis/demos/api/index.html
  tfjs-vis/demos/api/package.json
  tfjs-vis/demos/api/yarn.lock
  tfjs-vis/demos/mnist/index.html
  tfjs-vis/demos/mnist/index.js
  tfjs-vis/demos/mnist/package.json
  tfjs-vis/demos/mnist/yarn.lock
  tfjs-vis/demos/mnist_internals/package.json
  tfjs-vis/demos/mnist_internals/yarn.lock
Labels: cla: yes

#2321 [WASM] Support multiple dispose callback functions for the same tensor id.
  tfjs-backend-wasm/package.json
  tfjs-backend-wasm/src/cc/backend.cc
  tfjs-backend-wasm/src/cc/backend.h
  tfjs-backend-wasm/src/cc/backend_test.cc
  tfjs-backend-wasm/src/cc/binary.h
  tfjs-backend-wasm/src/cc/kernels/Add.cc
  tfjs-backend-wasm/src/cc/kernels/BatchMatMul.cc
  tfjs-backend-wasm/src/cc/kernels/Div.cc
  tfjs-backend-wasm/src/cc/kernels/FusedBatchNorm.cc
  tfjs-backend-wasm/src/cc/kernels/Max.cc
  tfjs-backend-wasm/src/cc/kernels/Min.cc
  tfjs-backend-wasm/src/cc/kernels/Mul.cc
  tfjs-backend-wasm/src/cc/kernels/Prelu.cc
  tfjs-backend-wasm/src/cc/kernels/Sub.cc
  tfjs-backend-wasm/src/cc/kernels/Transpose.cc
  tfjs-backend-wasm/src/cc/unary.h
  tfjs-backend-wasm/src/cc/util.h
Labels: cla: yes

#2324 [WASM] Add `const` in C++ where applicable
  tfjs-backend-wasm/src/cc/backend.cc
  tfjs-backend-wasm/src/cc/util.cc
  tfjs-backend-wasm/src/cc/util.h
Labels: cla: yes

#2312 add output for noop and tensorArrayExit,
  tfjs-converter/src/operations/executors/control_executor.ts
  tfjs-converter/src/operations/executors/graph_executor.ts
  tfjs-converter/src/operations/executors/graph_executor_test.ts
Labels: cla: yes

#2325 rely on only the tensorflow cpu pip
  tfjs-converter/python/requirements.txt
Labels: cla: yes

#2132 [tfjs-react-native] add decodeJpeg function
  tfjs-react-native/README.md
  tfjs-react-native/package.json
  tfjs-react-native/src/decode_image.ts
  tfjs-react-native/src/decode_image_test.ts
  tfjs-react-native/src/index.ts
  tfjs-react-native/yarn.lock
Labels: cla: yes, comp:react-native

#2332 fix converter validation test
  tfjs/integration_tests/python/validation.py
Labels: cla: yes

#2313 [tfjs/integration_tests] Upgrade tfjs and tensorflowjs
  tfjs/integration_tests/package.json
  tfjs/integration_tests/python/requirements.txt
  tfjs/integration_tests/yarn.lock
Labels: cla: yes

#2314 Fix typo in tfjs-react-native example
  tfjs-react-native/integration_rn59/components/mobilenet_demo.tsx
Labels: cla: yes

#2283 [WASM] Add Conv2D that calls into xnn pack.
  .vscode/settings.json
  tfjs-backend-wasm/WORKSPACE
  tfjs-backend-wasm/src/cc/BUILD
  tfjs-backend-wasm/src/cc/backend.cc
  tfjs-backend-wasm/src/cc/kernels/Conv2D.cc
  tfjs-backend-wasm/src/cc/kernels/Conv2D.h
  tfjs-backend-wasm/src/cc/kernels/Conv2D_test.cc
  tfjs-backend-wasm/src/kernels/Conv2D.ts
  tfjs-backend-wasm/src/setup_test.ts
  tfjs-core/src/backends/backend.ts
  tfjs-core/src/engine_test.ts
  tfjs-core/src/kernel_registry.ts
  tfjs-core/src/ops/conv.ts
  tfjs-core/src/ops/conv_util.ts
Labels: cla: yes

#2331 [tfjs-react-native] update decodeJpeg readme
  tfjs-react-native/README.md
Labels: cla: yes

#2342 [WASM] Add useful accessors on TensorInfo
  tfjs-backend-wasm/src/cc/backend.cc
  tfjs-backend-wasm/src/cc/backend.h
  tfjs-backend-wasm/src/cc/binary.h
  tfjs-backend-wasm/src/cc/kernels/BatchMatMul.cc
  tfjs-backend-wasm/src/cc/kernels/Conv2D.cc
  tfjs-backend-wasm/src/cc/kernels/FusedBatchNorm.cc
  tfjs-backend-wasm/src/cc/kernels/Max.cc
  tfjs-backend-wasm/src/cc/kernels/Min.cc
  tfjs-backend-wasm/src/cc/kernels/Prelu.cc
  tfjs-backend-wasm/src/cc/kernels/Transpose.cc
  tfjs-backend-wasm/src/cc/unary.h
Labels: cla: yes

#2320 [core]Add divNoNan op
  tfjs-core/src/ops/binary_ops.ts
  tfjs-core/src/ops/binary_ops_test.ts
  tfjs-core/src/tensor.ts
Labels: cla: yes

#2340 simplify install script, remove dependency to yarn
  tfjs-node-gpu/integration/typescript/package.json
  tfjs-node-gpu/package.json
Labels: cla: yes

#2337 remove the nodes that are skipped during batch norm folding for control node inputs
  tfjs-converter/python/tensorflowjs/converters/fold_batch_norms.py
Labels: cla: yes

#2333 added support prelu op
  tfjs-converter/docs/supported_ops.md
  tfjs-converter/src/operations/executors/basic_math_executor.ts
  tfjs-converter/src/operations/executors/basic_math_executor_test.ts
Labels: cla: yes

#2346 [layers] Properly support channelsFirst dataFormat in Flatten layer
  tfjs-layers/src/exports_layers.ts
  tfjs-layers/src/layers/core.ts
  tfjs-layers/src/layers/core_test.ts
  tfjs-layers/src/model_save_test.ts
Labels: cla: yes

#2334 [node] Add prep-gpu for windows system
  tfjs-node-gpu/package.json
  tfjs-node-gpu/prep-gpu-windows.bat
  tfjs-node-gpu/prep-gpu.sh
  tfjs-node/scripts/ensure-cpu-gpu-packages-align.js
Labels: cla: yes

#2344 [WASM] Transpose the filter of the convolution before calling xnnpack.
  tfjs-backend-wasm/src/cc/BUILD
  tfjs-backend-wasm/src/cc/backend.h
  tfjs-backend-wasm/src/cc/kernels/Conv2D.cc
  tfjs-backend-wasm/src/cc/kernels/Conv2D_test.cc
  tfjs-backend-wasm/src/cc/kernels/Transpose.cc
  tfjs-backend-wasm/src/cc/transpose_impl.cc
  tfjs-backend-wasm/src/cc/transpose_impl.h
  tfjs-core/src/ops/conv2d_test.ts
Labels: cla: yes

#2347 [Core] Fix bug with printing complex64 numbers.
  tfjs-core/src/tensor_format.ts
  tfjs-core/src/tensor_test.ts
Labels: cla: yes

#2326 add signature def to model.json
  tfjs-converter/python/tensorflowjs/converters/common.py
  tfjs-converter/python/tensorflowjs/converters/converter_test.py
  tfjs-converter/python/tensorflowjs/converters/tf_saved_model_conversion_v2.py
  tfjs-converter/python/tensorflowjs/converters/tf_saved_model_conversion_v2_test.py
  tfjs-converter/python/test_pip_package.py
Labels: cla: yes

#2352 fix the Concat and ConcatV2 op
  tfjs-converter/python/tensorflowjs/op_list/slice_join.json
  tfjs-converter/src/operations/executors/slice_join_executor.ts
  tfjs-converter/src/operations/executors/slice_join_executor_test.ts
  tfjs-converter/src/operations/op_list/slice_join.ts
Labels: cla: yes

#2297 webgpu: add dilated convolution support
  tfjs-backend-webgpu/src/kernels/conv2d_mm_webgpu.ts
  tfjs-backend-webgpu/src/kernels/conv2d_naive_webgpu.ts
  tfjs-backend-webgpu/src/kernels/depthwise_conv2d_webgpu.ts
  tfjs-backend-webgpu/src/setup_test.ts
Labels: cla: yes

#2369 [layers] Add SpatialDropout1D Layer
  tfjs-layers/src/exports_layers.ts
  tfjs-layers/src/layers/core.ts
  tfjs-layers/src/layers/core_test.ts
Labels: cla: yes

#2307 [wasm] Add CropAndResize kernel.
  tfjs-backend-wasm/scripts/cpplint.js
  tfjs-backend-wasm/src/cc/BUILD
  tfjs-backend-wasm/src/cc/kernels/CropAndResize.cc
  tfjs-backend-wasm/src/kernels/CropAndResize.ts
  tfjs-backend-wasm/src/kernels/all_kernels.ts
  tfjs-backend-wasm/src/setup_test.ts
  tfjs-core/src/ops/image_ops.ts
Labels: cla: yes

#2372 webgpu: fix browser load issue when testing on Windows
  tfjs-backend-webgpu/package.json
Labels: cla: yes

#2355 [Core] Update to TypeScript 3.6.3.
  tfjs-core/package.json
  tfjs-core/test.html
  tfjs-core/yarn.lock
Labels: cla: yes

#2368 do not quantize int32 tensors
  tfjs-converter/python/tensorflowjs/write_weights.py
  tfjs-converter/python/tensorflowjs/write_weights_test.py
Labels: cla: yes

#2371 [layers] Add masking support to tf.layers.bidirectional()
  tfjs-layers/src/layers/wrappers.ts
  tfjs-layers/src/layers/wrappers_test.ts
Labels: cla: yes

#2373 [webgpu] Upgrade to tfjs-core 1.3.
  tfjs-backend-webgpu/package.json
  tfjs-backend-webgpu/src/backend_webgpu.ts
  tfjs-backend-webgpu/src/backend_webgpu_test.ts
  tfjs-backend-webgpu/src/setup_test.ts
  tfjs-backend-webgpu/yarn.lock
Labels: cla: yes

#2376 Revert "[Core] Update to TypeScript 3.6.3. (#2355)"
  package.json
  tfjs-backend-wasm/package.json
  tfjs-backend-wasm/yarn.lock
  tfjs-core/package.json
  tfjs-core/test.html
  tfjs-core/yarn.lock
  yarn.lock
Labels: cla: yes

#2379 [core] use ModelTensorInfo in MetaGraphInfo
  tfjs-core/src/index.ts
  tfjs-core/src/model_types.ts
Labels: cla: yes

#2381 move signature def to userDefinedMetadata section
  tfjs-converter/python/tensorflowjs/converters/common.py
  tfjs-converter/python/tensorflowjs/converters/converter_test.py
  tfjs-converter/python/tensorflowjs/converters/tf_saved_model_conversion_v2.py
  tfjs-converter/python/tensorflowjs/converters/tf_saved_model_conversion_v2_test.py
  tfjs-converter/python/test_pip_package.py
Labels: cla: yes

#2380 Update tfjs-core to 1.3.2.
  tfjs-core/package.json
  tfjs-core/src/index.ts
  tfjs-core/src/model_types.ts
  tfjs-core/src/version.ts
Labels: INTERNAL, cla: yes

#2343 [converter] Add support for op DivNoNan
  tfjs-converter/docs/supported_ops.md
  tfjs-converter/package.json
  tfjs-converter/python/tensorflowjs/op_list/arithmetic.json
  tfjs-converter/src/operations/executors/arithmetic_executor.ts
  tfjs-converter/src/operations/executors/arithmetic_executor_test.ts
  tfjs-converter/src/operations/op_list/arithmetic.ts
  tfjs-converter/yarn.lock
Labels: cla: yes

#2382 Update tfjs-layers, tfjs-converter, tfjs-data to 1.3.2, 1.3.2, 1.3.2.
  tfjs-converter/package.json
  tfjs-converter/python/tensorflowjs/version.py
  tfjs-converter/src/version.ts
  tfjs-data/package.json
  tfjs-data/src/version.ts
  tfjs-data/yarn.lock
  tfjs-layers/package.json
  tfjs-layers/src/version.ts
  tfjs-layers/yarn.lock
Labels: INTERNAL, cla: yes

#2383 Update tfjs to 1.3.2.
  tfjs/package.json
  tfjs/src/version.ts
  tfjs/yarn.lock
Labels: INTERNAL, cla: yes

#2351 [node] Add divnonan in tfjs-node
  tfjs-node/src/nodejs_kernel_backend.ts
Labels: cla: yes

#2385 Update tfjs-node, tfjs-node-gpu to 1.3.2, 1.3.2.
  tfjs-node-gpu/package.json
  tfjs-node-gpu/yarn.lock
  tfjs-node/package.json
  tfjs-node/src/version.ts
  tfjs-node/yarn.lock
Labels: INTERNAL, cla: yes

#2353 [node] Use ModelTensorInfo when read SavedModel
  tfjs-node/src/saved_model.ts
  tfjs-node/src/saved_model_test.ts
Labels: cla: yes

#2336 [node] Add SavedModel execution
  tfjs-node-gpu/test_objects/saved_model/module_with_multiple_signatures/saved_model.pb
  tfjs-node-gpu/test_objects/saved_model/module_with_multiple_signatures/variables/variables.data-00000-of-00001
  tfjs-node-gpu/test_objects/saved_model/module_with_multiple_signatures/variables/variables.index
  tfjs-node-gpu/test_objects/saved_model/times_three_float/saved_model.pb
  tfjs-node-gpu/test_objects/saved_model/times_three_float/variables/variables.data-00000-of-00001
  tfjs-node-gpu/test_objects/saved_model/times_three_float/variables/variables.index
  tfjs-node-gpu/test_objects/saved_model/times_two_int/saved_model.pb
  tfjs-node-gpu/test_objects/saved_model/times_two_int/variables/variables.data-00000-of-00001
  tfjs-node-gpu/test_objects/saved_model/times_two_int/variables/variables.index
  tfjs-node/binding/tfjs_backend.cc
  tfjs-node/binding/tfjs_backend.h
  tfjs-node/binding/tfjs_binding.cc
  tfjs-node/src/nodejs_kernel_backend.ts
  tfjs-node/src/saved_model.ts
  tfjs-node/src/saved_model_test.ts
  tfjs-node/src/tfjs_binding.ts
  tfjs-node/test_objects/saved_model/module_with_multiple_signatures/saved_model.pb
  tfjs-node/test_objects/saved_model/module_with_multiple_signatures/variables/variables.data-00000-of-00001
  tfjs-node/test_objects/saved_model/module_with_multiple_signatures/variables/variables.index
  tfjs-node/test_objects/saved_model/times_three_float/saved_model.pb
  tfjs-node/test_objects/saved_model/times_three_float/variables/variables.data-00000-of-00001
  tfjs-node/test_objects/saved_model/times_three_float/variables/variables.index
  tfjs-node/test_objects/saved_model/times_two_int/saved_model.pb
  tfjs-node/test_objects/saved_model/times_two_int/variables/variables.data-00000-of-00001
  tfjs-node/test_objects/saved_model/times_two_int/variables/variables.index
Labels: cla: yes

#2389 the tensorflow cpu pip fails on mac
  tfjs-converter/python/requirements.txt
Labels: cla: yes

#2388 fix padding_test.ts & 'for .. in' to 'for .. of'
  tfjs-core/src/engine.ts
  tfjs-layers/src/engine/training_dataset.ts
  tfjs-layers/src/layers/padding_test.ts
Labels: cla: yes

#2392 added metadata to the model artifacts on the loaders
  tfjs-core/src/io/browser_files.ts
  tfjs-core/src/io/browser_files_test.ts
  tfjs-core/src/io/http.ts
  tfjs-core/src/io/http_test.ts
  tfjs-core/src/io/local_storage.ts
  tfjs-core/src/io/local_storage_test.ts
  tfjs-react-native/integration_rn59/components/ml.ts
Labels: cla: yes

#2404 [WASM] Add `PadV2` kernel
  tfjs-backend-wasm/src/cc/BUILD
  tfjs-backend-wasm/src/cc/kernels/PadV2.cc
  tfjs-backend-wasm/src/cc/util.h
  tfjs-backend-wasm/src/kernels/PadV2.ts
  tfjs-backend-wasm/src/setup_test.ts
  tfjs-core/src/kernel_registry.ts
  tfjs-core/src/ops/array_ops.ts
  tfjs-core/src/ops/pad_test.ts
Labels: cla: yes

#2339 webgpu: Add WEBGPU_USE_LOW_POWER_GPU flag
  tfjs-backend-webgpu/src/flags_webgpu.ts
  tfjs-backend-webgpu/src/index.ts
Labels: cla: yes

#2402 webgpu: Fix the delayed mode error
  tfjs-backend-webgpu/src/backend_webgpu.ts
Labels: cla: yes

#2405 [WASM] Add `ClipByValue`
  tfjs-backend-wasm/src/cc/BUILD
  tfjs-backend-wasm/src/cc/kernels/ClipByValue.cc
  tfjs-backend-wasm/src/cc/kernels/ClipByValue.h
  tfjs-backend-wasm/src/cc/kernels/ClipByValue_test.cc
  tfjs-backend-wasm/src/kernels/ClipByValue.ts
  tfjs-backend-wasm/src/kernels/all_kernels.ts
  tfjs-backend-wasm/src/setup_test.ts
  tfjs-core/src/ops/unary_ops.ts
  tfjs-core/src/ops/unary_ops_test.ts
Labels: cla: yes

#2396 [wasm] Add maxPool kernel.
  tfjs-backend-wasm/package.json
  tfjs-backend-wasm/src/cc/BUILD
  tfjs-backend-wasm/src/cc/kernels/MaxPool.cc
  tfjs-backend-wasm/src/cc/kernels/MaxPool.h
  tfjs-backend-wasm/src/cc/kernels/MaxPool_test.cc
  tfjs-backend-wasm/src/kernels/MaxPool.ts
  tfjs-backend-wasm/src/kernels/all_kernels.ts
  tfjs-backend-wasm/src/setup_test.ts
  tfjs-core/src/ops/pool.ts
Labels: cla: yes

#2408 [WASM] Add `Addn` used by MobileNet
  tfjs-backend-wasm/src/cc/BUILD
  tfjs-backend-wasm/src/cc/kernels/AddN.cc
  tfjs-backend-wasm/src/kernels/AddN.ts
  tfjs-backend-wasm/src/kernels/all_kernels.ts
  tfjs-backend-wasm/src/setup_test.ts
  tfjs-core/src/ops/binary_ops.ts
Labels: cla: yes

#2406 Fix C++ char array creation syntax.
  tfjs-node/binding/tfjs_backend.cc
Labels: cla: yes

#2393 Support GraphModel execution with SignatureDef keys
  tfjs-converter/src/executor/graph_executor.ts
  tfjs-converter/src/executor/graph_executor_test.ts
  tfjs-converter/src/executor/graph_model.ts
  tfjs-converter/src/executor/graph_model_test.ts
  tfjs-converter/src/executor/model_analysis.ts
  tfjs-converter/src/operations/operation_mapper.ts
  tfjs-converter/src/operations/operation_mapper_test.ts
  tfjs-converter/src/operations/types.ts
Labels: cla: yes

#2410 [core] Do not fail if half float extension not found and we are not forcing half float rendering.
  tfjs-core/src/backends/webgl/gpgpu_context.ts
Labels: cla: yes

#2417 [core] Rename fused ops for internal scopeName tracking.
  tfjs-core/src/ops/fused_ops.ts
Labels: cla: yes

#2416 [WASM] Implement `backend.time()` used for profiling
  tfjs-backend-wasm/src/backend_wasm.ts
Labels: cla: yes

#2411 [wasm] Add AvgPool kernel.
  tfjs-backend-wasm/karma.conf.js
  tfjs-backend-wasm/src/cc/BUILD
  tfjs-backend-wasm/src/cc/kernels/AvgPool.cc
  tfjs-backend-wasm/src/cc/kernels/AvgPool.h
  tfjs-backend-wasm/src/cc/kernels/AvgPool_test.cc
  tfjs-backend-wasm/src/kernels/AvgPool.ts
  tfjs-backend-wasm/src/kernels/all_kernels.ts
  tfjs-backend-wasm/src/setup_test.ts
  tfjs-core/src/ops/pool.ts
Labels: cla: yes

#2414 [WASM] Add `NonMaxSuppressionV3`
  tfjs-backend-wasm/src/backend_wasm.ts
  tfjs-backend-wasm/src/cc/BUILD
  tfjs-backend-wasm/src/cc/kernels/NonMaxSuppressionV3.cc
  tfjs-backend-wasm/src/kernels/NonMaxSuppressionV3.ts
  tfjs-backend-wasm/src/kernels/all_kernels.ts
  tfjs-backend-wasm/src/setup_test.ts
  tfjs-backend-wasm/wasm-out/tfjs-backend-wasm.d.ts
  tfjs-core/src/ops/image_ops.ts
Labels: cla: yes

#2238 tf.broadcastTo
  tfjs-core/src/ops/array_ops.ts
  tfjs-core/src/ops/array_ops_test.ts
Labels: cla: yes

#2420 [webgpu] Update device initialization to reflect spec change.
  tfjs-backend-webgpu/src/backend_webgpu.ts
Labels: cla: yes

#2422 [core] Relax fusing logic.
  tfjs-core/src/ops/fused_ops.ts
  tfjs-core/src/ops/fused_util.ts
Labels: cla: yes

#2421 [WASM] Update to latest XNNPACK and fix a potential bug in conv2d
  tfjs-backend-wasm/WORKSPACE
  tfjs-backend-wasm/src/backend_wasm.ts
  tfjs-backend-wasm/src/cc/backend.cc
  tfjs-backend-wasm/src/cc/conv2d_impl.cc
  tfjs-backend-wasm/src/cc/kernels/Conv2D_test.cc
Labels: cla: yes

#2226 tf.linalg.bandPart
  tfjs-core/src/ops/linalg_ops.ts
  tfjs-core/src/ops/linalg_ops_test.ts
Labels: cla: yes

#2426 [WASM] Add `FloorDiv` used by PoseNet
  tfjs-backend-wasm/src/cc/BUILD
  tfjs-backend-wasm/src/cc/kernels/FloorDiv.cc
  tfjs-backend-wasm/src/kernels/FloorDiv.ts
  tfjs-backend-wasm/src/kernels/all_kernels.ts
  tfjs-backend-wasm/src/setup_test.ts
  tfjs-core/src/ops/binary_ops.ts
Labels: cla: yes

#2429 [core, wasm] Modularize `FromPixels` and make it work for the wasm backend.
  tfjs-core/src/backends/backend.ts
  tfjs-core/src/backends/cpu/backend_cpu.ts
  tfjs-core/src/backends/cpu/backend_cpu_test.ts
  tfjs-core/src/backends/webgl/all_kernels.ts
  tfjs-core/src/backends/webgl/backend_webgl.ts
  tfjs-core/src/backends/webgl/backend_webgl_test.ts
  tfjs-core/src/backends/webgl/canvas_util.ts
  tfjs-core/src/backends/webgl/canvas_util_test.ts
  tfjs-core/src/backends/webgl/fromPixels.ts
  tfjs-core/src/engine.ts
  tfjs-core/src/ops/browser.ts
Labels: cla: yes

#2432 [wasm] Add relu, relu6 kernels.
  tfjs-backend-wasm/src/cc/BUILD
  tfjs-backend-wasm/src/cc/kernels/Relu.cc
  tfjs-backend-wasm/src/cc/kernels/Relu6.cc
  tfjs-backend-wasm/src/kernels/Relu.ts
  tfjs-backend-wasm/src/kernels/Relu6.ts
  tfjs-backend-wasm/src/kernels/all_kernels.ts
  tfjs-backend-wasm/src/setup_test.ts
  tfjs-core/src/ops/relu_ops.ts
Labels: FEATURE, cla: yes

#2433 [wasm] Add `ArgMax` kernel
  tfjs-backend-wasm/src/cc/BUILD
  tfjs-backend-wasm/src/cc/kernels/ArgMax.cc
  tfjs-backend-wasm/src/kernels/ArgMax.ts
  tfjs-backend-wasm/src/kernels/all_kernels.ts
  tfjs-backend-wasm/src/setup_test.ts
  tfjs-core/src/ops/reduction_ops.ts
Labels: cla: yes

#2434 add output format auto fill for frozen model and required param check
  tfjs-converter/python/tensorflowjs/converters/converter.py
Labels: cla: yes

#2431 [webgpu] Add slice
  tfjs-backend-webgpu/src/backend_webgpu.ts
  tfjs-backend-webgpu/src/benchmark_ops_test.ts
  tfjs-backend-webgpu/src/kernels/slice_webgpu.ts
  tfjs-backend-webgpu/src/setup_test.ts
Labels: cla: yes

#2435 [node] Fix typo when parsing string in c bindings
  tfjs-node/binding/utils.h
  tfjs-node/src/saved_model_test.ts
  tfjs-node/test_objects/saved_model/model_multi_output/saved_model.pb
  tfjs-node/test_objects/saved_model/model_multi_output/variables/variables.data-00000-of-00001
  tfjs-node/test_objects/saved_model/model_multi_output/variables/variables.index
Labels: cla: yes

#2438 [node] Add node n-api version 5 for new node releases
  .gitignore
  tfjs-node-gpu/package.json
  tfjs-node-gpu/test_objects/saved_model/model_multi_output/saved_model.pb
  tfjs-node-gpu/test_objects/saved_model/model_multi_output/variables/variables.data-00000-of-00001
  tfjs-node-gpu/test_objects/saved_model/model_multi_output/variables/variables.index
  tfjs-node/.npmignore
  tfjs-node/package.json
Labels: cla: yes

#2436 [wasm] Add resizeBilinear kernel.
  tfjs-backend-wasm/src/cc/BUILD
  tfjs-backend-wasm/src/cc/interpolate_bilinear_impl.cc
  tfjs-backend-wasm/src/cc/interpolate_bilinear_impl.h
  tfjs-backend-wasm/src/cc/kernels/CropAndResize.cc
  tfjs-backend-wasm/src/cc/kernels/ResizeBilinear.cc
  tfjs-backend-wasm/src/kernels/ResizeBilinear.ts
  tfjs-backend-wasm/src/kernels/all_kernels.ts
  tfjs-backend-wasm/src/setup_test.ts
  tfjs-core/src/backends/cpu/backend_cpu.ts
  tfjs-core/src/ops/image_ops.ts
  tfjs-core/src/ops/resize_bilinear_test.ts
Labels: cla: yes

#2444 [node] Add installation instruction for raspberry pi
  tfjs-node/README.md
Labels: cla: yes

#2439 add support to fused depthwise conv2d
  tfjs-converter/python/setup.py
  tfjs-converter/python/tensorflowjs/converters/BUILD
  tfjs-converter/python/tensorflowjs/converters/common.py
  tfjs-converter/python/tensorflowjs/converters/fold_batch_norms.py
  tfjs-converter/python/tensorflowjs/converters/fuse_depthwise_conv2d.py
  tfjs-converter/python/tensorflowjs/converters/fuse_depthwise_conv2d_test.py
  tfjs-converter/python/tensorflowjs/converters/fuse_prelu.py
  tfjs-converter/python/tensorflowjs/converters/fuse_prelu_test.py
  tfjs-converter/python/tensorflowjs/converters/graph_rewrite_util.py
  tfjs-converter/python/tensorflowjs/converters/tf_saved_model_conversion_v2.py
  tfjs-converter/python/tensorflowjs/converters/tf_saved_model_conversion_v2_test.py
  tfjs-converter/python/tensorflowjs/op_list/arithmetic.json
  tfjs-converter/python/tensorflowjs/op_list/convolution.json
  tfjs-converter/src/operations/op_list/convolution.ts
Labels: cla: yes

#2445 Add cloud func to sync RN test app to browserStack
  tfjs-core/scripts/cloud_funcs/README.md
  tfjs-core/scripts/cloud_funcs/sync_reactnative/.gcloudignore
  tfjs-core/scripts/cloud_funcs/sync_reactnative/index.js
  tfjs-core/scripts/cloud_funcs/sync_reactnative/package.json
Labels: cla: yes
