Repository tensorflow/tfjs, pull requests merged in 2019-10, with the labels that each got.

#2126 Remove trailing slashes when tagging a version.
  scripts/tag-version.js
Labels: cla: yes

#2034 Create a new tf.env() getter that returns the global ENV
  tfjs-core/benchmarks/index.html
  tfjs-core/src/backends/cpu/backend_cpu.ts
  tfjs-core/src/backends/webgl/backend_webgl.ts
  tfjs-core/src/backends/webgl/backend_webgl_test.ts
  tfjs-core/src/backends/webgl/canvas_util_test.ts
  tfjs-core/src/backends/webgl/flags_webgl.ts
  tfjs-core/src/backends/webgl/flags_webgl_test.ts
  tfjs-core/src/backends/webgl/glsl_version.ts
  tfjs-core/src/backends/webgl/gpgpu_context.ts
  tfjs-core/src/backends/webgl/gpgpu_context_test.ts
  tfjs-core/src/backends/webgl/gpgpu_math.ts
  tfjs-core/src/backends/webgl/reshape_packed_test.ts
  tfjs-core/src/backends/webgl/tex_util.ts
  tfjs-core/src/backends/webgl/texture_manager.ts
  tfjs-core/src/backends/webgl/webgl_batchnorm_test.ts
  tfjs-core/src/backends/webgl/webgl_ops_test.ts
  tfjs-core/src/backends/webgl/webgl_util.ts
  tfjs-core/src/backends/webgl/webgl_util_test.ts
  tfjs-core/src/debug_mode_test.ts
  tfjs-core/src/environment.ts
  tfjs-core/src/flags.ts
  tfjs-core/src/flags_test.ts
  tfjs-core/src/globals.ts
  tfjs-core/src/globals_test.ts
  tfjs-core/src/index.ts
  tfjs-core/src/io/browser_files.ts
  tfjs-core/src/io/http.ts
  tfjs-core/src/io/http_test.ts
  tfjs-core/src/io/indexed_db.ts
  tfjs-core/src/io/local_storage.ts
  tfjs-core/src/io/weights_loader.ts
  tfjs-core/src/io/weights_loader_test.ts
  tfjs-core/src/jasmine_util.ts
  tfjs-core/src/log.ts
  tfjs-core/src/ops/slice_test.ts
  tfjs-core/src/ops/tensor_ops.ts
  tfjs-core/src/platforms/platform_browser.ts
  tfjs-core/src/platforms/platform_node.ts
  tfjs-core/src/platforms/platform_node_test.ts
  tfjs-core/src/tensor_test.ts
  tfjs-core/src/tensor_util_env.ts
  tfjs-core/src/tensor_util_test.ts
  tfjs-core/src/util.ts
  tfjs-core/src/util_test.ts
  tfjs-core/src/webgl.ts
Labels: cla: yes

#2114 [layers] Add LayerNormalization
  tfjs-layers/cloudbuild.yml
  tfjs-layers/src/exports_layers.ts
  tfjs-layers/src/layers/normalization.ts
  tfjs-layers/src/layers/normalization_test.ts
Labels: cla: yes

#2133 Fix jsc build errors.
  tfjs-core/src/ops/boolean_mask.ts
  tfjs-core/src/ops/fused_ops.ts
  tfjs-core/src/ops/image_ops.ts
Labels: cla: yes

#2135 Remove dependency of transform_graph
  tfjs-converter/python/tensorflowjs/converters/fuse_prelu.py
  tfjs-converter/python/tensorflowjs/converters/fuse_prelu_test.py
  tfjs-converter/python/tensorflowjs/converters/tf_saved_model_conversion_v2.py
  tfjs-converter/python/tensorflowjs/converters/tf_saved_model_conversion_v2_test.py
Labels: cla: yes

#2109 fix: typo in docs
  tfjs-react-native/README.md
Labels: cla: yes

#2137 Simplify saved model tests
  tfjs-converter/python/tensorflowjs/converters/tf_saved_model_conversion_v2_test.py
Labels: cla: yes

#2122 Update tfjs to 1.2.10.
  tfjs/package.json
  tfjs/src/version.ts
  tfjs/yarn.lock
Labels: cla: yes

#2119 [node] Add fusedDepthwiseConv, add relu6, change interface to fusedConv2D and fusedBatchMatMul
  tfjs-node-gpu/package.json
  tfjs-node-gpu/yarn.lock
  tfjs-node/package.json
  tfjs-node/src/nodejs_kernel_backend.ts
  tfjs-node/src/version.ts
  tfjs-node/yarn.lock
Labels: cla: yes

#2139 fix the directory error in wizard bin
  tfjs-converter/python/setup.py
  tfjs-converter/python/tensorflowjs/converters/tf_saved_model_conversion_v2_test.py
Labels: cla: yes

#2142 verify weights existing, instead of the weights length
  tfjs-converter/python/tensorflowjs/converters/tf_saved_model_conversion_v2_test.py
Labels: cla: yes

#2143 Fix control flow test error
  tfjs-converter/python/tensorflowjs/converters/tf_saved_model_conversion_v2_test.py
Labels: cla: yes

#2144 update the TF deps to tf_nightly
  tfjs/integration_tests/python/requirements.txt
Labels: cla: yes

#2147 [tfjs-backend-wasm] Implement the batchMatMul kernel.
  tfjs-backend-wasm/src/backend_wasm.ts
  tfjs-backend-wasm/src/cc/kernels.cc
  tfjs-backend-wasm/src/cc/kernels.h
  tfjs-backend-wasm/src/cc/lib.cc
  tfjs-backend-wasm/src/setup_test.ts
  tfjs-backend-wasm/wasm-out/tfjs-backend-wasm.d.ts
Labels: cla: yes

#2125 Fix JSCompiler error (add @suppress on module objects)
  tfjs-core/src/index.ts
Labels: cla: yes

#2152 Don't disconnect audioContext when microphone is already closed
  tfjs-data/src/iterators/microphone_iterator.ts
  tfjs-data/src/iterators/microphone_iterator_test.ts
Labels: cla: yes

#2151 Only run prep-gpu.sh in cloudbuild and build-npm
  tfjs-node-gpu/cloudbuild.yml
  tfjs-node-gpu/package.json
  tfjs-node/scripts/ensure-cpu-gpu-packages-align.js
Labels: cla: yes

#2158 Update CI to use Pixel 3 XL
  tfjs-core/karma.conf.js
Labels: cla: yes

#2159 [WASM] Add XNNPACK as external dependency
  .vscode/settings.json
  scripts/diff.js
  tfjs-backend-wasm/WORKSPACE
  tfjs-backend-wasm/src/backend_wasm.ts
  tfjs-backend-wasm/src/cc/BUILD
  tfjs-backend-wasm/src/cc/lib.cc
  tfjs-backend-wasm/wasm-out/tfjs-backend-wasm.d.ts
Labels: cla: yes

#2163 Update tfjs-core to 1.2.11.
  tfjs-core/package.json
  tfjs-core/src/version.ts
Labels: INTERNAL, cla: yes

#2165 Update tfjs-layers, tfjs-converter, tfjs-data to 1.2.11, 1.2.11, 1.2.11.
  tfjs-converter/package.json
  tfjs-converter/python/tensorflowjs/version.py
  tfjs-converter/src/version.ts
  tfjs-converter/yarn.lock
  tfjs-data/package.json
  tfjs-data/src/version.ts
  tfjs-data/yarn.lock
  tfjs-layers/package.json
  tfjs-layers/src/version.ts
  tfjs-layers/yarn.lock
Labels: INTERNAL, cla: yes

#2162 Update release script with tfjs-node-gpu
  scripts/release.ts
  tfjs-node-gpu/package.json
Labels: cla: yes

#2166 Update tfjs to 1.2.11.
  tfjs/package.json
  tfjs/src/version.ts
  tfjs/yarn.lock
Labels: INTERNAL, cla: yes

#2167 Update tfjs-node, tfjs-node-gpu to 1.2.11, 1.2.11.
  tfjs-node-gpu/package.json
  tfjs-node-gpu/yarn.lock
  tfjs-node/package.json
  tfjs-node/src/version.ts
  tfjs-node/yarn.lock
Labels: INTERNAL, cla: yes

#2164 Create README.md
  tfjs-node-gpu/README.md
Labels: cla: yes

#2140 Add documentation to `tf.memory()` for `numBytesInGPU`
  tfjs-core/src/globals.ts
Labels: cla: yes

#2098 Annotated code snippets for Cloud docs
  tfjs-automl/code_snippets/img_classification.html
  tfjs-automl/code_snippets/object_detection.html
Labels: cla: yes

#2168 [tfjs-node] Add new line when saving package.json through code
  tfjs-node/package.json
  tfjs-node/scripts/install.js
Labels: cla: yes

#2145 [tfjs] integrate_tests: Update npm and Python dependencies
  tfjs/integration_tests/.gitignore
  tfjs/integration_tests/benchmark_layers.sh
  tfjs/integration_tests/package.json
  tfjs/integration_tests/python/requirements.txt
  tfjs/integration_tests/python/requirements_gpu.txt
  tfjs/integration_tests/yarn.lock
Labels: cla: yes

#2173 Modularize the WASM kernels into separate build targets.
  .vscode/settings.json
  tfjs-backend-wasm/src/backend_wasm.ts
  tfjs-backend-wasm/src/cc/BUILD
  tfjs-backend-wasm/src/cc/add.cc
  tfjs-backend-wasm/src/cc/backend.cc
  tfjs-backend-wasm/src/cc/backend.h
  tfjs-backend-wasm/src/cc/batch_matmul.cc
Labels: cla: yes

#2174 [layers] Fix bug: LayerNormalization registered as BatchNormalization
  tfjs-layers/src/layers/normalization.ts
  tfjs-layers/src/layers/normalization_test.ts
Labels: cla: yes

#2115 webgpu: Optimize concat/resizeBilinear/transpose
  tfjs-backend-webgpu/src/benchmark_ops_test.ts
  tfjs-backend-webgpu/src/kernels/concat_webgpu.ts
  tfjs-backend-webgpu/src/kernels/resize_bilinear_webgpu.ts
  tfjs-backend-webgpu/src/kernels/transpose_webgpu.ts
Labels: cla: yes

#2169 [layers] Re-enable tfjs2keras integration test; Switch tf.Sequential serialization to TF 2.x format
  tfjs-layers/cloudbuild.yml
  tfjs-layers/integration_tests/tfjs2keras/package.json
  tfjs-layers/integration_tests/tfjs2keras/requirements-dev.txt
  tfjs-layers/integration_tests/tfjs2keras/requirements-stable.txt
  tfjs-layers/integration_tests/tfjs2keras/yarn.lock
  tfjs-layers/src/models.ts
  tfjs-layers/src/models_test.ts
Labels: cla: yes

#2176 [webgpu] Add CPU forwarding flag, upgrade tfjs-core dep.
  tfjs-backend-webgpu/package.json
  tfjs-backend-webgpu/src/backend_webgpu.ts
  tfjs-backend-webgpu/src/backend_webgpu_test.ts
  tfjs-backend-webgpu/src/buffer_manager.ts
  tfjs-backend-webgpu/src/flags_webgpu.ts
  tfjs-backend-webgpu/src/kernels/unary_op_webgpu.ts
  tfjs-backend-webgpu/src/setup_test.ts
  tfjs-backend-webgpu/yarn.lock
Labels: cla: yes

#2136 Add compiled proto_pb.js into tfjs-node and test it
  tfjs-node-gpu/package.json
  tfjs-node-gpu/test_images/gif_test.gif
  tfjs-node-gpu/test_images/image_bmp_4_channel_test.bmp
  tfjs-node-gpu/test_images/image_bmp_test.bmp
  tfjs-node-gpu/test_images/image_jpeg_test.jpeg
  tfjs-node-gpu/test_images/image_png_4_channel_test.png
  tfjs-node-gpu/test_images/image_png_test.png
  tfjs-node-gpu/test_objects/images/gif_test.gif
  tfjs-node-gpu/test_objects/images/image_bmp_4_channel_test.bmp
  tfjs-node-gpu/test_objects/images/image_bmp_test.bmp
  tfjs-node-gpu/test_objects/images/image_jpeg_test.jpeg
  tfjs-node-gpu/test_objects/images/image_png_4_channel_test.png
  tfjs-node-gpu/test_objects/images/image_png_test.png
  tfjs-node-gpu/test_objects/times_three_float/saved_model.pb
  tfjs-node-gpu/test_objects/times_three_float/variables/variables.data-00000-of-00001
  tfjs-node-gpu/test_objects/times_three_float/variables/variables.index
  tfjs-node-gpu/yarn.lock
  tfjs-node/.npmignore
  tfjs-node/package.json
  tfjs-node/src/image_test.ts
  tfjs-node/src/nodejs_kernel_backend_test.ts
  tfjs-node/src/proto/api.proto
  tfjs-node/src/proto/api_pb.js
  tfjs-node/src/run_tests.ts
  tfjs-node/src/saved_model.ts
  tfjs-node/src/saved_model_test.ts
  tfjs-node/test_objects/images/gif_test.gif
  tfjs-node/test_objects/images/image_bmp_4_channel_test.bmp
  tfjs-node/test_objects/images/image_bmp_test.bmp
  tfjs-node/test_objects/images/image_jpeg_test.jpeg
  tfjs-node/test_objects/images/image_png_4_channel_test.png
  tfjs-node/test_objects/images/image_png_test.png
  tfjs-node/test_objects/times_three_float/saved_model.pb
  tfjs-node/test_objects/times_three_float/variables/variables.data-00000-of-00001
  tfjs-node/test_objects/times_three_float/variables/variables.index
  tfjs-node/yarn.lock
Labels: cla: yes

#2181 [tfjs-backend-wasm] Move the free() call into JavaScript.
  tfjs-backend-wasm/src/backend_wasm.ts
  tfjs-backend-wasm/src/cc/BUILD
  tfjs-backend-wasm/src/cc/backend.cc
Labels: cla: yes

#2178 [tfjs-backend-wasm] Implement prelu by calling XNNPack. Add cc tests
  .vscode/settings.json
  tfjs-backend-wasm/.bazelrc
  tfjs-backend-wasm/WORKSPACE
  tfjs-backend-wasm/package.json
  tfjs-backend-wasm/scripts/build-wasm.sh
  tfjs-backend-wasm/scripts/test-ci.sh
  tfjs-backend-wasm/src/backend_wasm.ts
  tfjs-backend-wasm/src/cc/BUILD
  tfjs-backend-wasm/src/cc/add.cc
  tfjs-backend-wasm/src/cc/backend.cc
  tfjs-backend-wasm/src/cc/backend.h
  tfjs-backend-wasm/src/cc/backend_test.cc
  tfjs-backend-wasm/src/cc/batch_matmul.cc
  tfjs-backend-wasm/src/cc/build_defs.bzl
  tfjs-backend-wasm/src/cc/prelu.cc
  tfjs-backend-wasm/src/cc/prelu.h
  tfjs-backend-wasm/src/cc/prelu_test.cc
  tfjs-backend-wasm/src/setup_test.ts
  tfjs-backend-wasm/wasm-out/tfjs-backend-wasm.d.ts
Labels: cla: yes

#2172 [WASM] Add kernel registry
  .vscode/settings.json
  tfjs-core/src/backends/backend.ts
  tfjs-core/src/backends/backend_util.ts
  tfjs-core/src/backends/cpu/all_kernels.ts
  tfjs-core/src/backends/cpu/backend_cpu.ts
  tfjs-core/src/backends/cpu/backend_cpu_test.ts
  tfjs-core/src/backends/cpu/cpu_types.ts
  tfjs-core/src/backends/cpu/cpu_util.ts
  tfjs-core/src/backends/cpu/square.ts
  tfjs-core/src/backends/webgl/backend_webgl.ts
  tfjs-core/src/backends/webgl/backend_webgl_test.ts
  tfjs-core/src/engine.ts
  tfjs-core/src/index.ts
  tfjs-core/src/kernel_registry.ts
  tfjs-core/src/kernel_registry_test.ts
  tfjs-core/src/ops/array_ops.ts
  tfjs-core/src/ops/ops.ts
  tfjs-core/src/ops/square.ts
  tfjs-core/src/ops/tensor_ops.ts
  tfjs-core/src/ops/unary_ops.ts
  tfjs-core/src/tape.ts
  tfjs-core/src/tensor.ts
  tfjs-core/src/tensor_test.ts
  tfjs-core/src/tensor_util_env.ts
  tfjs-core/src/test_async_backends.ts
  tfjs-core/src/tests.ts
Labels: cla: yes

#2192 Bump tfjs-automl version to 0.1.0
  tfjs-automl/README.md
  tfjs-automl/demo/img_classification/index.js
  tfjs-automl/demo/img_classification/package.json
  tfjs-automl/demo/img_classification/yarn.lock
  tfjs-automl/demo/object_detection/index.js
  tfjs-automl/demo/object_detection/package.json
  tfjs-automl/demo/object_detection/yarn.lock
  tfjs-automl/package.json
  tfjs-automl/src/object_detection.ts
  tfjs-automl/src/version.ts
Labels: cla: yes

#2149 add tool to summarize model by op
  tfjs-converter/tools/model_summary.ts
Labels: cla: yes

#2198 [tfjs-backend-wasm] Enable bundle size cloud build CI.
  tfjs-backend-wasm/cloudbuild.yml
Labels: cla: yes

#2201 support int64 for dType params
  tfjs-converter/src/operations/operation_mapper.ts
  tfjs-converter/src/operations/operation_mapper_test.ts
Labels: cla: yes

#2200 Add MetaGraphInfo in tfjs-core/model_types.ts
  tfjs-core/src/index.ts
  tfjs-core/src/model_types.ts
Labels: cla: yes

#2179 Remove 'tensorflowjs' as listed converter input/output format
  tfjs-converter/python/tensorflowjs/converters/converter.py
Labels: cla: yes

#2206 Add slice5d and slice6d methods.
  tfjs-layers/src/backend/tfjs_backend.ts
  tfjs-layers/src/backend/tfjs_backend_test.ts
Labels: FEATURE, cla: yes

#2210 [WASM] Fix bundle size by adding explicitly srcs to the cc_binary
  tfjs-backend-wasm/src/cc/BUILD
  tfjs-backend-wasm/src/cc/backend_test.cc
  tfjs-backend-wasm/src/cc/kernels/add.cc
  tfjs-backend-wasm/src/cc/kernels/batch_matmul.cc
  tfjs-backend-wasm/src/cc/kernels/prelu.cc
  tfjs-backend-wasm/src/cc/kernels/prelu.h
  tfjs-backend-wasm/src/cc/kernels/prelu_test.cc
Labels: cla: yes

#2207 [Core] Simplify the backend interface and clean up the tensor/variable c-tors
  tfjs-core/src/backends/backend.ts
  tfjs-core/src/backends/backend_util.ts
  tfjs-core/src/backends/cpu/backend_cpu.ts
  tfjs-core/src/backends/cpu/backend_cpu_test.ts
  tfjs-core/src/backends/webgl/backend_webgl.ts
  tfjs-core/src/backends/webgl/backend_webgl_test.ts
  tfjs-core/src/engine.ts
  tfjs-core/src/index.ts
  tfjs-core/src/ops/array_ops.ts
  tfjs-core/src/ops/tensor_ops.ts
  tfjs-core/src/tape.ts
  tfjs-core/src/tape_test.ts
  tfjs-core/src/tensor.ts
  tfjs-core/src/tensor_test.ts
  tfjs-core/src/tensor_util_env.ts
  tfjs-core/src/variable_test.ts
Labels: cla: yes

#2216 Rename Engine.run to Engine.runKernel
  tfjs-core/src/engine.ts
  tfjs-core/src/kernel_registry_test.ts
  tfjs-core/src/ops/array_ops.ts
  tfjs-core/src/ops/batchnorm.ts
  tfjs-core/src/ops/binary_ops.ts
  tfjs-core/src/ops/compare.ts
  tfjs-core/src/ops/complex_ops.ts
  tfjs-core/src/ops/concat_split.ts
  tfjs-core/src/ops/conv.ts
  tfjs-core/src/ops/diag.ts
  tfjs-core/src/ops/fused_ops.ts
  tfjs-core/src/ops/gather_nd.ts
  tfjs-core/src/ops/image_ops.ts
  tfjs-core/src/ops/logical_ops.ts
  tfjs-core/src/ops/lrn.ts
  tfjs-core/src/ops/matmul.ts
  tfjs-core/src/ops/pool.ts
  tfjs-core/src/ops/reduction_ops.ts
  tfjs-core/src/ops/relu_ops.ts
  tfjs-core/src/ops/reverse.ts
  tfjs-core/src/ops/scatter_nd.ts
  tfjs-core/src/ops/segment_ops.ts
  tfjs-core/src/ops/slice.ts
  tfjs-core/src/ops/sparse_to_dense.ts
  tfjs-core/src/ops/spectral_ops.ts
  tfjs-core/src/ops/square.ts
  tfjs-core/src/ops/strided_slice.ts
  tfjs-core/src/ops/tensor_ops.ts
  tfjs-core/src/ops/topk.ts
  tfjs-core/src/ops/transpose.ts
  tfjs-core/src/ops/unary_ops.ts
Labels: cla: yes

#2214 cast the condition param of Where op to bool type
  tfjs-converter/src/operations/executors/dynamic_executor.ts
  tfjs-converter/src/operations/executors/dynamic_executor_test.ts
Labels: cla: yes

#2218 [tfjs-core] Rename TensorInfo interface to ModelTensorInfo
  tfjs-core/src/index.ts
  tfjs-core/src/model_types.ts
  tfjs-core/src/tensor_types.ts
Labels: cla: yes

#2190 [node]Add a new API in tfjs-node to inspect SavedModel
  tfjs-node-gpu/package.json
  tfjs-node/src/saved_model.ts
  tfjs-node/src/saved_model_test.ts
Labels: cla: yes

#2209 support frozen model conversion
  tfjs-converter/README.md
  tfjs-converter/python/tensorflowjs/converters/common.py
  tfjs-converter/python/tensorflowjs/converters/converter.py
  tfjs-converter/python/tensorflowjs/converters/tf_saved_model_conversion_v2.py
  tfjs-converter/python/tensorflowjs/converters/tf_saved_model_conversion_v2_test.py
  tfjs-converter/python/test_pip_package.py
Labels: cla: yes

#2222 [tfjs-layers] Update stable versions of tensorflow to 1.15.0
  tfjs-layers/integration_tests/tfjs2keras/requirements-stable.txt
Labels: cla: yes

#2231 [core] Improve docs for decoding process.
  tfjs-core/src/backends/webgl/backend_webgl.ts
Labels: cla: yes

#2213 [WASM] Selectively link XNNPACK operators
  tfjs-backend-wasm/WORKSPACE
  tfjs-backend-wasm/src/cc/BUILD
Labels: cla: yes

#2221 update the tf version to 1.15 for converter
  tfjs-converter/python/.pylintrc
  tfjs-converter/python/requirements.txt
Labels: cla: yes

#2223 [webgpu] Make condition for not checking out of bounds stricter.
  tfjs-backend-webgpu/src/backend_webgpu.ts
  tfjs-backend-webgpu/src/kernels/matmul_packed_webgpu.ts
  tfjs-backend-webgpu/src/kernels/matmul_webgpu.ts
  tfjs-backend-webgpu/src/matmul_test.ts
  tfjs-backend-webgpu/src/webgpu_util.ts
Labels: cla: yes

#2229 [tfjs-backend-wasm] Add cpplint.
  tfjs-backend-wasm/package.json
  tfjs-backend-wasm/scripts/cpplint.js
  tfjs-backend-wasm/src/cc/backend.cc
  tfjs-backend-wasm/src/cc/backend.h
  tfjs-backend-wasm/src/cc/kernels/prelu.cc
  tfjs-backend-wasm/src/cc/kernels/prelu.h
  tfjs-backend-wasm/src/cc/util.h
  tfjs-backend-wasm/tools/cpplint.py
Labels: cla: yes

#2232 [tfjs-vis] Allow custom mark colors in charts
  tfjs-vis/demos/api/index.html
  tfjs-vis/src/render/barchart.ts
  tfjs-vis/src/render/histogram.ts
  tfjs-vis/src/render/linechart.ts
  tfjs-vis/src/render/scatterplot.ts
  tfjs-vis/src/types.ts
Labels: cla: yes

#2244 [Core] Add setup and dispose callback when registering modular kernels
  tfjs-core/src/backends/cpu/backend_cpu.ts
  tfjs-core/src/backends/cpu/cpu_types.ts
  tfjs-core/src/backends/cpu/square.ts
  tfjs-core/src/backends/webgl/backend_webgl_test.ts
  tfjs-core/src/backends/webgl/square.ts
  tfjs-core/src/engine.ts
  tfjs-core/src/engine_test.ts
  tfjs-core/src/kernel_registry.ts
  tfjs-core/src/kernel_registry_test.ts
  tfjs-core/src/ops/binary_ops.ts
  tfjs-core/src/ops/matmul.ts
  tfjs-core/src/ops/matmul_test.ts
  tfjs-core/src/ops/relu_ops.ts
  tfjs-core/src/test_async_backends.ts
Labels: cla: yes

#2249 [core] Remove fused from docs.
  tfjs-core/src/ops/fused_ops.ts
Labels: cla: yes

#2247 Copy tfjs/README.md to README.md during publishing.
  .gitignore
  tfjs/scripts/build-npm.sh
Labels: cla: yes

#2248 [Core] Remove `save` from kernels
  tfjs-core/src/backends/cpu/square.ts
  tfjs-core/src/backends/webgl/square.ts
  tfjs-core/src/engine.ts
  tfjs-core/src/kernel_registry.ts
  tfjs-core/src/ops/square.ts
Labels: cla: yes

#2250 Update the gl.canvas type to include OffscreenCanvas to prep for ts3.6
  tfjs-core/src/backends/webgl/backend_webgl.ts
Labels: cla: yes

#2242 webgpu: Add conv2dByMatMul
  tfjs-backend-webgpu/src/backend_webgpu.ts
  tfjs-backend-webgpu/src/kernels/matmul_packed_webgpu.ts
  tfjs-backend-webgpu/src/kernels/matmul_webgpu.ts
  tfjs-backend-webgpu/src/kernels/maxpool_webgpu.ts
  tfjs-backend-webgpu/src/kernels/resize_bilinear_webgpu.ts
Labels: cla: yes

#2251 Convert all usages of ENV in all packages to env().
  tfjs-backend-nodegl/src/index.ts
  tfjs-backend-webgpu/src/backend_webgpu_test.ts
  tfjs-backend-webgpu/src/flags_webgpu.ts
  tfjs-backend-webgpu/src/matmul_test.ts
  tfjs-converter/src/operations/operation_mapper.ts
  tfjs-data/src/dataset_test.ts
  tfjs-data/src/datasets/csv_dataset_test.ts
  tfjs-data/src/datasets/text_line_dataset_test.ts
  tfjs-data/src/iterators/byte_chunk_iterator.ts
  tfjs-data/src/iterators/byte_chunk_iterator_test.ts
  tfjs-data/src/iterators/file_chunk_iterator.ts
  tfjs-data/src/iterators/file_chunk_iterator_test.ts
  tfjs-data/src/iterators/microphone_iterator.ts
  tfjs-data/src/iterators/string_iterator_test.ts
  tfjs-data/src/iterators/webcam_iterator.ts
  tfjs-data/src/sources/file_data_source.ts
  tfjs-data/src/util/source_util_test.ts
  tfjs-layers/src/models_test.ts
  tfjs-node/src/io/node_http_test.ts
  tfjs-react-native/integration_rn59/components/diagnostic.tsx
  tfjs-react-native/integration_rn59/components/tfjs_unit_test_runner.tsx
  tfjs-react-native/integration_rn59/package.json
  tfjs-react-native/integration_rn59/yarn.lock
  tfjs-react-native/package.json
  tfjs-react-native/src/bundle_resource_io_test.ts
  tfjs-react-native/src/platform_react_native.ts
Labels: cla: yes

#2258 [core] In gradient mode, if fused activation is not backproppable, call unfused ops instead.
  tfjs-core/src/ops/fused_ops.ts
  tfjs-core/src/ops/fused_test.ts
  tfjs-core/src/ops/fused_util.ts
Labels: cla: yes

#2261 Minor edits to README.md
  README.md
Labels: cla: yes

#2257 [tfjs-vis] remove glamor-tachyons
  tfjs-vis/demos/api/index.html
  tfjs-vis/package.json
  tfjs-vis/src/components/surface.tsx
  tfjs-vis/src/components/tabs.tsx
  tfjs-vis/src/components/visor.tsx
  tfjs-vis/src/render/table.ts
  tfjs-vis/src/util/dom.ts
  tfjs-vis/yarn.lock
Labels: cla: yes

#2270 [Core] Fix a bug with fused conv2d
  tfjs-core/karma.conf.js
  tfjs-core/src/jasmine_util.ts
  tfjs-core/src/ops/fused_ops.ts
Labels: cla: yes

#2273 Update tfjs-automl to v1
  tfjs-automl/README.md
  tfjs-automl/demo/img_classification/package.json
  tfjs-automl/demo/img_classification/yarn.lock
  tfjs-automl/demo/object_detection/package.json
  tfjs-automl/demo/object_detection/yarn.lock
  tfjs-automl/package.json
  tfjs-automl/src/version.ts
Labels: cla: yes

#2271 [Core] Update to version 1.3.0
  tfjs-core/package.json
  tfjs-core/src/version.ts
Labels: cla: yes

#2274 Update tfjs-layers, tfjs-converter, tfjs-data to 1.3.0, 1.3.0, 1.3.0.
  tfjs-converter/karma.conf.js
  tfjs-converter/package.json
  tfjs-converter/python/tensorflowjs/version.py
  tfjs-converter/src/version.ts
  tfjs-converter/yarn.lock
  tfjs-data/karma.conf.js
  tfjs-data/package.json
  tfjs-data/src/version.ts
  tfjs-data/yarn.lock
  tfjs-layers/karma.conf.js
  tfjs-layers/package.json
  tfjs-layers/src/version.ts
  tfjs-layers/yarn.lock
Labels: INTERNAL, cla: yes

#2275 Update tfjs to 1.3.0.
  tfjs/karma.conf.js
  tfjs/package.json
  tfjs/src/version.ts
  tfjs/yarn.lock
Labels: INTERNAL, cla: yes

#2141 Add RN integratation tests (with core) to CI
  tfjs-core/cloudbuild.yml
  tfjs-core/src/io/io_utils_test.ts
  tfjs-core/src/jasmine_util.ts
  tfjs-react-native/DEVELOPMENT.md
  tfjs-react-native/integration_rn59/App.tsx
  tfjs-react-native/integration_rn59/android/app/src/main/java/com/integration_rn59/generated/BasePackageList.java
  tfjs-react-native/integration_rn59/components/tfjs_unit_test_runner.tsx
  tfjs-react-native/integration_rn59/ios/Podfile
  tfjs-react-native/integration_rn59/ios/Podfile.lock
  tfjs-react-native/integration_rn59/ios/integration_rn59.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
  tfjs-react-native/integration_rn59/package.json
  tfjs-react-native/integration_rn59/scripts/prep_tests.ts
  tfjs-react-native/integration_rn59/scripts/test-ci.sh
  tfjs-react-native/integration_rn59/test/integration_test.ts
  tfjs-react-native/integration_rn59/tsconfig.json
  tfjs-react-native/integration_rn59/wdio.conf.js
  tfjs-react-native/integration_rn59/yarn.lock
  tfjs-react-native/package.json
  tfjs-react-native/src/platform_react_native.ts
  tfjs-react-native/yarn.lock
Labels: cla: yes

#2256 webgpu: Enable rectangle workgroup size for matMul
  tfjs-backend-webgpu/src/kernels/conv2d_mm_webgpu.ts
  tfjs-backend-webgpu/src/kernels/matmul_packed_webgpu.ts
  tfjs-backend-webgpu/src/webgpu_util.ts
Labels: cla: yes

#2280 [Node] Depend on newest core (1.3.0)
  tfjs-node-gpu/package.json
  tfjs-node-gpu/yarn.lock
  tfjs-node/package.json
  tfjs-node/src/io/file_system_test.ts
  tfjs-node/src/nodejs_kernel_backend.ts
  tfjs-node/src/run_tests.ts
  tfjs-node/yarn.lock
Labels: cla: yes

#2281 Update tfjs-node, tfjs-node-gpu to 1.3.0, 1.3.0.
  tfjs-node-gpu/package.json
  tfjs-node-gpu/yarn.lock
  tfjs-node/package.json
  tfjs-node/src/version.ts
Labels: INTERNAL, cla: yes

#2282 Update layers integration tests to 1.3.0
  tfjs-layers/integration_tests/tfjs2keras/package.json
  tfjs-layers/integration_tests/tfjs2keras/yarn.lock
Labels: cla: yes

#2264 [wasm] Add batchnorm kernel.
  tfjs-backend-wasm/src/cc/BUILD
  tfjs-backend-wasm/src/cc/kernels/FusedBatchNorm.cc
  tfjs-backend-wasm/src/kernels/FusedBatchNorm.ts
  tfjs-backend-wasm/src/kernels/all_kernels.ts
  tfjs-backend-wasm/src/setup_test.ts
  tfjs-core/src/ops/batchnorm.ts
Labels: cla: yes

#2217 [tfjs-node] Add SavedModel signatureDef loading and deleting API
  tfjs-node-gpu/package.json
  tfjs-node-gpu/test_objects/module_with_multiple_signatures/saved_model.pb
  tfjs-node-gpu/test_objects/module_with_multiple_signatures/variables/variables.data-00000-of-00001
  tfjs-node-gpu/test_objects/module_with_multiple_signatures/variables/variables.index
  tfjs-node/binding/tfjs_backend.cc
  tfjs-node/binding/tfjs_backend.h
  tfjs-node/binding/tfjs_binding.cc
  tfjs-node/binding/utils.h
  tfjs-node/integration/typescript/src/test.ts
  tfjs-node/package.json
  tfjs-node/scripts/build-npm.sh
  tfjs-node/src/node.ts
  tfjs-node/src/nodejs_kernel_backend.ts
  tfjs-node/src/saved_model.ts
  tfjs-node/src/saved_model_test.ts
  tfjs-node/src/tfjs_binding.ts
  tfjs-node/test_objects/module_with_multiple_signatures/saved_model.pb
  tfjs-node/test_objects/module_with_multiple_signatures/variables/variables.data-00000-of-00001
  tfjs-node/test_objects/module_with_multiple_signatures/variables/variables.index
Labels: cla: yes

#2234 move the prelu fusing logic after grappler optimization
  tfjs-converter/python/tensorflowjs/converters/fuse_prelu.py
  tfjs-converter/python/tensorflowjs/converters/fuse_prelu_test.py
  tfjs-converter/python/tensorflowjs/converters/tf_saved_model_conversion_v2.py
  tfjs-converter/python/tensorflowjs/converters/tf_saved_model_conversion_v2_test.py
Labels: cla: yes

#2290 [Core] Fix bug with pointwise conv2d with packing
  tfjs-core/src/backends/webgl/backend_webgl.ts
  tfjs-core/src/backends/webgl/webgl_ops_test.ts
Labels: cla: yes

#2291 [Core] Fix bug with WEBGL_PACK=false and uploading packed tensor
  tfjs-core/src/backends/webgl/backend_webgl.ts
  tfjs-core/src/backends/webgl/webgl_ops_test.ts
Labels: cla: yes

#2292 Update tfjs-core to 1.3.1.
  tfjs-core/package.json
  tfjs-core/src/version.ts
Labels: INTERNAL, cla: yes

#2284 replace the weights node name with scaled weights node
  tfjs-converter/python/tensorflowjs/converters/fold_batch_norms.py
  tfjs-converter/python/tensorflowjs/converters/fold_batch_norms_test.py
  tfjs-converter/python/tensorflowjs/converters/keras_h5_conversion.py
Labels: cla: yes

#2293 Update tfjs-layers, tfjs-converter, tfjs-data to 1.3.1, 1.3.1, 1.3.1.
  tfjs-converter/package.json
  tfjs-converter/python/tensorflowjs/version.py
  tfjs-converter/src/version.ts
  tfjs-converter/yarn.lock
  tfjs-data/package.json
  tfjs-data/src/version.ts
  tfjs-data/yarn.lock
  tfjs-layers/package.json
  tfjs-layers/src/version.ts
  tfjs-layers/yarn.lock
Labels: INTERNAL, cla: yes

#2295 Update tfjs to 1.3.1.
  tfjs/package.json
  tfjs/src/version.ts
  tfjs/yarn.lock
Labels: INTERNAL, cla: yes

#2296 Update tfjs-node, tfjs-node-gpu to 1.3.1, 1.3.1.
  tfjs-node-gpu/package.json
  tfjs-node-gpu/yarn.lock
  tfjs-node/package.json
  tfjs-node/src/version.ts
  tfjs-node/yarn.lock
Labels: INTERNAL, cla: yes

#2287 clean the unused control flow input nodes from the graph
  tfjs-converter/cloudbuild.yml
  tfjs-converter/python/tensorflowjs/converters/tf_saved_model_conversion_v2.py
Labels: cla: yes

#2294 [Core] Test WEBGL_PACK=false on CI
  tfjs-core/scripts/test-ci.sh
Labels: cla: yes

#2289 [wasm] Add min / max kernels.
  tfjs-backend-wasm/src/cc/BUILD
  tfjs-backend-wasm/src/cc/kernels/Max.cc
  tfjs-backend-wasm/src/cc/kernels/Min.cc
  tfjs-backend-wasm/src/kernels/Max.ts
  tfjs-backend-wasm/src/kernels/Min.ts
  tfjs-backend-wasm/src/kernels/all_kernels.ts
  tfjs-backend-wasm/src/setup_test.ts
  tfjs-core/src/ops/reduction_ops.ts
Labels: cla: yes

#2305 [WASM] Add a hierarchical test spec.
  tfjs-backend-wasm/src/setup_test.ts
  tfjs-core/src/jasmine_util.ts
Labels: cla: yes
