Repository tensorflow/tfjs, pull requests merged in 2020-04, with the labels that each got.

#2995 [node] Clean up dependency of tfc and tfl in node tests
  scripts/release-util.ts
  tfjs-core/yarn.lock
  tfjs-node/package.json
  tfjs-node/src/canvas_test.ts
  tfjs-node/src/image.ts
  tfjs-node/src/image_test.ts
  tfjs-node/src/io/file_system.ts
  tfjs-node/src/io/file_system_test.ts
  tfjs-node/src/io/io_utils.ts
  tfjs-node/src/io/node_http.ts
  tfjs-node/src/io/node_http_test.ts
  tfjs-node/src/kernels/Softmax.ts
  tfjs-node/src/kernels/SquaredDifference.ts
  tfjs-node/src/kernels/non_max_suppression_v5.ts
  tfjs-node/src/nodejs_kernel_backend.ts
  tfjs-node/src/nodejs_kernel_backend_test.ts
  tfjs-node/src/saved_model_test.ts
  tfjs-node/src/tfjs_binding.ts
Labels: cla: yes

#2996 [core] Modularize batchnorm.
  tfjs-backend-wasm/src/kernels/FusedBatchNorm.ts
  tfjs-core/src/gradients/FusedBatchNorm_grad.ts
  tfjs-core/src/kernel_names.ts
  tfjs-core/src/ops/batchnorm.ts
  tfjs-core/src/ops/batchnorm2d.ts
  tfjs-core/src/ops/batchnorm3d.ts
  tfjs-core/src/ops/batchnorm4d.ts
  tfjs-core/src/ops/batchnorm_util.ts
  tfjs-core/src/ops/ops.ts
  tfjs-core/src/public/chained_ops/batchnorm.ts
  tfjs-core/src/public/chained_ops/register_all_chained_ops.ts
  tfjs-core/src/public/chained_ops/register_all_chained_ops_test.ts
  tfjs-core/src/register_all_gradients.ts
  tfjs-core/src/tensor.ts
Labels: cla: yes

#3010 support Op MaxPooWthArgmax in CPU and WebGL
  tfjs-backend-wasm/src/setup_test.ts
  tfjs-backend-webgpu/src/setup_test.ts
  tfjs-converter/python/tensorflowjs/op_list/convolution.json
  tfjs-converter/src/operations/executors/convolution_executor.ts
  tfjs-converter/src/operations/executors/convolution_executor_test.ts
  tfjs-converter/src/operations/op_list/convolution.ts
  tfjs-core/src/backends/cpu/backend_cpu.ts
  tfjs-core/src/backends/cpu/kernels/MaxPoolWithArgmax.ts
  tfjs-core/src/backends/cpu/kernels/MaxPoolWithArgmax_impl.ts
  tfjs-core/src/backends/cpu/pool_utils.ts
  tfjs-core/src/backends/cpu/register_all_kernels.ts
  tfjs-core/src/backends/webgl/kernels/MaxPoolWithArgmax.ts
  tfjs-core/src/backends/webgl/kernels/MaxPoolWithArgmax_impl.ts
  tfjs-core/src/backends/webgl/pool_gpu.ts
  tfjs-core/src/backends/webgl/register_all_kernels.ts
  tfjs-core/src/kernel_names.ts
  tfjs-core/src/ops/pool.ts
  tfjs-core/src/ops/pool_test.ts
  tfjs-node/src/run_tests.ts
Labels: cla: yes

#3005 Refactor release script.
  scripts/release-util.ts
  scripts/release-website.ts
  scripts/release.ts
Labels: cla: yes

#3018 fix nightly test
  tfjs-core/src/ops/pool_test.ts
Labels: cla: yes

#3013 [node] Check if native addon module exists and throw error message
  tfjs-node/src/index.ts
Labels: cla: yes

#3002 [core]Modularize addN.
  tfjs-core/src/engine.ts
  tfjs-core/src/gradients/AddN_grad.ts
  tfjs-core/src/kernel_names.ts
  tfjs-core/src/kernel_registry.ts
  tfjs-core/src/kernel_registry_test.ts
  tfjs-core/src/ops/add_n.ts
  tfjs-core/src/ops/add_n_test.ts
  tfjs-core/src/ops/arithmetic_test.ts
  tfjs-core/src/ops/binary_ops.ts
  tfjs-core/src/ops/ops.ts
  tfjs-core/src/register_all_gradients.ts
  tfjs-core/src/tests.ts
Labels: cla: yes

#2970 Remove test-integration.
  cloudbuild.yml
  tfjs-core/package.json
  tfjs-core/scripts/cloud_funcs/README.md
  tfjs-core/scripts/test-integration.js
  tfjs-core/scripts/test-integration.sh
Labels: cla: yes

#3024 Update tfjs-layers, tfjs-converter to 1.7.2, 1.7.2.
  tfjs-converter/package.json
  tfjs-converter/python/tensorflowjs/version.py
  tfjs-converter/src/version.ts
  tfjs-converter/yarn.lock
  tfjs-layers/package.json
  tfjs-layers/src/version.ts
  tfjs-layers/yarn.lock
Labels: INTERNAL, cla: yes

#3026 Update tfjs to 1.7.2.
  tfjs/package.json
  tfjs/src/version.ts
  tfjs/yarn.lock
Labels: INTERNAL, cla: yes

#3027 Add license.
  tfjs-core/src/ops/pad3d.ts
Labels: cla: yes

#3030 Remove duplicate declaration.
  tfjs-core/src/ops/rand_util.ts
Labels: cla: yes

#3029 Update tfjs-node, tfjs-node-gpu to 1.7.2, 1.7.2.
  tfjs-node-gpu/package.json
  tfjs-node-gpu/yarn.lock
  tfjs-node/package.json
  tfjs-node/src/version.ts
  tfjs-node/yarn.lock
Labels: INTERNAL, cla: yes

#3032 Update tfjs-backend-wasm to 1.7.2.
  tfjs-backend-wasm/package.json
  tfjs-backend-wasm/src/version.ts
  tfjs-backend-wasm/yarn.lock
Labels: INTERNAL, cla: yes

#3033 wasm release require additional step to build.
  scripts/publish-npm.ts
  scripts/release.ts
Labels: cla: yes

#3028 Change dev branch naming pattern.
  scripts/release.ts
Labels: cla: yes

#3031 Remove layers symlink in node-gpu.
  tfjs-node-gpu/package.json
Labels: cla: yes

#3035 Upgrade browserstack to 1.5.1
  tfjs-core/package.json
  tfjs-core/yarn.lock
Labels: cla: yes

#3038 Browserstack disconnection issue.
  tfjs-core/karma.conf.js
Labels: cla: yes

#3044 Add this.throwIfDisposed();
  tfjs-core/src/public/chained_ops/add.ts
  tfjs-core/src/public/chained_ops/batchnorm.ts
  tfjs-core/src/public/chained_ops/broadcast_to.ts
  tfjs-core/src/public/chained_ops/div.ts
  tfjs-core/src/public/chained_ops/div_no_nan.ts
  tfjs-core/src/public/chained_ops/one_hot.ts
  tfjs-core/src/public/chained_ops/pad.ts
  tfjs-core/src/public/chained_ops/squared_difference.ts
  tfjs-core/src/public/chained_ops/tile.ts
  tfjs-core/src/public/chained_ops/transpose.ts
Labels: cla: yes

#3047 Clean up. Remove backward func from BroadcastTo.
  tfjs-core/src/gradients/BroadcastTo_grad.ts
  tfjs-core/src/ops/broadcast_to.ts
Labels: cla: yes

#3055 Clean up. Remove backward func from SquaredDifference.
  tfjs-core/src/ops/squared_difference.ts
Labels: cla: yes

#3034 Use union package start/end version for all.
  scripts/release_notes/release_notes.ts
Labels: cla: yes

#3059 [cpu] Remove use of browserstack.
  tfjs-backend-cpu/package.json
  tfjs-backend-cpu/run_tests.ts
  tfjs-backend-cpu/scripts/test-ci.sh
  tfjs-core/src/ops/complex_ops_test.ts
Labels: cla: yes

#3064 [cpu] Fix build and deps.
  tfjs-backend-cpu/cloudbuild.yml
  tfjs-backend-cpu/package.json
  tfjs-core/cloudbuild.yml
  tfjs-core/package.json
Labels: cla: yes

#3063 Remove WebGL test matrix from core
  scripts/package_dependencies.json
  tfjs-backend-cpu/cloudbuild.yml
  tfjs-backend-cpu/karma.conf.js
  tfjs-backend-webgl/cloudbuild.yml
  tfjs-backend-webgl/karma.conf.js
  tfjs-backend-webgl/src/setup_test.ts
  tfjs-core/karma.conf.js
  tfjs-core/package.json
  tfjs-core/scripts/test-ci.sh
  tfjs-core/src/index.ts
  tfjs-core/src/worker_test.ts
Labels: cla: yes

#3065 Add new deps to release script.
  scripts/release-util.ts
Labels: cla: yes

#3073 [core] Fix toPixels memLeak for TensorLike inputs.
  tfjs-core/src/ops/array_ops_test.ts
  tfjs-core/src/ops/browser.ts
Labels: cla: yes

#3076 Add retry to download emsdk due to flaky download.
  tfjs-backend-wasm/scripts/build-ci.sh
Labels: cla: yes

#3075 ensure isMobile() does not fail when navigator is not set
  tfjs-core/src/device_util.ts
  tfjs-core/src/device_util_test.ts
  tfjs-core/src/tests.ts
Labels: cla: yes

#3078 Add retry to install emsdk.
  tfjs-backend-wasm/scripts/build-ci.sh
Labels: cla: yes

#3066 Add new deps to package_dependencies.json.
  scripts/package_dependencies.json
Labels: cla: yes

#3082 Remove cpu backend in tfjs-node testing, use fake instead.
  tfjs-node/src/image_test.ts
  tfjs-node/src/nodejs_kernel_backend_test.ts
  tfjs-node/src/run_tests.ts
Labels: cla: yes

#3079 fix nightly test for isMobile
  tfjs-core/src/device_util_test.ts
Labels: cla: yes

#3077 [webgpu] Add devDependency on WebGL for testing.
  tfjs-backend-webgpu/package.json
  tfjs-backend-webgpu/src/setup_test.ts
Labels: cla: yes

#3081 Refactor CI flow.
  tfjs-backend-cpu/cloudbuild.yml
  tfjs-backend-cpu/package.json
  tfjs-backend-wasm/cloudbuild.yml
  tfjs-backend-wasm/scripts/test-ci.sh
  tfjs-backend-webgl/cloudbuild.yml
  tfjs-backend-webgl/package.json
  tfjs-backend-webgl/scripts/test-ci.sh
  tfjs-converter/cloudbuild.yml
  tfjs-converter/package.json
  tfjs-core/cloudbuild.yml
  tfjs-core/package.json
  tfjs-core/scripts/test-ci.sh
  tfjs-data/cloudbuild.yml
  tfjs-data/package.json
  tfjs-layers/cloudbuild.yml
  tfjs-layers/scripts/test-ci.sh
  tfjs-node-gpu/cloudbuild.yml
  tfjs-node-gpu/package.json
  tfjs-node/cloudbuild.yml
  tfjs-node/package.json
  tfjs-node/scripts/test-ci.sh
  tfjs/cloudbuild.yml
  tfjs/scripts/test-ci.sh
Labels: cla: yes

#3090 Bump dev deps version to remove security vulnerability
  package.json
  tfjs-automl/yarn.lock
  tfjs-backend-cpu/yarn.lock
  tfjs-backend-nodegl/yarn.lock
  tfjs-backend-wasm/yarn.lock
  tfjs-backend-webgl/yarn.lock
  tfjs-backend-webgpu/package.json
  tfjs-backend-webgpu/yarn.lock
  tfjs-converter/package.json
  tfjs-converter/yarn.lock
  tfjs-core/yarn.lock
  tfjs-data/package.json
  tfjs-data/yarn.lock
  tfjs-layers/package.json
  tfjs-layers/yarn.lock
  tfjs-node-gpu/yarn.lock
  tfjs-node/yarn.lock
  tfjs-react-native/yarn.lock
  tfjs-vis/yarn.lock
  tfjs/yarn.lock
  yarn.lock
Labels: cla: yes

#2993 [webgpu] Fix conv2d padding issue
  tfjs-backend-webgpu/src/backend_webgpu.ts
  tfjs-backend-webgpu/src/kernels/conv2d_mm_webgpu.ts
Labels: cla: yes

#3049 [webgpu] fix shaderKey issue to add types info in shaderKey
  tfjs-backend-webgpu/src/backend_webgpu.ts
  tfjs-backend-webgpu/src/kernels/webgpu_program.ts
Labels: cla: yes

#2846 [webgpu] Fix dilation and add stride 2 filter 3x3 same conv2d test case
  tfjs-backend-webgpu/src/backend_webgpu.ts
  tfjs-core/src/ops/conv2d_test.ts
  tfjs-core/src/ops/fused_test.ts
Labels: cla: yes

#3100 use instantiateWasm override and platform fetch
  tfjs-backend-wasm/README.md
  tfjs-backend-wasm/src/backend_wasm.ts
  tfjs-backend-wasm/src/index.ts
  tfjs-backend-wasm/src/index_test.ts
  tfjs-backend-wasm/wasm-out/tfjs-backend-wasm.d.ts
Labels: cla: yes

#3115 Revise release script for 1.7.x hot fix.
  scripts/release.ts
Labels: cla: yes

#3117 Wasm fix
  tfjs-backend-wasm/README.md
  tfjs-backend-wasm/src/backend_wasm.ts
  tfjs-backend-wasm/src/index.ts
  tfjs-backend-wasm/src/index_test.ts
  tfjs-backend-wasm/wasm-out/tfjs-backend-wasm.d.ts
Labels: cla: yes

#3097 [webgpu] Add time selection feature to benchmarks frontend.
  tfjs-backend-webgpu/benchmarks/config.js
  tfjs-backend-webgpu/benchmarks/index.html
  tfjs-backend-webgpu/benchmarks/main.css
  tfjs-backend-webgpu/benchmarks/main.js
  tfjs-backend-webgpu/benchmarks/util.js
  tfjs-backend-webgpu/package.json
Labels: cla: yes

#3108 [wasm] Enable compatibility with emscripten 1.39.11, which in turn enables pthread support.
  tfjs-backend-wasm/src/cc/batch_mat_mul_impl.cc
Labels: cla: yes

#3123 Update tfjs-core to 1.7.3.
  tfjs-core/package.json
  tfjs-core/src/version.ts
Labels: INTERNAL, cla: yes

#3124 Update tfjs-layers, tfjs-converter to 1.7.3, 1.7.3.
  tfjs-converter/package.json
  tfjs-converter/python/tensorflowjs/version.py
  tfjs-converter/src/version.ts
  tfjs-converter/yarn.lock
  tfjs-layers/package.json
  tfjs-layers/src/version.ts
  tfjs-layers/yarn.lock
Labels: INTERNAL, cla: yes

#3126 Switching to tf.io. for file access and loading savedmodels in eager model.
  tfjs-converter/python/tensorflowjs/BUILD
  tfjs-converter/python/tensorflowjs/converters/BUILD
  tfjs-converter/python/tensorflowjs/converters/keras_tfjs_loader_test.py
  tfjs-converter/python/tensorflowjs/converters/tf_saved_model_conversion_v2.py
  tfjs-converter/python/tensorflowjs/read_weights_test.py
  tfjs-converter/python/tensorflowjs/write_weights.py
  tfjs-converter/python/tensorflowjs/write_weights_test.py
Labels: cla: yes

#3110 Updated README.md with TF.js Blog Link
  README.md
Labels: cla: yes

#3127 path for python converter
  tfjs-converter/python/tensorflowjs/BUILD
  tfjs-converter/python/tensorflowjs/converters/BUILD
  tfjs-converter/python/tensorflowjs/converters/keras_tfjs_loader_test.py
  tfjs-converter/python/tensorflowjs/converters/tf_saved_model_conversion_v2.py
  tfjs-converter/python/tensorflowjs/read_weights_test.py
  tfjs-converter/python/tensorflowjs/write_weights.py
  tfjs-converter/python/tensorflowjs/write_weights_test.py
Labels: cla: no

#3125 Update tfjs-data to 1.7.3.
  tfjs-data/package.json
  tfjs-data/src/version.ts
  tfjs-data/yarn.lock
Labels: INTERNAL, cla: yes

#3129 Update tfjs-node, tfjs-node-gpu to 1.7.3, 1.7.3.
  tfjs-node-gpu/package.json
  tfjs-node-gpu/yarn.lock
  tfjs-node/package.json
  tfjs-node/src/version.ts
  tfjs-node/yarn.lock
Labels: INTERNAL, cla: yes

#3130 Update tfjs-backend-wasm to 1.7.3.
  tfjs-backend-wasm/package.json
  tfjs-backend-wasm/src/version.ts
  tfjs-backend-wasm/yarn.lock
Labels: INTERNAL, cla: yes

#3138 cherry pick g3 fix to release branch
  tfjs-core/src/ops/pad3d.ts
  tfjs-core/src/ops/rand_util.ts
Labels: cla: yes

#3139 fix nightly error on isMobile
  tfjs-core/src/device_util.ts
  tfjs-core/src/device_util_test.ts
Labels: cla: yes

#3099 Add packages to vs.code workspace
  tfjs.code-workspace
Labels: cla: yes

#3145 remove unnecessary eager call
  tfjs-converter/python/tensorflowjs/converters/tf_saved_model_conversion_v2.py
Labels: cla: yes

#3147 cherrypick remove unnecessary eager call (#3145) to 1.7.3
  tfjs-converter/python/tensorflowjs/converters/tf_saved_model_conversion_v2.py
Labels: cla: yes

#3142 [core] Change inputs to matMul test to avoid precision issues in Safari as stopgap.
  tfjs-core/src/ops/conv2d_test.ts
Labels: cla: yes

#3062 webgpu: Simplify the unary/binary shader conditionally
  tfjs-backend-webgpu/src/kernels/binary_op_webgpu.ts
  tfjs-backend-webgpu/src/kernels/unary_op_webgpu.ts
Labels: cla: yes

#2929 [webgpu] reduce workPerThread size when dispatch equal 1
  tfjs-backend-webgpu/src/benchmark_ops_test.ts
  tfjs-backend-webgpu/src/kernels/matmul_packed_webgpu.ts
Labels: cla: yes

#3094 Remove unnecessary integration tests in node and node-gpu.
  tfjs-data/yarn.lock
  tfjs-layers/yarn.lock
  tfjs-node-gpu/cloudbuild.yml
  tfjs-node-gpu/integration/typescript/package.json
  tfjs-node-gpu/integration/typescript/src/test.ts
  tfjs-node-gpu/integration/typescript/tsconfig.json
  tfjs-node-gpu/integration/typescript/yarn.lock
  tfjs-node-gpu/package.json
  tfjs-node/cloudbuild.yml
  tfjs-node/integration/typescript/src/test.ts
  tfjs-node/integration/typescript/tsconfig.json
  tfjs-node/integration/typescript/yarn.lock
  tfjs-node/package.json
  tfjs-node/scripts/test-ts-integration.sh
  tfjs/yarn.lock
Labels: cla: yes

#3058 Remove use of chained ops.
  tfjs-core/src/gradients/Div_grad.ts
  tfjs-core/src/gradients/FusedBatchNorm_grad.ts
  tfjs-core/src/gradients/Square_grad.ts
  tfjs-core/src/gradients/Tile_grad.ts
  tfjs-core/src/ops/batchnorm.ts
  tfjs-core/src/ops/broadcast_to.ts
  tfjs-core/src/ops/one_hot.ts
Labels: cla: yes

#3154 added support select v2 op
  tfjs-converter/python/tensorflowjs/op_list/logical.json
  tfjs-converter/src/operations/executors/logical_executor.ts
  tfjs-converter/src/operations/executors/logical_executor_test.ts
  tfjs-converter/src/operations/op_list/logical.ts
Labels: cla: yes

#3153 add tfjs-vis back to test matrix
  cloudbuild.yml
  tfjs-backend-cpu/package.json
Labels: cla: yes

#3157 fix tensor array gather
  tfjs-converter/src/executor/tensor_array.ts
  tfjs-converter/src/executor/tensor_array_test.ts
Labels: cla: yes

#3159 added support select v2 op (#3154)
  tfjs-converter/python/tensorflowjs/op_list/logical.json
  tfjs-converter/src/operations/executors/logical_executor.ts
  tfjs-converter/src/operations/executors/logical_executor_test.ts
  tfjs-converter/src/operations/op_list/logical.ts
Labels: cla: yes

#3161 Update tfjs-core to 1.7.4.
  tfjs-core/package.json
  tfjs-core/src/version.ts
Labels: INTERNAL, cla: yes

#3162 Update tfjs-layers, tfjs-converter to 1.7.4, 1.7.4.
  tfjs-converter/package.json
  tfjs-converter/python/tensorflowjs/version.py
  tfjs-converter/src/version.ts
  tfjs-converter/yarn.lock
  tfjs-layers/package.json
  tfjs-layers/src/version.ts
  tfjs-layers/yarn.lock
Labels: INTERNAL, cla: yes

#3163 Update tfjs-data to 1.7.4.
  tfjs-data/package.json
  tfjs-data/src/version.ts
  tfjs-data/yarn.lock
Labels: INTERNAL, cla: yes

#3164 Update tfjs to 1.7.4.
  tfjs/package.json
  tfjs/src/version.ts
  tfjs/yarn.lock
Labels: INTERNAL, cla: yes

#3165 Update tfjs-node, tfjs-node-gpu to 1.7.4, 1.7.4.
  tfjs-node-gpu/package.json
  tfjs-node-gpu/yarn.lock
  tfjs-node/package.json
  tfjs-node/src/version.ts
  tfjs-node/yarn.lock
Labels: INTERNAL, cla: yes

#3166 Update tfjs-backend-wasm to 1.7.4.
  tfjs-backend-wasm/package.json
  tfjs-backend-wasm/src/version.ts
  tfjs-backend-wasm/yarn.lock
Labels: INTERNAL, cla: yes

#3177 Update tfjs-core to 2.0.0-rc.1.
  tfjs-core/package.json
  tfjs-core/src/version.ts
Labels: INTERNAL, cla: yes

#3178 Update tfjs-layers, tfjs-converter to 2.0.0-rc.1, 2.0.0-rc.1.
  tfjs-converter/package.json
  tfjs-converter/python/tensorflowjs/version.py
  tfjs-converter/src/version.ts
  tfjs-layers/package.json
  tfjs-layers/src/version.ts
Labels: INTERNAL, cla: yes

#3179 Update tfjs-data to 2.0.0-rc.1.
  tfjs-data/package.json
  tfjs-data/src/version.ts
Labels: INTERNAL, cla: yes

#3181 Update tfjs-backend-cpu to 2.0.0-rc.1.
  tfjs-backend-cpu/package.json
  tfjs-backend-cpu/src/version.ts
Labels: INTERNAL, cla: yes

#3174 Update tfjs-backend-webgl to tfjs_2.0.0-rc.1.
  tfjs-backend-webgl/package.json
  tfjs-backend-webgl/src/version.ts
Labels: INTERNAL, cla: yes

#3180 Update tfjs to 2.0.0-rc.1.
  tfjs/package.json
  tfjs/src/version.ts
Labels: INTERNAL, cla: yes

#3171 [core] Change inputs to conv test as stopgap to fix precision errors in WebGL Safari.
  tfjs-core/src/ops/conv2d_test.ts
Labels: cla: yes
