Repository tensorflow/tfjs, pull requests merged in 2020-05, with the labels that each got.

#3187 [core] Restrict size of conv test output to temporarily fix precision issues in Safari.
  tfjs-core/src/ops/fused_test.ts
Labels: cla: yes

#3193 Update tfjs-node, tfjs-node-gpu to 2.0.0-rc.1, 2.0.0-rc.1.
  tfjs-node-gpu/package.json
  tfjs-node-gpu/yarn.lock
  tfjs-node/package.json
  tfjs-node/src/version.ts
  tfjs-node/yarn.lock
Labels: INTERNAL, cla: yes

#3198 Increase capture timeout.
  tfjs-core/karma.conf.js
  tfjs-core/scripts/test-ci.sh
Labels: cla: yes

#3199 Temporarily remove ios test in nightly build.
  tfjs-backend-webgl/scripts/test-ci.sh
  tfjs-core/scripts/test-ci.sh
Labels: cla: yes

#3204 Fix browserstack iPhone browser issue.
  tfjs-backend-webgl/karma.conf.js
  tfjs-backend-webgl/scripts/test-ci.sh
  tfjs-core/karma.conf.js
  tfjs-core/scripts/test-ci.sh
Labels: cla: yes

#3201 [tfjs-node] fix import in README.md
  tfjs-node/README.md
Labels: cla: yes

#3194 Add exported symbols back to webgl backend
  package.json
  scripts/publish-npm.ts
  scripts/release-util.ts
  scripts/release-website.ts
  scripts/release.ts
  tfjs-backend-cpu/src/index.ts
  tfjs-backend-cpu/src/version.ts
  tfjs-backend-webgl/rollup.config.js
  tfjs-backend-webgl/src/index.ts
  tfjs-backend-webgl/src/kernels/Transpose_impl.ts
  tfjs-backend-webgl/src/version.ts
  tfjs-core/cloudbuild.yml
  tfjs-core/karma.conf.js
  tfjs-core/src/kernel_registry.ts
  tfjs-core/src/kernel_registry_test.ts
  tfjs-node-gpu/package.json
  tfjs-node/package.json
  tfjs-node/scripts/build-npm.sh
  tfjs-react-native/cloudbuild.yml
  tfjs-react-native/integration_rn59/components/tfjs_unit_test_runner.tsx
  tfjs-react-native/integration_rn59/package.json
  tfjs-react-native/integration_rn59/scripts/prep_tests.ts
  tfjs-react-native/integration_rn59/scripts/test-ci.sh
  tfjs-react-native/integration_rn59/yarn.lock
  tfjs-react-native/package.json
  tfjs-react-native/src/camera/camera_webgl_util.ts
  tfjs-react-native/src/platform_react_native.ts
  tfjs-react-native/yarn.lock
  tfjs/package.json
  tfjs/rollup.config.js
  tfjs/src/index.ts
  tfjs/yarn.lock
  yarn.lock
Labels: cla: yes

#3009 Adding Touch The Dot game to the gallery
  GALLERY.md
Labels: cla: yes

#3209 Fix nightly build.
  tfjs-backend-webgl/scripts/test-ci.sh
Labels: cla: yes

#3208 Nightly test fixes
  tfjs-core/karma.conf.js
  tfjs/scripts/test-ci.sh
Labels: cla: yes

#3120 [core] Modularize conv ops.
  tfjs-backend-wasm/src/kernels/Conv2D.ts
  tfjs-backend-wasm/src/kernels/DepthwiseConv2dNative.ts
  tfjs-core/src/gradients/Conv2DBackpropInput_grad.ts
  tfjs-core/src/gradients/Conv2D_grad.ts
  tfjs-core/src/gradients/Conv3D_grad.ts
  tfjs-core/src/gradients/DepthwiseConv2dNative_grad.ts
  tfjs-core/src/kernel_names.ts
  tfjs-core/src/ops/conv.ts
  tfjs-core/src/ops/conv1d.ts
  tfjs-core/src/ops/conv2d.ts
  tfjs-core/src/ops/conv2d_backprop_filter.ts
  tfjs-core/src/ops/conv2d_backprop_input.ts
  tfjs-core/src/ops/conv2d_depthwise_test.ts
  tfjs-core/src/ops/conv2d_transpose.ts
  tfjs-core/src/ops/conv3d.ts
  tfjs-core/src/ops/conv3d_backprop_filter.ts
  tfjs-core/src/ops/conv3d_backprop_input.ts
  tfjs-core/src/ops/conv3d_transpose.ts
  tfjs-core/src/ops/depthwise_conv2d.ts
  tfjs-core/src/ops/depthwise_conv2d_native_backprop_filter.ts
  tfjs-core/src/ops/depthwise_conv2d_native_backprop_input.ts
  tfjs-core/src/ops/fused_ops.ts
  tfjs-core/src/ops/ops.ts
  tfjs-core/src/ops/separable_conv2d.ts
  tfjs-core/src/public/chained_ops/conv1d.ts
  tfjs-core/src/public/chained_ops/conv2d.ts
  tfjs-core/src/public/chained_ops/conv2d_transpose.ts
  tfjs-core/src/public/chained_ops/depthwise_conv2D_deprecated.ts
  tfjs-core/src/public/chained_ops/depthwise_conv2d.ts
  tfjs-core/src/public/chained_ops/register_all_chained_ops.ts
  tfjs-core/src/public/chained_ops/register_all_chained_ops_test.ts
  tfjs-core/src/public/chained_ops/separable_conv2d.ts
  tfjs-core/src/register_all_gradients.ts
  tfjs-core/src/tensor.ts
  tfjs-node/src/nodejs_kernel_backend.ts
Labels: cla: yes

#3211 Update tfjs-core to 2.0.0-rc.3.
  tfjs-core/package.json
  tfjs-core/src/version.ts
Labels: INTERNAL, cla: yes

#3212 Update tfjs-backend-cpu to 2.0.0-rc.3.
  tfjs-backend-cpu/package.json
  tfjs-backend-cpu/src/version.ts
  tfjs-backend-cpu/yarn.lock
Labels: INTERNAL, cla: yes

#3213 Update tfjs-backend-webgl to 2.0.0-rc.3.
  tfjs-backend-webgl/package.json
  tfjs-backend-webgl/src/version.ts
  tfjs-backend-webgl/yarn.lock
Labels: INTERNAL, cla: yes

#3214 Update tfjs-layers, tfjs-converter to 2.0.0-rc.3, 2.0.0-rc.3.
  tfjs-converter/package.json
  tfjs-converter/python/tensorflowjs/version.py
  tfjs-converter/src/version.ts
  tfjs-converter/yarn.lock
  tfjs-layers/package.json
  tfjs-layers/src/version.ts
  tfjs-layers/yarn.lock
Labels: INTERNAL, cla: yes

#3215 Update tfjs-data to 2.0.0-rc.3.
  tfjs-data/package.json
  tfjs-data/src/version.ts
  tfjs-data/yarn.lock
Labels: INTERNAL, cla: yes

#3216 Update tfjs to 2.0.0-rc.3.
  tfjs/package.json
  tfjs/src/version.ts
  tfjs/yarn.lock
Labels: INTERNAL, cla: yes

#3219 Update tfjs-node, tfjs-node-gpu to 2.0.0-rc.3, 2.0.0-rc.3.
  tfjs-node-gpu/package.json
  tfjs-node-gpu/yarn.lock
  tfjs-node/package.json
  tfjs-node/src/version.ts
  tfjs-node/yarn.lock
Labels: INTERNAL, cla: yes

#3220 Update tfjs-backend-wasm to 2.0.0-rc.3.
  tfjs-backend-wasm/package.json
  tfjs-backend-wasm/src/version.ts
  tfjs-backend-wasm/yarn.lock
Labels: INTERNAL, cla: yes

#3183 [wasm] Add split, sqrt kernels.
  tfjs-backend-wasm/src/cc/kernels/Sqrt.cc
  tfjs-backend-wasm/src/kernels/Split.ts
  tfjs-backend-wasm/src/kernels/Sqrt.ts
  tfjs-backend-wasm/src/kernels/all_kernels.ts
  tfjs-backend-wasm/src/setup_test.ts
  tfjs-core/src/backends/split_shared.ts
  tfjs-core/src/ops/split.ts
  tfjs-core/src/ops/unary_ops.ts
Labels: cla: yes

#3222 Update tfjs-react-native to depend on tfjs 2.x
  tfjs-react-native/cloudbuild.yml
  tfjs-react-native/integration_rn59/package.json
  tfjs-react-native/integration_rn59/yarn.lock
  tfjs-react-native/package.json
  tfjs-react-native/yarn.lock
Labels: cla: yes

#3210 [webgpu] Update build to match other packages.
  tfjs-backend-webgl/package.json
  tfjs-backend-webgl/yarn.lock
  tfjs-backend-webgpu/karma.conf.js
  tfjs-backend-webgpu/package.json
  tfjs-backend-webgpu/rollup.config.js
  tfjs-backend-webgpu/src/kernels/crop_and_resize_webgpu.ts
  tfjs-backend-webgpu/src/kernels/matmul_packed_webgpu.ts
  tfjs-backend-webgpu/tsconfig.test.json
  tfjs-backend-webgpu/yarn.lock
Labels: cla: yes

#3225 Fix webgl bundling and test invocation
  tfjs-backend-cpu/package.json
  tfjs-backend-wasm/package.json
  tfjs-backend-webgl/rollup.config.js
  tfjs-converter/package.json
  tfjs-core/package.json
  tfjs-data/package.json
  tfjs-node-gpu/package.json
  tfjs-node/package.json
Labels: cla: yes

#3237 allow tfjs to dep on tf-cpu latest version
  tfjs-converter/python/requirements.txt
Labels: cla: yes

#3233 [data] Remove deprecated API in tfjs-data
  tfjs-data/src/dataset.ts
  tfjs-data/src/dataset_test.ts
  tfjs-data/src/index.ts
  tfjs-data/src/iterators/lazy_iterator.ts
  tfjs-data/src/types.ts
Labels: cla: yes

#3217 Modularize diag.
  tfjs-core/src/kernel_names.ts
  tfjs-core/src/ops/diag.ts
  tfjs-core/src/ops/ops.ts
Labels: cla: yes

#3243 correct typo on tf.node.tensorBoard doc
  tfjs-node/src/callbacks.ts
Labels: cla: yes

#3242 Add support for napi version 6
  tfjs-node-gpu/package.json
  tfjs-node/package.json
Labels: cla: yes

#3240 allow tfjs to dep on tf-cpu latest version
  tfjs-converter/python/requirements.txt
Labels: cla: yes

#3239 deprecate strict variants of ops
  tfjs-core/src/globals_test.ts
  tfjs-core/src/ops/add.ts
  tfjs-core/src/ops/binary_ops.ts
  tfjs-core/src/ops/compare.ts
  tfjs-core/src/ops/div.ts
  tfjs-core/src/ops/div_no_nan.ts
  tfjs-core/src/ops/equal.ts
  tfjs-core/src/ops/greater.ts
  tfjs-core/src/ops/greater_equal.ts
  tfjs-core/src/ops/less.ts
  tfjs-core/src/ops/less_equal.ts
  tfjs-core/src/ops/linalg_ops.ts
  tfjs-core/src/ops/lstm.ts
  tfjs-core/src/ops/not_equal.ts
  tfjs-core/src/ops/relu_ops.ts
  tfjs-core/src/ops/softmax_test.ts
  tfjs-core/src/ops/squared_difference.ts
  tfjs-core/src/ops/sub.ts
  tfjs-core/src/ops/unary_ops.ts
  tfjs-core/src/optimizers/optimizer_test.ts
  tfjs-core/src/tensor.ts
  tfjs-layers/src/backend/tfjs_backend.ts
  tfjs-layers/src/constraints.ts
  tfjs-layers/src/engine/training_test.ts
  tfjs-layers/src/layers/merge.ts
  tfjs-layers/src/layers/recurrent.ts
  tfjs-layers/src/utils/math_utils.ts
Labels: cla: yes

#3235 [node] Remove deprecated createTypeOpAttr
  tfjs-node/src/kernels/Softmax.ts
  tfjs-node/src/kernels/SquaredDifference.ts
  tfjs-node/src/kernels/non_max_suppression_v5.ts
  tfjs-node/src/nodejs_kernel_backend.ts
  tfjs-node/src/nodejs_kernel_backend_test.ts
Labels: cla: yes

#3223 Modularize matmul.
  tfjs-core/src/gradients/BatchMatMul_grad.ts
  tfjs-core/src/kernel_names.ts
  tfjs-core/src/ops/compare_ops_test.ts
  tfjs-core/src/ops/dot.ts
  tfjs-core/src/ops/fused_ops.ts
  tfjs-core/src/ops/mat_mul.ts
  tfjs-core/src/ops/mat_mul_test.ts
  tfjs-core/src/ops/matmul.ts
  tfjs-core/src/ops/ops.ts
  tfjs-core/src/ops/outer_product.ts
  tfjs-core/src/public/chained_ops/dot.ts
  tfjs-core/src/public/chained_ops/mat_mul.ts
  tfjs-core/src/public/chained_ops/register_all_chained_ops.ts
  tfjs-core/src/public/chained_ops/register_all_chained_ops_test.ts
  tfjs-core/src/register_all_gradients.ts
  tfjs-core/src/tensor.ts
  tfjs-core/src/tests.ts
Labels: cla: yes

#3238 Remove deprecated batchnormalization op
  tfjs-backend-cpu/src/backend_cpu.ts
  tfjs-backend-webgl/src/backend_webgl.ts
  tfjs-core/src/backends/backend.ts
  tfjs-core/src/ops/batchnorm.ts
  tfjs-core/src/ops/batchnorm2d.ts
  tfjs-core/src/ops/batchnorm3d.ts
  tfjs-core/src/ops/batchnorm4d.ts
  tfjs-core/src/ops/batchnorm_test.ts
  tfjs-core/src/ops/batchnorm_util.ts
  tfjs-core/src/ops/ops.ts
  tfjs-core/src/tensor.ts
  tfjs-layers/cloudbuild.yml
  tfjs-node/src/nodejs_kernel_backend.ts
Labels: cla: yes

#3246 [tfjs-react-native] Update camera.tsx docs
  tfjs-react-native/src/camera/camera_stream.tsx
Labels: cla: yes

#3248 Fix node and nodegpu build.
  tfjs-node-gpu/package.json
  tfjs-node/package.json
Labels: cla: yes

#3249 Update tfjs-core to 2.0.0-rc.4.
  tfjs-core/package.json
  tfjs-core/src/version.ts
Labels: INTERNAL, cla: yes

#3250 Update tfjs-backend-cpu to 2.0.0-rc.4.
  tfjs-backend-cpu/package.json
  tfjs-backend-cpu/src/version.ts
  tfjs-backend-cpu/yarn.lock
Labels: INTERNAL, cla: yes

#3251 Update tfjs-backend-webgl to 2.0.0-rc.4.
  tfjs-backend-webgl/package.json
  tfjs-backend-webgl/src/version.ts
  tfjs-backend-webgl/yarn.lock
Labels: INTERNAL, cla: yes

#3253 Update tfjs-layers, tfjs-converter to 2.0.0-rc.4, 2.0.0-rc.4.
  tfjs-converter/package.json
  tfjs-converter/python/tensorflowjs/version.py
  tfjs-converter/src/version.ts
  tfjs-converter/yarn.lock
  tfjs-layers/package.json
  tfjs-layers/src/version.ts
  tfjs-layers/yarn.lock
Labels: INTERNAL, cla: yes

#3254 Update tfjs-data to 2.0.0-rc.4.
  tfjs-data/package.json
  tfjs-data/src/version.ts
  tfjs-data/yarn.lock
Labels: INTERNAL, cla: yes

#3255 Update tfjs to 2.0.0-rc.4.
  tfjs/package.json
  tfjs/src/version.ts
  tfjs/yarn.lock
Labels: INTERNAL, cla: yes

#3256 Update tfjs-node, tfjs-node-gpu to 2.0.0-rc.4, 2.0.0-rc.4.
  tfjs-node-gpu/package.json
  tfjs-node-gpu/yarn.lock
  tfjs-node/package.json
  tfjs-node/src/version.ts
  tfjs-node/yarn.lock
Labels: INTERNAL, cla: yes

#3258 Update tfjs-backend-wasm to 2.0.0-rc.4.
  tfjs-backend-wasm/package.json
  tfjs-backend-wasm/src/version.ts
  tfjs-backend-wasm/yarn.lock
Labels: INTERNAL, cla: yes

#2652 [webgpu] Add batchNormal kernel
  tfjs-backend-webgpu/src/kernels/FusedBatchNorm.ts
  tfjs-backend-webgpu/src/kernels/batchnorm_webgpu.ts
  tfjs-backend-webgpu/src/register_all_kernels.ts
  tfjs-backend-webgpu/src/setup_test.ts
  tfjs-backend-webgpu/src/shader_preprocessor.ts
Labels: cla: yes

#3096 [webgpu] Fix fusedConv2d bias weight and add teset case
  tfjs-backend-wasm/src/setup_test.ts
  tfjs-backend-webgpu/src/kernels/conv2d_mm_webgpu.ts
  tfjs-backend-webgpu/src/kernels/conv2d_naive_webgpu.ts
  tfjs-core/src/ops/fused_test.ts
Labels: cla: yes

#3268 fix test-snippets invocation
  tfjs-converter/package.json
  tfjs-data/package.json
  tfjs-layers/package.json
Labels: cla: yes

#3261 add READMEs to cpu and webgl backends
  tfjs-backend-cpu/README.md
  tfjs-backend-webgl/README.md
Labels: cla: yes

#3262 add miniprogram entries for cpu and webgl backends
  tfjs-backend-cpu/package.json
  tfjs-backend-cpu/scripts/build-npm.sh
  tfjs-backend-webgl/package.json
  tfjs-backend-webgl/scripts/build-npm.sh
Labels: cla: yes

#3148 [webgpu] Use TensorInfo instead of Tensor
  tfjs-backend-webgpu/src/backend_webgpu.ts
  tfjs-backend-webgpu/src/kernels/webgpu_program.ts
Labels: cla: yes

#3276 [webgpu] Fix the glsl compilation error
  tfjs-backend-webgpu/src/shader_preprocessor.ts
Labels: cla: yes

#3279 make sure graph def library fields are not removed during optimization
  tfjs-converter/python/tensorflowjs/converters/fold_batch_norms.py
  tfjs-converter/python/tensorflowjs/converters/graph_rewrite_util.py
  tfjs-converter/python/tensorflowjs/converters/tf_saved_model_conversion_v2.py
Labels: cla: yes

#3277 Modularize depthToSpace.
  tfjs-core/src/kernel_names.ts
  tfjs-core/src/ops/array_ops.ts
  tfjs-core/src/ops/array_ops_test.ts
  tfjs-core/src/ops/depth_to_space.ts
  tfjs-core/src/ops/depth_to_space_test.ts
  tfjs-core/src/ops/ops.ts
  tfjs-core/src/public/chained_ops/depth_to_space.ts
  tfjs-core/src/public/chained_ops/register_all_chained_ops.ts
  tfjs-core/src/public/chained_ops/register_all_chained_ops_test.ts
  tfjs-core/src/tensor.ts
  tfjs-core/src/tests.ts
Labels: cla: yes

#3280 add back arm support
  tfjs-node/scripts/install.js
Labels: cla: no

#3257 add default object to layer constructor
  tfjs-layers/src/engine/topology.ts
  tfjs-layers/src/engine/topology_test.ts
Labels: cla: yes

#3156 [layers] `sparseCategoricalCrossentropy` should have `fromLogits` as a function parameter
  tfjs-layers/src/losses.ts
Labels: cla: yes

#3286 use the loadOptions to find the IOHandler
  tfjs-converter/src/executor/graph_model.ts
  tfjs-converter/src/executor/graph_model_test.ts
  tfjs-core/src/io/http.ts
  tfjs-core/src/io/router_registry.ts
  tfjs-core/src/io/router_registry_test.ts
  tfjs-layers/src/models.ts
Labels: cla: yes

#3245 update devDependencies
  tfjs-backend-nodegl/demo/package.json
  tfjs-backend-nodegl/demo/yarn.lock
  tfjs-backend-nodegl/package.json
  tfjs-backend-nodegl/yarn.lock
  tfjs-backend-wasm/package.json
  tfjs-backend-wasm/yarn.lock
  tfjs-core/package.json
  tfjs-core/yarn.lock
  tfjs/integration_tests/package.json
  tfjs/package.json
  tfjs/yarn.lock
Labels: cla: yes

#3292 Update react native docs
  tfjs-react-native/README.md
  tfjs-react-native/src/bundle_resource_io.ts
  tfjs-react-native/src/decode_image.ts
Labels: cla: yes

#3316 fix: typedarray perf
  tfjs-core/src/io/io_utils.ts
Labels: cla: yes

#3317 avoid unnecessary calc
  tfjs-core/src/io/io_utils.ts
Labels: cla: yes

#3322 Update tfjs-core to 2.0.0.
  tfjs-core/package.json
  tfjs-core/src/version.ts
Labels: INTERNAL, cla: yes

#3323 Update tfjs-backend-cpu to 2.0.0.
  tfjs-backend-cpu/package.json
  tfjs-backend-cpu/src/version.ts
  tfjs-backend-cpu/yarn.lock
Labels: INTERNAL, cla: yes

#3324 Update tfjs-backend-webgl to 2.0.0.
  tfjs-backend-webgl/package.json
  tfjs-backend-webgl/src/version.ts
  tfjs-backend-webgl/yarn.lock
Labels: INTERNAL, cla: yes

#3325 Update tfjs-layers, tfjs-converter to 2.0.0, 2.0.0.
  tfjs-converter/package.json
  tfjs-converter/python/tensorflowjs/version.py
  tfjs-converter/src/version.ts
  tfjs-converter/yarn.lock
  tfjs-layers/package.json
  tfjs-layers/src/version.ts
  tfjs-layers/yarn.lock
Labels: INTERNAL, cla: yes

#3327 Update tfjs-data to 2.0.0.
  tfjs-data/package.json
  tfjs-data/src/version.ts
  tfjs-data/yarn.lock
Labels: INTERNAL, cla: yes

#3328 Update tfjs to 2.0.0.
  tfjs/package.json
  tfjs/src/version.ts
  tfjs/yarn.lock
Labels: INTERNAL, cla: yes

#3330 Update tfjs-node, tfjs-node-gpu to 2.0.0.
  tfjs-node-gpu/package.json
  tfjs-node-gpu/yarn.lock
  tfjs-node/package.json
  tfjs-node/src/version.ts
  tfjs-node/yarn.lock
Labels: INTERNAL, cla: yes

#3332 Update tfjs-backend-wasm to 2.0.0.
  tfjs-backend-wasm/package.json
  tfjs-backend-wasm/src/version.ts
  tfjs-backend-wasm/yarn.lock
Labels: INTERNAL, cla: yes

#3269 Modularize pool ops.
  tfjs-backend-wasm/src/kernels/AvgPool.ts
  tfjs-backend-wasm/src/kernels/MaxPool.ts
  tfjs-core/src/gradients/AvgPool3D_grad.ts
  tfjs-core/src/gradients/AvgPool_grad.ts
  tfjs-core/src/gradients/MaxPool3D_grad.ts
  tfjs-core/src/gradients/MaxPool_grad.ts
  tfjs-core/src/kernel_names.ts
  tfjs-core/src/ops/avg_pool.ts
  tfjs-core/src/ops/avg_pool_3d.ts
  tfjs-core/src/ops/avg_pool_3d_backprop.ts
  tfjs-core/src/ops/avg_pool_3d_test.ts
  tfjs-core/src/ops/avg_pool_backprop.ts
  tfjs-core/src/ops/avg_pool_test.ts
  tfjs-core/src/ops/max_pool.ts
  tfjs-core/src/ops/max_pool_3d.ts
  tfjs-core/src/ops/max_pool_3d_backprop.ts
  tfjs-core/src/ops/max_pool_3d_test.ts
  tfjs-core/src/ops/max_pool_backprop.ts
  tfjs-core/src/ops/max_pool_test.ts
  tfjs-core/src/ops/max_pool_with_argmax.ts
  tfjs-core/src/ops/max_pool_with_argmax_test.ts
  tfjs-core/src/ops/ops.ts
  tfjs-core/src/ops/pool.ts
  tfjs-core/src/ops/pool_test.ts
  tfjs-core/src/public/chained_ops/avg_pool.ts
  tfjs-core/src/public/chained_ops/max_pool.ts
  tfjs-core/src/public/chained_ops/pool.ts
  tfjs-core/src/public/chained_ops/register_all_chained_ops.ts
  tfjs-core/src/public/chained_ops/register_all_chained_ops_test.ts
  tfjs-core/src/register_all_gradients.ts
  tfjs-core/src/tensor.ts
  tfjs-core/src/tests.ts
Labels: cla: yes

#3334 [WASM] Fix allocation issue for buffers with byteOffsets
  tfjs-backend-wasm/src/backend_wasm.ts
  tfjs-backend-wasm/src/index_test.ts
Labels: cla: yes

#3333 fix release notes script
  package.json
  scripts/release_notes/release_notes.ts
  scripts/release_notes/release_notes_test.ts
  scripts/release_notes/util.ts
  yarn.lock
Labels: cla: yes

#3339 Update readme to highlight tfjs 2.0 release
  README.md
Labels: cla: yes

#3304 Add support for ellipsisMask in stridedSlice.
  tfjs-core/src/ops/slice_util.ts
  tfjs-core/src/ops/strided_slice.ts
  tfjs-core/src/ops/strided_slice_test.ts
Labels: cla: yes

#3296 Modularize cumsum.
  tfjs-core/src/gradients/Cumsum_grad.ts
  tfjs-core/src/kernel_names.ts
  tfjs-core/src/ops/array_ops.ts
  tfjs-core/src/ops/array_ops_test.ts
  tfjs-core/src/ops/cumsum.ts
  tfjs-core/src/ops/cumsum_test.ts
  tfjs-core/src/ops/image_ops_test.ts
  tfjs-core/src/ops/ops.ts
  tfjs-core/src/public/chained_ops/cumsum.ts
  tfjs-core/src/public/chained_ops/register_all_chained_ops.ts
  tfjs-core/src/public/chained_ops/register_all_chained_ops_test.ts
  tfjs-core/src/register_all_gradients.ts
  tfjs-core/src/tensor.ts
  tfjs-core/src/tests.ts
Labels: cla: yes

#3305 Add op modularization guide.
  tfjs-core/development/op_modularization.md
Labels: cla: yes

#3320 webgpu: Use shared memory for binary op
  tfjs-backend-webgpu/src/kernels/binary_op_webgpu.ts
Labels: cla: yes

#3321 webgpu: Remove uniform buffer when not needed
  tfjs-backend-webgpu/src/backend_webgpu.ts
  tfjs-backend-webgpu/src/kernels/argminmax_webgpu.ts
  tfjs-backend-webgpu/src/kernels/batchnorm_webgpu.ts
  tfjs-backend-webgpu/src/kernels/binary_op_webgpu.ts
  tfjs-backend-webgpu/src/kernels/clip_webgpu.ts
  tfjs-backend-webgpu/src/kernels/concat_webgpu.ts
  tfjs-backend-webgpu/src/kernels/conv2d_mm_webgpu.ts
  tfjs-backend-webgpu/src/kernels/conv2d_naive_webgpu.ts
  tfjs-backend-webgpu/src/kernels/crop_and_resize_webgpu.ts
  tfjs-backend-webgpu/src/kernels/depthwise_conv2d_webgpu.ts
  tfjs-backend-webgpu/src/kernels/fill_webgpu.ts
  tfjs-backend-webgpu/src/kernels/from_pixels_webgpu.ts
  tfjs-backend-webgpu/src/kernels/im2col_webgpu.ts
  tfjs-backend-webgpu/src/kernels/matmul_packed_webgpu.ts
  tfjs-backend-webgpu/src/kernels/matmul_webgpu.ts
  tfjs-backend-webgpu/src/kernels/maxpool_filtersizeone_webgpu.ts
  tfjs-backend-webgpu/src/kernels/maxpool_webgpu.ts
  tfjs-backend-webgpu/src/kernels/pad_webgpu.ts
  tfjs-backend-webgpu/src/kernels/reduce_webgpu.ts
  tfjs-backend-webgpu/src/kernels/resize_bilinear_webgpu.ts
  tfjs-backend-webgpu/src/kernels/select_webgpu.ts
  tfjs-backend-webgpu/src/kernels/slice_webgpu.ts
  tfjs-backend-webgpu/src/kernels/strided_slice_webgpu.ts
  tfjs-backend-webgpu/src/kernels/transpose_shared_webgpu.ts
  tfjs-backend-webgpu/src/kernels/transpose_webgpu.ts
  tfjs-backend-webgpu/src/kernels/unary_op_webgpu.ts
  tfjs-backend-webgpu/src/kernels/webgpu_program.ts
  tfjs-backend-webgpu/src/shader_preprocessor.ts
Labels: cla: yes

#3337 Fix maxPool save.
  tfjs-core/src/ops/max_pool.ts
Labels: cla: yes

#3346 Adding support for Control flow v2 in converter and executor
  .vscode/settings.json
  tfjs-converter/python/requirements-dev.txt
  tfjs-converter/python/tensorflowjs/converters/common.py
  tfjs-converter/python/tensorflowjs/converters/converter.py
  tfjs-converter/python/tensorflowjs/converters/tf_saved_model_conversion_v2.py
  tfjs-converter/python/tensorflowjs/converters/tf_saved_model_conversion_v2_test.py
  tfjs-converter/python/tensorflowjs/converters/wizard.py
  tfjs-converter/python/tensorflowjs/converters/wizard_test.py
  tfjs-converter/python/tensorflowjs/op_list/control.json
  tfjs-converter/src/executor/execution_context.ts
  tfjs-converter/src/executor/graph_executor.ts
  tfjs-converter/src/executor/graph_executor_test.ts
  tfjs-converter/src/executor/model_analysis.ts
  tfjs-converter/src/executor/types.ts
  tfjs-converter/src/operations/executors/control_executor.ts
  tfjs-converter/src/operations/executors/control_executor_test.ts
  tfjs-converter/src/operations/executors/utils.ts
  tfjs-converter/src/operations/op_list/control.ts
  tfjs-converter/src/operations/op_mapper_schema.ts
  tfjs-converter/src/operations/operation_mapper.ts
  tfjs-converter/src/operations/operation_mapper_test.ts
  tfjs-converter/src/operations/types.ts
Labels: cla: yes

#3351 nms perf
  tfjs-core/src/backends/non_max_suppression_impl.ts
Labels: cla: yes

#3338 Clean up integration test in layers.
  tfjs-layers/cloudbuild.yml
  tfjs-layers/integration_tests/tfjs2keras/package.json
  tfjs-layers/integration_tests/tfjs2keras/requirements-dev.txt
  tfjs-layers/integration_tests/tfjs2keras/requirements-stable.txt
  tfjs-layers/integration_tests/tfjs2keras/tfjs2keras_test.py
  tfjs-layers/integration_tests/tfjs2keras/tfjs_save.js
  tfjs-layers/integration_tests/tfjs2keras/tsconfig.json
  tfjs-layers/integration_tests/tfjs2keras/yarn.lock
  tfjs-layers/package.json
  tfjs-layers/scripts/switch-tfjs-core-version.sh
  tfjs-layers/scripts/tfjs2keras-js.sh
  tfjs-layers/scripts/tfjs2keras-py.sh
Labels: cla: yes

#3349 webgpu: Fix the deprecated type warnings
  tfjs-backend-webgpu/package.json
  tfjs-backend-webgpu/src/backend_webgpu.ts
  tfjs-backend-webgpu/src/buffer_manager.ts
  tfjs-backend-webgpu/src/kernels/webgpu_program.ts
  tfjs-backend-webgpu/yarn.lock
Labels: cla: yes

#3350 webgpu: Fix the incorrect array comparision
  tfjs-backend-webgpu/src/kernels/matmul_packed_webgpu.ts
Labels: cla: yes
