Repository tensorflow/tfjs, pull requests merged in 2021-04, with the labels that each got.

#4855 Add tf.meshgrid support for 2D case only
  tfjs-core/src/ops/meshgrid.ts
  tfjs-core/src/ops/meshgrid_test.ts
  tfjs-core/src/ops/ops.ts
  tfjs-core/src/tests.ts
Labels: cla: yes

#4894 do not dispose intermediate tensor with kept status
  tfjs-converter/src/executor/graph_executor.ts
Labels: cla: yes

#4882 Update cloud functions README to use node 14
  scripts/cloud_funcs/README.md
Labels: cla: yes

#4888 webgpu: Batch submitted command encoders
  tfjs-backend-webgpu/src/backend_webgpu.ts
  tfjs-backend-webgpu/src/backend_webgpu_test.ts
  tfjs-backend-webgpu/src/flags_webgpu.ts
  tfjs-backend-webgpu/src/matmul_test.ts
Labels: cla: yes

#4862 webgpu: fix profiling error
  tfjs-backend-webgpu/src/backend_webgpu.ts
  tfjs-backend-webgpu/src/index.ts
Labels: cla: yes

#4899 Fix meshgrid tests broken by WebGL precision
  tfjs-core/src/ops/meshgrid_test.ts
Labels: cla: yes

#4896 webgpu: Flatten dispatch layout for cropAndResize/resizeBiliear
  tfjs-backend-webgpu/src/kernels/crop_and_resize_webgpu.ts
  tfjs-backend-webgpu/src/kernels/resize_bilinear_webgpu.ts
Labels: cla: yes

#4893 Remove WASM Emscripten install instructions
  tfjs-backend-wasm/README.md
Labels: cla: yes

#2641 [layers]: Add Conv3DTranspose Layer
  tfjs-layers/src/exports_layers.ts
  tfjs-layers/src/layers/convolutional.ts
  tfjs-layers/src/layers/convolutional_test.ts
Labels: cla: yes

#4900 Initial TFLite support
  tfjs-tflite/README.md
  tfjs-tflite/demo/README.md
  tfjs-tflite/demo/models/cartoongan_fp16.tflite
  tfjs-tflite/demo/package.json
  tfjs-tflite/demo/screenshot.png
  tfjs-tflite/demo/src/cat.jpg
  tfjs-tflite/demo/src/index.html
  tfjs-tflite/demo/src/magic.svg
  tfjs-tflite/demo/src/mountain.jpg
  tfjs-tflite/demo/src/people.jpg
  tfjs-tflite/demo/src/pizza.jpg
  tfjs-tflite/demo/src/room.jpg
  tfjs-tflite/demo/src/script.ts
  tfjs-tflite/demo/tsconfig.json
  tfjs-tflite/demo/yarn.lock
  tfjs-tflite/karma.conf.js
  tfjs-tflite/package.json
  tfjs-tflite/rollup.config.js
  tfjs-tflite/scripts/build-npm.sh
  tfjs-tflite/scripts/download-tfweb.sh
  tfjs-tflite/scripts/get-current-version.js
  tfjs-tflite/src/index.ts
  tfjs-tflite/src/setup_test.ts
  tfjs-tflite/src/tflite_model.ts
  tfjs-tflite/src/tflite_model_test.ts
  tfjs-tflite/src/tfweb_client.d.ts
  tfjs-tflite/src/tfweb_client.js
  tfjs-tflite/src/types/tfweb_model_runner.ts
  tfjs-tflite/tsconfig.json
  tfjs-tflite/tsconfig.test.json
  tfjs-tflite/tslint.json
  tfjs-tflite/yarn.lock
Labels: cla: yes

#4895 Make tfjs-core tests more robust
  tfjs-core/src/engine_test.ts
  tfjs-core/src/environment.ts
  tfjs-core/src/environment_test.ts
  tfjs-core/src/globals_test.ts
  tfjs-core/src/optimizers/adadelta_optimizer_test.ts
  tfjs-core/src/optimizers/adagrad_optimizer_test.ts
  tfjs-core/src/optimizers/adam_optimizer_test.ts
  tfjs-core/src/optimizers/adamax_optimizer_test.ts
  tfjs-core/src/optimizers/optimizer_test.ts
  tfjs-core/src/optimizers/rmsprop_optimizer_test.ts
  tfjs-core/src/optimizers/sgd_optimizer_test.ts
Labels: cla: yes

#4908 [webgl]Remove cpu backend warning.
  tfjs-backend-webgl/src/backend_webgl.ts
Labels: cla: yes

#4897 webgpu: batch several compute passes into one command encoder
  tfjs-backend-webgpu/src/backend_webgpu.ts
  tfjs-backend-webgpu/src/kernels/FromPixelsImageBitmap.ts
  tfjs-backend-webgpu/src/kernels/FromPixels_utils/from_pixels_webgpu.ts
Labels: cla: yes

#4903 [core] Add basic implementation of einsum
  tfjs-backend-cpu/src/kernels/Einsum.ts
  tfjs-backend-cpu/src/register_all_kernels.ts
  tfjs-backend-webgl/src/kernels/Einsum.ts
  tfjs-backend-webgl/src/register_all_kernels.ts
  tfjs-core/src/backends/backend_util.ts
  tfjs-core/src/backends/einsum_util.ts
  tfjs-core/src/kernel_names.ts
  tfjs-core/src/ops/einsum.ts
  tfjs-core/src/ops/einsum_test.ts
  tfjs-core/src/ops/ops.ts
  tfjs-core/src/tests.ts
  tfjs-node/src/run_tests.ts
Labels: cla: yes

#4914 [converter] Support Einsum
  tfjs-converter/docs/supported_ops.md
  tfjs-converter/metadata/kernel2op.json
  tfjs-converter/python/tensorflowjs/op_list/matrices.json
  tfjs-converter/src/operations/executors/matrices_executor.ts
  tfjs-converter/src/operations/executors/matrices_executor_test.ts
  tfjs-converter/src/operations/op_list/matrices.ts
Labels: cla: yes

#4915 [core] Fix a bug in einsum kernels
  tfjs-backend-cpu/src/kernels/Einsum.ts
  tfjs-backend-webgl/src/kernels/Einsum.ts
  tfjs-core/src/backends/einsum_util.ts
  tfjs-core/src/ops/einsum.ts
  tfjs-core/src/ops/einsum_test.ts
Labels: cla: yes

#4810 tfjs-node: add 2.0 api
  tfjs-node/binding.gyp
  tfjs-node/binding/tfjs_backend.cc
  tfjs-node/scripts/deps-constants.js
  tfjs-node/src/run_tests.ts
Labels: cla: yes

#4826 Added tan.cc tan.ts file
  tfjs-backend-wasm/src/cc/BUILD
  tfjs-backend-wasm/src/cc/kernels/Tan.cc
  tfjs-backend-wasm/src/kernels/Tan.ts
  tfjs-backend-wasm/src/register_all_kernels.ts
  tfjs-backend-wasm/src/setup_test.ts
Labels: cla: yes

#4916 Address mutability edge case in tf.Tensor docs
  tfjs-core/src/tensor.ts
Labels: cla: yes

#4925 [wasm] Add iOS 11 workaround for Tan
  tfjs-backend-wasm/src/cc/BUILD
  tfjs-backend-wasm/src/cc/kernels/Tan.cc
  tfjs-backend-wasm/src/cc/sin_cos_workaround.cc
  tfjs-backend-wasm/src/cc/sin_cos_workaround.h
Labels: cla: yes

#4909 improve perf of packed depthwise conv2d
  tfjs-backend-webgl/src/conv_packed_gpu_depthwise.ts
  tfjs-backend-webgl/src/flags_webgl.ts
Labels: cla: yes

#4911 enable pack depthwise conv2d flag
  e2e/benchmarks/benchmark_util.js
  e2e/benchmarks/local-benchmark/index.html
  e2e/benchmarks/local-benchmark/index.js
Labels: cla: yes

#4926 Update monorepo to 3.4.0.
  tfjs-backend-cpu/package.json
  tfjs-backend-cpu/src/version.ts
  tfjs-backend-wasm/package.json
  tfjs-backend-wasm/src/version.ts
  tfjs-backend-webgl/package.json
  tfjs-backend-webgl/src/version.ts
  tfjs-converter/package.json
  tfjs-converter/python/tensorflowjs/version.py
  tfjs-converter/src/version.ts
  tfjs-core/package.json
  tfjs-core/src/version.ts
  tfjs-data/package.json
  tfjs-data/src/version.ts
  tfjs-layers/package.json
  tfjs-layers/src/version.ts
  tfjs-node-gpu/package.json
  tfjs-node/package.json
  tfjs-node/src/version.ts
  tfjs/package.json
  tfjs/src/version.ts
Labels: INTERNAL, cla: yes

#4924 [webgpu] Add support for Range
  tfjs-backend-webgpu/src/kernel_utils/shared.ts
  tfjs-backend-webgpu/src/kernels/Range.ts
  tfjs-backend-webgpu/src/register_all_kernels.ts
  tfjs-backend-webgpu/src/setup_test.ts
Labels: cla: yes

#4922 [webgpu] Add basic implementation of einsum
  tfjs-backend-webgpu/src/kernels/Einsum.ts
  tfjs-backend-webgpu/src/register_all_kernels.ts
  tfjs-backend-webgpu/src/setup_test.ts
Labels: cla: yes

#4931 Update lockfiles branch tfjs_3.4.0_lockfiles lock files.
  tfjs-backend-cpu/yarn.lock
  tfjs-backend-wasm/yarn.lock
  tfjs-backend-webgl/yarn.lock
  tfjs-converter/yarn.lock
  tfjs-data/yarn.lock
  tfjs-layers/yarn.lock
  tfjs-node-gpu/yarn.lock
  tfjs-node/yarn.lock
  tfjs/yarn.lock
Labels: INTERNAL, cla: yes

#4928 [webgl]Fix tile rank 6.
  tfjs-backend-webgl/src/kernels/Tile.ts
Labels: cla: yes

#4920 [webgl]Remove cpu backend.
  tfjs-backend-webgl/src/backend_webgl.ts
Labels: cla: yes

#4929 e2e: Put profileMemoryAndKernelTime after measureAveragePredictTime
  e2e/benchmarks/benchmark_util.js
  e2e/benchmarks/local-benchmark/index.html
  e2e/benchmarks/local-benchmark/index.js
Labels: cla: yes

#4938 Add missing headings to core operations docs
  tfjs-core/src/ops/diag.ts
  tfjs-core/src/ops/rand.ts
Labels: cla: yes

#4940 [webgl] Allow Concat to run on CPU for small tensors
  tfjs-backend-webgl/src/kernels/Concat_impl.ts
Labels: cla: yes

#4321 [core] Add support for explicit padding for depthwiseConv.
  tfjs-backend-cpu/src/kernels/DepthwiseConv2dNative.ts
  tfjs-core/src/kernel_names.ts
  tfjs-core/src/ops/depthwise_conv2d.ts
  tfjs-core/src/ops/depthwise_conv2d_native_backprop_filter.ts
  tfjs-core/src/ops/depthwise_conv2d_native_backprop_input.ts
  tfjs-core/src/ops/depthwise_conv2d_test.ts
  tfjs-node/src/kernels/DepthwiseConv2dNative.ts
Labels: cla: no

#4941 Add bert text classifier tutorial to gallery.
  GALLERY.md
Labels: cla: yes

#4951 fix nightly failure for webgl concat and pack ops
  tfjs-backend-webgl/src/flags_webgl.ts
  tfjs-backend-webgl/src/kernels/Concat_impl.ts
Labels: cla: yes

#4819 [webgpu] Use uniform instead of constant for shape
  tfjs-backend-webgpu/src/backend_webgpu.ts
  tfjs-backend-webgpu/src/backend_webgpu_test.ts
  tfjs-backend-webgpu/src/kernel_utils/reduce.ts
  tfjs-backend-webgpu/src/kernels/ArgMax.ts
  tfjs-backend-webgpu/src/kernels/ArgMin.ts
  tfjs-backend-webgpu/src/kernels/AvgPool.ts
  tfjs-backend-webgpu/src/kernels/BatchMatMul_impl.ts
  tfjs-backend-webgpu/src/kernels/Conv2D.ts
  tfjs-backend-webgpu/src/kernels/DepthwiseConv2dNative.ts
  tfjs-backend-webgpu/src/kernels/Fill.ts
  tfjs-backend-webgpu/src/kernels/FromPixelsImageBitmap.ts
  tfjs-backend-webgpu/src/kernels/FromPixels_utils/from_pixels_webgpu.ts
  tfjs-backend-webgpu/src/kernels/FusedConv2D.ts
  tfjs-backend-webgpu/src/kernels/FusedDepthwiseConv2D.ts
  tfjs-backend-webgpu/src/kernels/MaxPool.ts
  tfjs-backend-webgpu/src/kernels/PadV2.ts
  tfjs-backend-webgpu/src/kernels/addn_packed_webgpu.ts
  tfjs-backend-webgpu/src/kernels/argminmax_webgpu.ts
  tfjs-backend-webgpu/src/kernels/batchnorm_webgpu.ts
  tfjs-backend-webgpu/src/kernels/binary_op_complex_webgpu.ts
  tfjs-backend-webgpu/src/kernels/binary_op_shared_webgpu.ts
  tfjs-backend-webgpu/src/kernels/binary_op_vec4_webgpu.ts
  tfjs-backend-webgpu/src/kernels/binary_op_webgpu.ts
  tfjs-backend-webgpu/src/kernels/clip_webgpu.ts
  tfjs-backend-webgpu/src/kernels/concat_webgpu.ts
  tfjs-backend-webgpu/src/kernels/conv2d_mm_vec4_webgpu.ts
  tfjs-backend-webgpu/src/kernels/conv2d_mm_webgpu.ts
  tfjs-backend-webgpu/src/kernels/conv2d_naive_webgpu.ts
  tfjs-backend-webgpu/src/kernels/crop_and_resize_webgpu.ts
  tfjs-backend-webgpu/src/kernels/depthwise_conv2d_webgpu.ts
  tfjs-backend-webgpu/src/kernels/fill_webgpu.ts
  tfjs-backend-webgpu/src/kernels/gather_webgpu.ts
  tfjs-backend-webgpu/src/kernels/im2col_webgpu.ts
  tfjs-backend-webgpu/src/kernels/matmul_packed_vec4_webgpu.ts
  tfjs-backend-webgpu/src/kernels/matmul_packed_webgpu.ts
  tfjs-backend-webgpu/src/kernels/mirror_pad_webgpu.ts
  tfjs-backend-webgpu/src/kernels/pad_webgpu.ts
  tfjs-backend-webgpu/src/kernels/pool2d_webgpu.ts
  tfjs-backend-webgpu/src/kernels/pool_filtersizeone_webgpu.ts
  tfjs-backend-webgpu/src/kernels/reduce_webgpu.ts
  tfjs-backend-webgpu/src/kernels/resize_bilinear_webgpu.ts
  tfjs-backend-webgpu/src/kernels/select_webgpu.ts
  tfjs-backend-webgpu/src/kernels/slice_webgpu.ts
  tfjs-backend-webgpu/src/kernels/transpose_shared_webgpu.ts
  tfjs-backend-webgpu/src/kernels/transpose_webgpu.ts
  tfjs-backend-webgpu/src/kernels/unary_op_webgpu.ts
  tfjs-backend-webgpu/src/kernels/webgpu_program.ts
  tfjs-backend-webgpu/src/shader_preprocessor.ts
Labels: cla: yes

#4950 Feat/add mish
  tfjs-layers/src/activations.ts
  tfjs-layers/src/activations_test.ts
Labels: cla: yes

#4960 add mish in config
  tfjs-layers/src/keras_format/activation_config.ts
Labels: cla: yes

#4956 Add Kernel SparseReshape for CPU and WebGL backend
  tfjs-backend-cpu/src/kernels/SparseReshape.ts
  tfjs-backend-cpu/src/kernels/SparseReshape_impl.ts
  tfjs-backend-cpu/src/register_all_kernels.ts
  tfjs-backend-cpu/src/shared.ts
  tfjs-backend-webgl/src/kernel_utils/shared.ts
  tfjs-backend-webgl/src/kernels/SparseReshape.ts
  tfjs-backend-webgl/src/register_all_kernels.ts
  tfjs-converter/metadata/kernel2op.json
  tfjs-core/src/kernel_names.ts
  tfjs-core/src/ops/ops.ts
  tfjs-core/src/ops/sparse/sparse_reshape.ts
  tfjs-core/src/ops/sparse/sparse_reshape_test.ts
  tfjs-core/src/tests.ts
  tfjs-node/src/run_tests.ts
Labels: cla: yes

#4963 added support for sparseReshape op for converter
  tfjs-converter/metadata/kernel2op.json
  tfjs-converter/python/tensorflowjs/op_list/sparse.json
  tfjs-converter/src/operations/executors/sparse_executor.ts
  tfjs-converter/src/operations/executors/sparse_executor_test.ts
  tfjs-converter/src/operations/op_list/sparse.ts
  tfjs-converter/src/operations/op_mapper_schema.ts
  tfjs-converter/src/operations/operation_executor.ts
  tfjs-converter/src/operations/types.ts
Labels: cla: yes

#4958 [webgpu] Use uniform for program batchNorm, clip, im2col
  tfjs-backend-webgpu/src/kernels/ClipByValue.ts
  tfjs-backend-webgpu/src/kernels/Conv2D_impl.ts
  tfjs-backend-webgpu/src/kernels/FromPixels_utils/from_pixels_webgpu.ts
  tfjs-backend-webgpu/src/kernels/FusedBatchNorm.ts
  tfjs-backend-webgpu/src/kernels/batchnorm_webgpu.ts
  tfjs-backend-webgpu/src/kernels/clip_vec4_webgpu.ts
  tfjs-backend-webgpu/src/kernels/clip_webgpu.ts
  tfjs-backend-webgpu/src/kernels/im2col_webgpu.ts
  tfjs-backend-webgpu/src/shader_preprocessor.ts
Labels: cla: yes

#4957 [wasm] Fix wasm backend not starting any threads
  tfjs-backend-wasm/scripts/build-wasm.sh
  tfjs-backend-wasm/src/backend_wasm.ts
  tfjs-backend-wasm/src/cc/BUILD
  tfjs-backend-wasm/src/index_test.ts
  tfjs-backend-wasm/wasm-out/tfjs-backend-wasm-threaded-simd.d.ts
Labels: cla: yes

#4968 Update monorepo to 3.5.0.
  tfjs-backend-cpu/package.json
  tfjs-backend-cpu/src/version.ts
  tfjs-backend-wasm/package.json
  tfjs-backend-wasm/src/version.ts
  tfjs-backend-webgl/package.json
  tfjs-backend-webgl/src/version.ts
  tfjs-converter/package.json
  tfjs-converter/python/tensorflowjs/version.py
  tfjs-converter/src/version.ts
  tfjs-core/package.json
  tfjs-core/src/version.ts
  tfjs-data/package.json
  tfjs-data/src/version.ts
  tfjs-layers/package.json
  tfjs-layers/src/version.ts
  tfjs-node-gpu/package.json
  tfjs-node/package.json
  tfjs-node/src/version.ts
  tfjs/package.json
  tfjs/src/version.ts
Labels: INTERNAL, cla: yes

#4969 Remove Emscripten toolchain setup from release script
  scripts/publish-npm.ts
Labels: cla: yes

#4970 Update lockfiles branch tfjs_3.5.0_lockfiles lock files.
  tfjs-backend-cpu/yarn.lock
  tfjs-backend-wasm/yarn.lock
  tfjs-backend-webgl/yarn.lock
  tfjs-converter/yarn.lock
  tfjs-data/yarn.lock
  tfjs-layers/yarn.lock
  tfjs-node-gpu/yarn.lock
  tfjs-node/yarn.lock
  tfjs/yarn.lock
Labels: INTERNAL, cla: yes

#4973 Upgrade tfjs deps to 3.5.0
  tfjs-vis/demos/api/package.json
  tfjs-vis/demos/api/yarn.lock
  tfjs-vis/demos/mnist/package.json
  tfjs-vis/demos/mnist/yarn.lock
  tfjs-vis/demos/mnist_internals/package.json
  tfjs-vis/demos/mnist_internals/yarn.lock
  tfjs-vis/package.json
  tfjs-vis/yarn.lock
Labels: cla: yes

#4974 Update tfjs-vis to 1.5.1.
  tfjs-vis/package.json
  tfjs-vis/src/version.ts
Labels: INTERNAL, cla: yes

#4966 webgpu: Use uniforms for PadV2 paddings
  tfjs-backend-webgpu/src/kernels/PadV2.ts
  tfjs-backend-webgpu/src/kernels/pad_webgpu.ts
Labels: cla: yes

#4954 depthwise packed perf: reduce texel read for dilation of 2
  tfjs-backend-webgl/src/conv_packed_gpu_depthwise.ts
  tfjs-backend-webgl/src/flags_webgl.ts
  tfjs-backend-webgl/src/flags_webgl_test.ts
  tfjs-backend-webgl/src/gpgpu_context.ts
Labels: cla: yes

#4906 Create threshold.ts
  tfjs-core/src/ops/image/threshold.ts
  tfjs-core/src/ops/image/threshold_test.ts
  tfjs-core/src/ops/ops.ts
  tfjs-core/src/tests.ts
Labels: cla: yes

#4977 generate wechat miniprogram compatible wasm js file
  tfjs-backend-wasm/rollup.config.js
  tfjs-backend-wasm/scripts/build-npm.sh
Labels: cla: yes

#4980 [wasm] Add transform op.
  tfjs-backend-wasm/src/cc/BUILD
  tfjs-backend-wasm/src/cc/kernels/Transform.cc
  tfjs-backend-wasm/src/kernels/Transform.ts
  tfjs-backend-wasm/src/register_all_kernels.ts
  tfjs-backend-wasm/src/setup_test.ts
  tfjs-core/src/ops/image/transform_test.ts
Labels: cla: yes

#4981 fixed wasm conv2d backprop error when strides is greater than 1
  tfjs-backend-wasm/src/cc/kernels/Conv2DBackpropInput.cc
  tfjs-backend-wasm/src/setup_test.ts
  tfjs-core/src/ops/conv2d_transpose_test.ts
Labels: cla: yes

#4986 fix nightly failure
  tfjs-core/src/ops/conv2d_transpose_test.ts
Labels: cla: yes

#4985 added packed version of resize nearest neighbor kernel
  tfjs-backend-webgl/src/kernels/ResizeNearestNeighbor.ts
  tfjs-backend-webgl/src/resize_nearest_neighbor_packed_gpu.ts
Labels: cla: yes

#4983 Adding a blog post
  GALLERY.md
Labels: cla: yes

#4991 add v8 to the supported napi versions
  tfjs-node-gpu/package.json
  tfjs-node/package.json
Labels: cla: yes

#4945 Update webgpu to 0.0.1_alpha.1
  tfjs-backend-webgpu/package.json
  tfjs-backend-webgpu/yarn.lock
Labels: cla: yes

#4967 webgpu: Use outShapeStrides in more places
  tfjs-backend-webgpu/src/shader_preprocessor.ts
Labels: cla: yes

#4996 Upgrade webgpu to 0.0.1-alpha.5
  tfjs-backend-webgpu/package.json
Labels: cla: yes

#4997 [Converter] removed h5py direct deps to rely on TF
  tfjs-converter/python/requirements.txt
Labels: cla: yes

#4992 Add Kernel SparseFillEmptyRows for CPU and WebGL backend
  tfjs-backend-cpu/src/kernels/SparseFillEmptyRows.ts
  tfjs-backend-cpu/src/kernels/SparseFillEmptyRows_impl.ts
  tfjs-backend-cpu/src/register_all_kernels.ts
  tfjs-backend-cpu/src/shared.ts
  tfjs-backend-webgl/src/kernel_utils/shared.ts
  tfjs-backend-webgl/src/kernels/SparseFillEmptyRows.ts
  tfjs-backend-webgl/src/register_all_kernels.ts
  tfjs-core/src/kernel_names.ts
  tfjs-core/src/ops/ops.ts
  tfjs-core/src/ops/sparse/sparse_fill_empty_rows.ts
  tfjs-core/src/ops/sparse/sparse_fill_empty_rows_test.ts
  tfjs-core/src/tests.ts
  tfjs-node/src/run_tests.ts
Labels: cla: yes

#4999 Make the package work with webworker, and use a better default for numThreads.
  tfjs-tflite/demo/src/script.ts
  tfjs-tflite/package.json
  tfjs-tflite/scripts/download-tflite-web-api.sh
  tfjs-tflite/src/index.ts
  tfjs-tflite/src/tflite_model.ts
  tfjs-tflite/src/tflite_task_library_client/bert_nl_classifier.ts
  tfjs-tflite/src/tflite_task_library_client/bert_qa.ts
  tfjs-tflite/src/tflite_task_library_client/common.ts
  tfjs-tflite/src/tflite_task_library_client/image_classifier.ts
  tfjs-tflite/src/tflite_task_library_client/image_segmenter.ts
  tfjs-tflite/src/tflite_task_library_client/nl_classifier.ts
  tfjs-tflite/src/tflite_task_library_client/object_detector.ts
  tfjs-tflite/src/tflite_web_api_client_test.ts
  tfjs-tflite/src/types/bert_nl_classifier.ts
  tfjs-tflite/src/types/bert_qa.ts
  tfjs-tflite/src/types/common.ts
  tfjs-tflite/src/types/image_classifier.ts
  tfjs-tflite/src/types/image_segmenter.ts
  tfjs-tflite/src/types/nl_classifier.ts
  tfjs-tflite/src/types/object_detector.ts
  tfjs-tflite/src/types/tflite_web_api.ts
  tfjs-tflite/src/types/tflite_web_model_runner.ts
Labels: cla: yes

#5008 Fix tile rank > 6
  tfjs-backend-webgl/src/kernels/Tile.ts
  tfjs-core/src/ops/tile_test.ts
Labels: cla: yes

#5009 Update monorepo to 3.6.0.
  tfjs-backend-cpu/package.json
  tfjs-backend-cpu/src/version.ts
  tfjs-backend-wasm/package.json
  tfjs-backend-wasm/src/version.ts
  tfjs-backend-webgl/package.json
  tfjs-backend-webgl/src/version.ts
  tfjs-converter/package.json
  tfjs-converter/python/tensorflowjs/version.py
  tfjs-converter/src/version.ts
  tfjs-core/package.json
  tfjs-core/src/version.ts
  tfjs-data/package.json
  tfjs-data/src/version.ts
  tfjs-layers/package.json
  tfjs-layers/src/version.ts
  tfjs-node-gpu/package.json
  tfjs-node/package.json
  tfjs-node/src/version.ts
  tfjs/package.json
  tfjs/src/version.ts
Labels: INTERNAL, cla: yes

#5010 Update lockfiles branch tfjs_3.6.0_lockfiles lock files.
  tfjs-backend-cpu/yarn.lock
  tfjs-backend-wasm/yarn.lock
  tfjs-backend-webgl/yarn.lock
  tfjs-converter/yarn.lock
  tfjs-data/yarn.lock
  tfjs-layers/yarn.lock
  tfjs-node-gpu/yarn.lock
  tfjs-node/yarn.lock
  tfjs/yarn.lock
Labels: INTERNAL, cla: yes

#5011 upgrade tfjs-automl to 1.1.0
  tfjs-automl/package.json
  tfjs-automl/src/version.ts
Labels: cla: yes

#5006 Upgrade rules_nodejs to 3.4.1 and karma to 6.3.2
  WORKSPACE
  package.json
  tfjs-backend-cpu/BUILD.bazel
  tfjs-core/BUILD.bazel
  yarn.lock
Labels: cla: yes

#5005 Add support for SparseFillEmptyRows conversion
  tfjs-converter/metadata/kernel2op.json
  tfjs-converter/python/tensorflowjs/op_list/sparse.json
  tfjs-converter/src/operations/executors/sparse_executor.ts
  tfjs-converter/src/operations/executors/sparse_executor_test.ts
  tfjs-converter/src/operations/op_list/sparse.ts
Labels: cla: yes

#5015 Update tfjs-node, tfjs-node-gpu to 3.6.1, 3.6.1.
  tfjs-node-gpu/package.json
  tfjs-node/binding/tfjs_backend.cc
  tfjs-node/package.json
  tfjs-node/src/version.ts
Labels: INTERNAL, cla: no

#5014 Update contribution and development docs
  CONTRIBUTING.md
  CONTRIBUTING_MISSING_OP.md
  DEVELOPMENT.md
Labels: cla: yes
