Repository tensorflow/tfjs, pull requests merged in 2021-11, with the labels that each got.

#5802 [converter] fix tensorflow-estimator version to 2.6.0
  tfjs-converter/python/BUILD
  tfjs-converter/python/requirements.txt
Labels: cla: yes

#5796 [webgl]Refactor GPGPUBinary.
  tfjs-backend-webgl/src/gpgpu_context.ts
  tfjs-backend-webgl/src/gpgpu_context_test.ts
  tfjs-backend-webgl/src/gpgpu_math.ts
Labels: cla: yes

#5801 [converter] Add license to BUILD file
  tfjs-converter/python/tensorflowjs/op_list/BUILD
Labels: cla: yes

#5707 webgpu: Fix the potential error using atomicCompareExchangeWeak
  tfjs-backend-webgpu/src/kernels/scatter_optimized_webgpu.ts
Labels: cla: yes

#5792 [webgpu] reshape stridedSlice result
  tfjs-backend-webgpu/src/kernels/StridedSlice.ts
Labels: cla: yes

#5809 [converter] lock keras version to 2.6.0
  tfjs-converter/python/BUILD
  tfjs-converter/python/requirements.txt
Labels: cla: yes

#5804 [react-native] Add "rotation" property to TensorCamera to allow users to rotate camera view and internal texture
  tfjs-react-native/src/camera/camera.ts
  tfjs-react-native/src/camera/camera_stream.tsx
  tfjs-react-native/src/camera/camera_webgl_util.ts
  tfjs-react-native/src/camera/draw_texture_program_info.ts
  tfjs-react-native/src/camera/types.ts
Labels: cla: yes

#5810 Update tfjs-react-native to 0.8.0.
  tfjs-react-native/package.json
  tfjs-react-native/src/version.ts
  tfjs-react-native/yarn.lock
Labels: cla: yes, INTERNAL

#5785 webgpu: Refactor some utilities
  tfjs-backend-webgpu/src/backend_webgpu.ts
  tfjs-backend-webgpu/src/backend_webgpu_test.ts
  tfjs-backend-webgpu/src/kernels/FromPixels_utils/from_pixels_webgpu.ts
  tfjs-backend-webgpu/src/kernels/ScatterNd.ts
  tfjs-backend-webgpu/src/kernels/addn_packed_webgpu.ts
  tfjs-backend-webgpu/src/kernels/argminmax_webgpu.ts
  tfjs-backend-webgpu/src/kernels/batchnorm_webgpu.ts
  tfjs-backend-webgpu/src/kernels/binary_op_complex_webgpu.ts
  tfjs-backend-webgpu/src/kernels/binary_op_shared_webgpu.ts
  tfjs-backend-webgpu/src/kernels/binary_op_vec4_webgpu.ts
  tfjs-backend-webgpu/src/kernels/binary_op_webgpu.ts
  tfjs-backend-webgpu/src/kernels/clip_vec4_webgpu.ts
  tfjs-backend-webgpu/src/kernels/clip_webgpu.ts
  tfjs-backend-webgpu/src/kernels/concat_webgpu.ts
  tfjs-backend-webgpu/src/kernels/conv2d_naive_webgpu.ts
  tfjs-backend-webgpu/src/kernels/conv_backprop_webgpu.ts
  tfjs-backend-webgpu/src/kernels/crop_and_resize_webgpu.ts
  tfjs-backend-webgpu/src/kernels/depth_to_space_webgpu.ts
  tfjs-backend-webgpu/src/kernels/depthwise_conv2d_3x3_webgpu.ts
  tfjs-backend-webgpu/src/kernels/depthwise_conv2d_webgpu.ts
  tfjs-backend-webgpu/src/kernels/fill_webgpu.ts
  tfjs-backend-webgpu/src/kernels/flip_left_right_webgpu.ts
  tfjs-backend-webgpu/src/kernels/gather_nd_webgpu.ts
  tfjs-backend-webgpu/src/kernels/gather_webgpu.ts
  tfjs-backend-webgpu/src/kernels/im2col_webgpu.ts
  tfjs-backend-webgpu/src/kernels/matmul_packed_vec4_webgpu.ts
  tfjs-backend-webgpu/src/kernels/matmul_packed_webgpu.ts
  tfjs-backend-webgpu/src/kernels/matmul_reduce.ts
  tfjs-backend-webgpu/src/kernels/matmul_small_output_size_webgpu.ts
  tfjs-backend-webgpu/src/kernels/mirror_pad_webgpu.ts
  tfjs-backend-webgpu/src/kernels/pad_webgpu.ts
  tfjs-backend-webgpu/src/kernels/pool2d_webgpu.ts
  tfjs-backend-webgpu/src/kernels/pool_filtersizeone_webgpu.ts
  tfjs-backend-webgpu/src/kernels/reduce_webgpu.ts
  tfjs-backend-webgpu/src/kernels/resize_bilinear_webgpu.ts
  tfjs-backend-webgpu/src/kernels/resize_nearest_neighbor_webgpu.ts
  tfjs-backend-webgpu/src/kernels/rotate_webgpu.ts
  tfjs-backend-webgpu/src/kernels/scatter_optimized_webgpu.ts
  tfjs-backend-webgpu/src/kernels/scatter_webgpu.ts
  tfjs-backend-webgpu/src/kernels/select_webgpu.ts
  tfjs-backend-webgpu/src/kernels/slice_webgpu.ts
  tfjs-backend-webgpu/src/kernels/strided_slice_webgpu.ts
  tfjs-backend-webgpu/src/kernels/tile_webgpu.ts
  tfjs-backend-webgpu/src/kernels/top_k_webgpu.ts
  tfjs-backend-webgpu/src/kernels/transform_webgpu.ts
  tfjs-backend-webgpu/src/kernels/transpose_shared_webgpu.ts
  tfjs-backend-webgpu/src/kernels/transpose_webgpu.ts
  tfjs-backend-webgpu/src/kernels/unary_op_webgpu.ts
  tfjs-backend-webgpu/src/kernels/webgpu_program.ts
  tfjs-backend-webgpu/src/shader_preprocessor.ts
Labels: cla: yes

#5818 [tfjs-node]: upgrade TF to 2.7.0
  tfjs-node/scripts/deps-constants.js
Labels: cla: yes

#5814 [converter] removed TF version lock.
  tfjs-converter/python/BUILD
  tfjs-converter/python/requirements.txt
Labels: cla: yes

#5817 [converter] added wizard deps to the package
  tfjs-converter/python/tensorflowjs/converters/BUILD
Labels: cla: yes

#5825 add check for valid gl context when reading isContextLost
  tfjs-backend-webgl/src/canvas_util.ts
Labels: cla: yes

#5362 Build tfjs-backend-webgpu with Bazel
  e2e/scripts/publish-tfjs-ci.sh
  link-package/package.json
  package.json
  scripts/package_dependencies.json
  scripts/publish-npm.ts
  tfjs-backend-webgpu/BUILD.bazel
  tfjs-backend-webgpu/cloudbuild.yml
  tfjs-backend-webgpu/package.json
  tfjs-backend-webgpu/scripts/test-ci.sh
  tfjs-backend-webgpu/src/BUILD.bazel
  tfjs-backend-webgpu/src/backend_webgpu.ts
  tfjs-backend-webgpu/src/backend_webgpu_test.ts
  tfjs-backend-webgpu/src/backend_webgpu_test_registry.ts
  tfjs-backend-webgpu/src/setup_test.ts
  tfjs-backend-webgpu/tsconfig.json
  tfjs-backend-webgpu/tsconfig.test.json
  tfjs-backend-webgpu/tslint.json
  tfjs-backend-webgpu/yarn.lock
  tools/karma_template.conf.js
  tools/tfjs_web_test.bzl
  tsconfig_ts_library.json
  tsconfig_tslint.json
  yarn.lock
Labels: cla: yes, bazel

#5774 webgpu: modify ArgMinMaxProgram to flat dispatch layout
  tfjs-backend-webgpu/src/kernels/ArgMax.ts
  tfjs-backend-webgpu/src/kernels/ArgMin.ts
  tfjs-backend-webgpu/src/kernels/argminmax_webgpu.ts
Labels: cla: yes

#5858 [tfjs-converter] support float16 data type in conversion and cast op
  tfjs-converter/python/tensorflowjs/converters/tf_saved_model_conversion_v2.py
  tfjs-converter/python/tensorflowjs/converters/tf_saved_model_conversion_v2_test.py
  tfjs-converter/python/tensorflowjs/write_weights.py
  tfjs-converter/python/tensorflowjs/write_weights_test.py
  tfjs-converter/src/data/compiled_api.ts
  tfjs-converter/src/operations/operation_mapper.ts
  tfjs-converter/src/operations/operation_mapper_test.ts
  tfjs-converter/tools/compiled_api.d.ts
Labels: cla: yes

#5855 webgpu: Fix the deprecated intrinsic warning
  tfjs-backend-webgpu/src/kernels/scatter_optimized_webgpu.ts
Labels: cla: yes

#5830 webgpu: refactor and optimize reduce kernel
  tfjs-backend-webgpu/src/kernel_utils/reduce.ts
  tfjs-backend-webgpu/src/kernels/reduce_webgpu.ts
Labels: cla: yes

#5862 [webgl] replace texImage2D with texStorage2D + texSubImage2D
  tfjs-backend-webgl/src/backend_webgl.ts
  tfjs-backend-webgl/src/backend_webgl_test.ts
  tfjs-backend-webgl/src/gpgpu_context_test.ts
  tfjs-backend-webgl/src/gpgpu_util.ts
  tfjs-backend-webgl/src/tex_util.ts
  tfjs-backend-webgl/src/texture_manager.ts
Labels: cla: yes

#5865 Add doccomment for fromPixels inconsistent result.
  tfjs-core/src/ops/browser.ts
Labels: cla: yes

#5874 [wasm] Fix incorrect check for existance of process
  tfjs-backend-wasm/src/cc/post.js
  tfjs-backend-wasm/src/cc/pre.js
  tfjs-backend-wasm/src/index_test.ts
Labels: cla: yes

#5873 [wasm]Supports broadcast for all binary ops.
  tfjs-backend-wasm/src/cc/BUILD
  tfjs-backend-wasm/src/cc/binary.cc
  tfjs-backend-wasm/src/cc/binary.h
  tfjs-backend-wasm/src/cc/kernels/Add.cc
  tfjs-backend-wasm/src/cc/kernels/Equal.cc
  tfjs-backend-wasm/src/cc/kernels/FloorDiv.cc
  tfjs-backend-wasm/src/cc/kernels/Greater.cc
  tfjs-backend-wasm/src/cc/kernels/GreaterEqual.cc
  tfjs-backend-wasm/src/cc/kernels/Less.cc
  tfjs-backend-wasm/src/cc/kernels/LessEqual.cc
  tfjs-backend-wasm/src/cc/kernels/LogicalAnd.cc
  tfjs-backend-wasm/src/cc/kernels/Maximum.cc
  tfjs-backend-wasm/src/cc/kernels/Minimum.cc
  tfjs-backend-wasm/src/cc/kernels/Multiply.cc
  tfjs-backend-wasm/src/cc/kernels/NotEqual.cc
  tfjs-backend-wasm/src/cc/kernels/Pow.cc
  tfjs-backend-wasm/src/cc/kernels/RealDiv.cc
  tfjs-backend-wasm/src/cc/kernels/SquaredDifference.cc
  tfjs-backend-wasm/src/cc/kernels/Sub.cc
  tfjs-backend-wasm/src/cc/util.cc
  tfjs-backend-wasm/src/cc/util.h
  tfjs-backend-wasm/src/kernels/binary_kernel.ts
  tfjs-backend-wasm/src/setup_test.ts
  tfjs-core/src/ops/binary_ops_test.ts
  tfjs-core/src/ops/floordiv_test.ts
Labels: cla: yes

#5827 [webgpu] Optimize shader key of concat and resizeBilinear
  tfjs-backend-webgpu/src/kernels/Concat_impl.ts
  tfjs-backend-webgpu/src/kernels/ResizeBilinear.ts
  tfjs-backend-webgpu/src/kernels/ResizeNearestNeighbor.ts
  tfjs-backend-webgpu/src/kernels/concat_webgpu.ts
  tfjs-backend-webgpu/src/kernels/resize_bilinear_webgpu.ts
  tfjs-backend-webgpu/src/kernels/resize_nearest_neighbor_webgpu.ts
Labels: cla: yes

#5835 webgl: Support uniforms for pack/unpack programs
  tfjs-backend-webgl/src/pack_gpu.ts
  tfjs-backend-webgl/src/unpack_gpu.ts
Labels: cla: yes

#5770 Update package.json to include the repository
  tfjs-backend-wasm/package.json
  tfjs-data/package.json
  tfjs-layers/package.json
  tfjs-react-native/package.json
Labels: cla: yes

#5887 Add and update package.json repository metadata
  tfjs-automl/package.json
  tfjs-backend-cpu/package.json
  tfjs-backend-nodegl/package.json
  tfjs-backend-webgpu/package.json
  tfjs-converter/package.json
  tfjs-core/package.json
  tfjs-inference/package.json
  tfjs-node-gpu/package.json
  tfjs-node/package.json
  tfjs-node/scripts/ensure-cpu-gpu-packages-align.js
  tfjs-tflite/package.json
  tfjs-vis/package.json
Labels: cla: yes

#5806 [webgpu] Calculating coords use i32 to avoid precision issue
  tfjs-backend-webgpu/src/kernels/precision_webgpu_test.ts
  tfjs-backend-webgpu/src/shader_preprocessor.ts
Labels: cla: yes

#5848 webgpu: simplify shader key of depthwise_conv2d
  tfjs-backend-webgpu/src/kernels/DepthwiseConv2dNative.ts
  tfjs-backend-webgpu/src/kernels/FusedDepthwiseConv2D.ts
  tfjs-backend-webgpu/src/kernels/depthwise_conv2d_webgpu.ts
Labels: cla: yes

#5723 Add SparseReshape kernel to WASM backend
  tfjs-backend-cpu/src/kernels/SparseReshape_impl.ts
  tfjs-backend-wasm/src/cc/BUILD
  tfjs-backend-wasm/src/cc/kernels/SparseReshape.cc
  tfjs-backend-wasm/src/kernels/SparseReshape.ts
  tfjs-backend-wasm/src/register_all_kernels.ts
  tfjs-backend-wasm/src/setup_test.ts
  tfjs-core/src/backends/backend_util.ts
  tfjs-core/src/ops/sparse/sparse_reshape.ts
  tfjs-core/src/ops/sparse/sparse_reshape_test.ts
  tfjs-core/src/ops/sparse/sparse_reshape_util.ts
Labels: cla: yes

#5747 Add SparseFillEmptyRows kernel to WASM
  tfjs-backend-cpu/src/kernels/SparseFillEmptyRows_impl.ts
  tfjs-backend-wasm/src/cc/BUILD
  tfjs-backend-wasm/src/cc/kernels/SparseFillEmptyRows.cc
  tfjs-backend-wasm/src/kernels/SparseFillEmptyRows.ts
  tfjs-backend-wasm/src/register_all_kernels.ts
  tfjs-backend-wasm/src/setup_test.ts
  tfjs-core/src/backends/backend_util.ts
  tfjs-core/src/ops/sparse/sparse_fill_empty_rows.ts
  tfjs-core/src/ops/sparse/sparse_fill_empty_rows_test.ts
  tfjs-core/src/ops/sparse/sparse_fill_empty_rows_util.ts
Labels: cla: yes

#5849 Expose dimRoundingMode attribute of pool op
  tfjs-core/src/gradients/DepthwiseConv2dNative_grad.ts
  tfjs-core/src/ops/avg_pool.ts
  tfjs-core/src/ops/avg_pool_3d.ts
  tfjs-core/src/ops/avg_pool_3d_grad.ts
  tfjs-core/src/ops/avg_pool_3d_test.ts
  tfjs-core/src/ops/avg_pool_test.ts
  tfjs-core/src/ops/conv1d.ts
  tfjs-core/src/ops/conv1d_test.ts
  tfjs-core/src/ops/conv2d.ts
  tfjs-core/src/ops/conv2d_backprop_filter.ts
  tfjs-core/src/ops/conv2d_backprop_input.ts
  tfjs-core/src/ops/conv2d_test.ts
  tfjs-core/src/ops/conv2d_transpose_test.ts
  tfjs-core/src/ops/conv_util.ts
  tfjs-core/src/ops/depthwise_conv2d.ts
  tfjs-core/src/ops/depthwise_conv2d_test.ts
  tfjs-core/src/ops/fused/conv2d.ts
  tfjs-core/src/ops/fused/depthwise_conv2d.ts
  tfjs-core/src/ops/fused/fused_conv2d_test.ts
  tfjs-core/src/ops/max_pool.ts
  tfjs-core/src/ops/max_pool_3d.ts
  tfjs-core/src/ops/max_pool_3d_grad.ts
  tfjs-core/src/ops/max_pool_3d_test.ts
  tfjs-core/src/ops/max_pool_grad.ts
  tfjs-core/src/ops/max_pool_test.ts
  tfjs-core/src/ops/pool.ts
  tfjs-core/src/ops/pool_test.ts
  tfjs-core/src/public/chained_ops/pool.ts
  tfjs-node/src/run_tests.ts
Labels: cla: yes

#5739 Add SparseSegmentSum/Mean kernel to WASM backend
  tfjs-backend-cpu/src/kernels/SparseSegmentMean.ts
  tfjs-backend-cpu/src/kernels/SparseSegmentReduction_impl.ts
  tfjs-backend-cpu/src/kernels/SparseSegmentSum.ts
  tfjs-backend-wasm/src/backend_wasm.ts
  tfjs-backend-wasm/src/cc/BUILD
  tfjs-backend-wasm/src/cc/kernels/SparseSegmentReduction.cc
  tfjs-backend-wasm/src/kernels/SparseSegmentMean.ts
  tfjs-backend-wasm/src/kernels/SparseSegmentReduction.ts
  tfjs-backend-wasm/src/kernels/SparseSegmentSum.ts
  tfjs-backend-wasm/src/register_all_kernels.ts
  tfjs-backend-wasm/src/setup_test.ts
  tfjs-core/src/backends/backend_util.ts
  tfjs-core/src/ops/sparse/sparse_segment_mean.ts
  tfjs-core/src/ops/sparse/sparse_segment_mean_test.ts
  tfjs-core/src/ops/sparse/sparse_segment_reduction_util.ts
  tfjs-core/src/ops/sparse/sparse_segment_sum.ts
  tfjs-core/src/ops/sparse/sparse_segment_sum_test.ts
Labels: cla: yes
