Repository tensorflow/tfjs, pull requests merged in 2021-09, with the labels that each got.

#5552 Add wgsl support for FromPixels
  tfjs-backend-webgpu/package.json
  tfjs-backend-webgpu/src/backend_webgpu.ts
  tfjs-backend-webgpu/src/kernels/FromPixelsExternalImage.ts
  tfjs-backend-webgpu/src/kernels/FromPixels_utils/from_pixels_import_webgpu.ts
  tfjs-backend-webgpu/src/kernels/FromPixels_utils/from_pixels_webgpu.ts
  tfjs-backend-webgpu/src/shader_preprocessor_wgsl.ts
  tfjs-backend-webgpu/yarn.lock
Labels: cla: yes

#5527 [webgpu] Add conv2d/conv2dNaive/matmul/im2col WGSL support
  tfjs-backend-webgpu/src/kernels/BatchMatMul_impl.ts
  tfjs-backend-webgpu/src/kernels/Conv2D.ts
  tfjs-backend-webgpu/src/kernels/Conv2D_impl.ts
  tfjs-backend-webgpu/src/kernels/FusedConv2D.ts
  tfjs-backend-webgpu/src/kernels/activation_util.ts
  tfjs-backend-webgpu/src/kernels/conv2d_mm_webgpu.ts
  tfjs-backend-webgpu/src/kernels/conv2d_naive_webgpu.ts
  tfjs-backend-webgpu/src/kernels/im2col_webgpu.ts
  tfjs-backend-webgpu/src/kernels/matmul_packed_webgpu.ts
Labels: cla: yes

#5559 [webgpu] Fix wrongly used u32 of WGSL
  tfjs-backend-webgpu/src/kernels/conv2d_mm_vec4_webgpu.ts
  tfjs-backend-webgpu/src/shader_preprocessor_wgsl.ts
Labels: cla: yes

#5568 Fix typo in tf_saved_model_conversion_v2.py
  tfjs-converter/python/tensorflowjs/converters/tf_saved_model_conversion_v2.py
Labels: cla: yes

#5545 [tflite] Update README and fix demo
  link-package/package.json
  link-package/yarn.lock
  tfjs-tflite/README.md
  tfjs-tflite/demo/package.json
  tfjs-tflite/demo/src/script.ts
  tfjs-tflite/demo/yarn.lock
Labels: cla: yes

#5553 [webgpu] Add halfPixelCenters support for resizeBilinear op
  tfjs-backend-webgpu/src/kernels/ResizeBilinear.ts
  tfjs-backend-webgpu/src/kernels/resize_bilinear_webgpu.ts
  tfjs-backend-webgpu/src/setup_test.ts
Labels: cla: yes

#5580 [e2e] Add WEBGPU_USE_GLSL flag support
  e2e/benchmarks/benchmark_util.js
  e2e/benchmarks/local-benchmark/index.html
  e2e/benchmarks/local-benchmark/index.js
Labels: cla: yes

#5583 update docker and fixed test bundle size wasm task
  dockers/release-docker/Dockerfile
  tfjs-backend-wasm/scripts/test-bundle-size.js
Labels: cla: yes

#5592 [custom-bundle] fix custom bundle op file name issue
  tfjs/tools/custom_module/esm_module_provider_test.ts
  tfjs/tools/custom_module/util.ts
Labels: cla: yes

#5591 Add scripts to deploy benchmarks tool to firebase hosting
  .gitignore
  e2e/benchmarks/firebase_prod.json
  e2e/benchmarks/firebase_staging.json
  e2e/package.json
  e2e/scripts/deploy-benchmarks.sh
Labels: cla: yes

#5581 [tflite] Add README to npm package
  tfjs-tflite/BUILD.bazel
Labels: cla: yes

#5485 [webgl]Add BroadcastArgs to WebGL.
  tfjs-backend-webgl/src/kernels/BroadcastArgs.ts
  tfjs-backend-webgl/src/register_all_kernels.ts
  tfjs-backend-webgl/src/setup_test.ts
Labels: cla: yes

#5587 Hide importExternalTexture behind flag
  tfjs-backend-webgpu/src/flags_webgpu.ts
Labels: cla: yes

#5579 [webgpu] Use module constant as workgroup size in WGSL
  tfjs-backend-webgpu/src/kernels/FromPixels_utils/from_pixels_webgpu.ts
  tfjs-backend-webgpu/src/kernels/addn_packed_webgpu.ts
  tfjs-backend-webgpu/src/kernels/argminmax_webgpu.ts
  tfjs-backend-webgpu/src/kernels/batchnorm_webgpu.ts
  tfjs-backend-webgpu/src/kernels/binary_op_complex_webgpu.ts
  tfjs-backend-webgpu/src/kernels/binary_op_shared_webgpu.ts
  tfjs-backend-webgpu/src/kernels/binary_op_vec4_webgpu.ts
  tfjs-backend-webgpu/src/kernels/binary_op_webgpu.ts
  tfjs-backend-webgpu/src/kernels/clip_vec4_webgpu.ts
  tfjs-backend-webgpu/src/kernels/clip_webgpu.ts
  tfjs-backend-webgpu/src/kernels/concat_webgpu.ts
  tfjs-backend-webgpu/src/kernels/conv2d_naive_webgpu.ts
  tfjs-backend-webgpu/src/kernels/crop_and_resize_webgpu.ts
  tfjs-backend-webgpu/src/kernels/depthwise_conv2d_3x3_webgpu.ts
  tfjs-backend-webgpu/src/kernels/depthwise_conv2d_webgpu.ts
  tfjs-backend-webgpu/src/kernels/fill_webgpu.ts
  tfjs-backend-webgpu/src/kernels/gather_nd_webgpu.ts
  tfjs-backend-webgpu/src/kernels/gather_webgpu.ts
  tfjs-backend-webgpu/src/kernels/im2col_webgpu.ts
  tfjs-backend-webgpu/src/kernels/matmul_packed_vec4_webgpu.ts
  tfjs-backend-webgpu/src/kernels/matmul_packed_webgpu.ts
  tfjs-backend-webgpu/src/kernels/mirror_pad_webgpu.ts
  tfjs-backend-webgpu/src/kernels/pad_webgpu.ts
  tfjs-backend-webgpu/src/kernels/pool2d_webgpu.ts
  tfjs-backend-webgpu/src/kernels/pool_filtersizeone_webgpu.ts
  tfjs-backend-webgpu/src/kernels/reduce_webgpu.ts
  tfjs-backend-webgpu/src/kernels/resize_bilinear_webgpu.ts
  tfjs-backend-webgpu/src/kernels/resize_nearest_neighbor_webgpu.ts
  tfjs-backend-webgpu/src/kernels/select_webgpu.ts
  tfjs-backend-webgpu/src/kernels/slice_webgpu.ts
  tfjs-backend-webgpu/src/kernels/strided_slice_webgpu.ts
  tfjs-backend-webgpu/src/kernels/tile_webgpu.ts
  tfjs-backend-webgpu/src/kernels/transform_webgpu.ts
  tfjs-backend-webgpu/src/kernels/transpose_shared_webgpu.ts
  tfjs-backend-webgpu/src/kernels/transpose_webgpu.ts
  tfjs-backend-webgpu/src/kernels/unary_op_webgpu.ts
  tfjs-backend-webgpu/src/kernels/webgpu_program.ts
  tfjs-backend-webgpu/src/shader_preprocessor_wgsl.ts
Labels: cla: yes

#5596 Add github actions for previewing/deploying benchmark site to firebase hosting
  .github/workflows/deploy-benchmark-preview.yml
  .github/workflows/deploy-benchmark-prod.yml
  e2e/benchmarks/firebase.json
  e2e/benchmarks/firebase_staging.json
  e2e/benchmarks/local-benchmark/index.html
  e2e/scripts/deploy-benchmarks.sh
Labels: cla: yes

#5599 Upadte benchmark tool url
  README.md
Labels: cla: yes

#5582 [core] Fix io test flakiness when run out-of-order
  tfjs-converter/src/executor/graph_executor.ts
  tfjs-core/scripts/test_snippets/BUILD.bazel
  tfjs-core/src/BUILD.bazel
  tfjs-core/src/io/indexed_db_test.ts
  tfjs-core/src/io/local_storage_test.ts
  tfjs-core/src/io/model_management_test.ts
  tfjs-core/src/jasmine_util.ts
  tfjs-core/src/util_base.ts
  tfjs-data/package.json
  tfjs-data/src/util/deep_map.ts
Labels: cla: yes

#5565 [webgpu] Add conv2dBackprop WGSL support
  tfjs-backend-webgpu/src/kernels/Conv2DBackpropInput.ts
  tfjs-backend-webgpu/src/kernels/conv_backprop_mm_webgpu.ts
  tfjs-backend-webgpu/src/kernels/conv_backprop_webgpu.ts
Labels: cla: yes

#5567 [webgpu] Add MatMulSmallOutputSizeProgram WGSL support
  tfjs-backend-webgpu/src/kernels/matmul_small_output_size_webgpu.ts
Labels: cla: yes

#5589 [webgpu] Fix WGSL pow case fail
  tfjs-backend-webgpu/src/kernels/binary_op_util.ts
  tfjs-backend-webgpu/src/shader_preprocessor_wgsl.ts
  tfjs-core/src/ops/arithmetic_test.ts
Labels: cla: yes

#5593 [webgpu] Remove unused uniforms in PoolWithFilterSizeEqualsOneProgram
  tfjs-backend-webgpu/src/kernels/AvgPool.ts
  tfjs-backend-webgpu/src/kernels/MaxPool.ts
  tfjs-backend-webgpu/src/kernels/pool2d_webgpu.ts
  tfjs-backend-webgpu/src/kernels/pool_filtersizeone_webgpu.ts
Labels: cla: yes

#5600 Fix converter nightly test
  tfjs-converter/cloudbuild_nightly.yml
  tfjs-converter/python/build-pip-package.sh
Labels: cla: yes

#5570 [automl] Update tfjs deps to 3.9.0
  tfjs-automl/package.json
  tfjs-automl/yarn.lock
Labels: cla: yes

#5617 Update diag.ts
  tfjs-core/src/ops/diag.ts
Labels: cla: yes

#5610 [webgpu] Create FromPixles program as required
  tfjs-backend-webgpu/src/backend_webgpu.ts
  tfjs-backend-webgpu/src/kernels/FromPixels_utils/from_pixels_webgpu.ts
Labels: cla: yes

#5618 Webgl Update package.json
  tfjs-backend-webgl/package.json
Labels: cla: yes

#5625 [e2e] Fix converter missing in publishing CI
  e2e/scripts/publish-tfjs-ci.sh
Labels: cla: yes

#5616 [webgl] Run tests out of order
  tfjs-backend-webgl/karma.conf.js
  tfjs-backend-webgl/src/backend_webgl_test.ts
  tfjs-backend-webgl/src/flags_webgl_test.ts
  tfjs-core/src/ops/image/threshold_test.ts
Labels: cla: yes

#5635 [converter] Pin python2 protobuf version to 3.17.3
  tfjs-converter/python/BUILD
  tfjs-converter/python/requirements.txt
Labels: cla: yes

#5628 [webgpu] Use i32 as coords type in WGSL
  tfjs-backend-webgpu/src/kernels/BatchMatMul_impl.ts
  tfjs-backend-webgpu/src/kernels/Conv2D.ts
  tfjs-backend-webgpu/src/kernels/Conv2D_impl.ts
  tfjs-backend-webgpu/src/kernels/FromPixels_utils/from_pixels_webgpu.ts
  tfjs-backend-webgpu/src/kernels/FusedConv2D.ts
  tfjs-backend-webgpu/src/kernels/addn_packed_webgpu.ts
  tfjs-backend-webgpu/src/kernels/argminmax_webgpu.ts
  tfjs-backend-webgpu/src/kernels/binary_op_shared_webgpu.ts
  tfjs-backend-webgpu/src/kernels/binary_op_webgpu.ts
  tfjs-backend-webgpu/src/kernels/clip_vec4_webgpu.ts
  tfjs-backend-webgpu/src/kernels/concat_webgpu.ts
  tfjs-backend-webgpu/src/kernels/conv2d_mm_vec4_webgpu.ts
  tfjs-backend-webgpu/src/kernels/conv2d_mm_webgpu.ts
  tfjs-backend-webgpu/src/kernels/conv2d_naive_webgpu.ts
  tfjs-backend-webgpu/src/kernels/conv_backprop_mm_webgpu.ts
  tfjs-backend-webgpu/src/kernels/conv_backprop_webgpu.ts
  tfjs-backend-webgpu/src/kernels/crop_and_resize_webgpu.ts
  tfjs-backend-webgpu/src/kernels/depthwise_conv2d_3x3_webgpu.ts
  tfjs-backend-webgpu/src/kernels/depthwise_conv2d_webgpu.ts
  tfjs-backend-webgpu/src/kernels/fill_webgpu.ts
  tfjs-backend-webgpu/src/kernels/gather_nd_webgpu.ts
  tfjs-backend-webgpu/src/kernels/gather_webgpu.ts
  tfjs-backend-webgpu/src/kernels/im2col_webgpu.ts
  tfjs-backend-webgpu/src/kernels/matmul_packed_vec4_webgpu.ts
  tfjs-backend-webgpu/src/kernels/matmul_packed_webgpu.ts
  tfjs-backend-webgpu/src/kernels/matmul_small_output_size_webgpu.ts
  tfjs-backend-webgpu/src/kernels/mirror_pad_webgpu.ts
  tfjs-backend-webgpu/src/kernels/pad_webgpu.ts
  tfjs-backend-webgpu/src/kernels/pool2d_webgpu.ts
  tfjs-backend-webgpu/src/kernels/pool_filtersizeone_webgpu.ts
  tfjs-backend-webgpu/src/kernels/reduce_webgpu.ts
  tfjs-backend-webgpu/src/kernels/resize_bilinear_webgpu.ts
  tfjs-backend-webgpu/src/kernels/resize_nearest_neighbor_webgpu.ts
  tfjs-backend-webgpu/src/kernels/slice_webgpu.ts
  tfjs-backend-webgpu/src/kernels/strided_slice_webgpu.ts
  tfjs-backend-webgpu/src/kernels/transform_webgpu.ts
  tfjs-backend-webgpu/src/kernels/transpose_shared_webgpu.ts
  tfjs-backend-webgpu/src/kernels/transpose_webgpu.ts
  tfjs-backend-webgpu/src/shader_preprocessor_wgsl.ts
Labels: cla: yes

#5621 [webgpu] Use WGSL as default shading language
  tfjs-backend-webgpu/src/flags_webgpu.ts
Labels: cla: yes

#5626 [react-native] Add option to TensorCamera to not use custom shaders to resize camera image texture
  tfjs-react-native/src/camera/camera.ts
  tfjs-react-native/src/camera/camera_stream.tsx
  tfjs-react-native/src/camera/camera_test.ts
  tfjs-react-native/src/camera/camera_webgl_util.ts
  tfjs-react-native/src/camera/draw_texture_program_info.ts
  tfjs-react-native/yarn.lock
Labels: cla: yes

#5636 [webgl] Update yarn.lock
  tfjs-backend-webgl/yarn.lock
Labels: cla: yes

#5639 [converter] Add required libs to readme
  tfjs-converter/README.md
Labels: cla: yes

#5638 Update tfjs-react-native to 0.7.0.
  tfjs-react-native/package.json
  tfjs-react-native/src/version.ts
Labels: cla: yes, INTERNAL

#5562 [webgl] Build tfjs-backend-webgl with Bazel
  e2e/benchmarks/browserstack-benchmark/yarn.lock
  e2e/package.json
  e2e/scripts/publish-tfjs-ci.sh
  link-package/package.json
  package.json
  scripts/cloudbuild_tfjs_core_expected.yml
  scripts/cloudbuild_tfjs_node_expected.yml
  scripts/package_dependencies.json
  scripts/publish-npm.ts
  tfjs-backend-webgl/BUILD.bazel
  tfjs-backend-webgl/cloudbuild.yml
  tfjs-backend-webgl/karma.conf.js
  tfjs-backend-webgl/package.json
  tfjs-backend-webgl/src/BUILD.bazel
  tfjs-backend-webgl/src/flags_webgl_test.ts
  tfjs-backend-webgl/src/setup_test.ts
  tfjs-backend-webgl/yarn.lock
  tfjs-core/src/device_util.ts
  tfjs-core/src/engine_test.ts
  tfjs-layers/package.json
  tfjs/package.json
  tfjs/yarn.lock
  tools/karma_template.conf.js
  tools/tfjs_web_test.bzl
  yarn.lock
Labels: cla: yes

#5651 Only start browserstack tunnel when running on BrowserStack
  tools/karma_template.conf.js
  yarn.lock
Labels: cla: yes

#5642 [webgpu] Add support for sin, cos, sinh and cosh
  tfjs-backend-webgpu/src/kernels/Cos.ts
  tfjs-backend-webgpu/src/kernels/Cosh.ts
  tfjs-backend-webgpu/src/kernels/Sin.ts
  tfjs-backend-webgpu/src/kernels/Sinh.ts
  tfjs-backend-webgpu/src/kernels/unary_op_util.ts
  tfjs-backend-webgpu/src/register_all_kernels.ts
  tfjs-backend-webgpu/src/setup_test.ts
Labels: cla: yes

#5645 [webgpu] Add support for split
  tfjs-backend-webgpu/src/kernels/SplitV.ts
  tfjs-backend-webgpu/src/register_all_kernels.ts
  tfjs-backend-webgpu/src/setup_test.ts
Labels: cla: yes

#5644 [webgpu] Add support for LogicalNot
  tfjs-backend-webgpu/src/kernels/LogicalNot.ts
  tfjs-backend-webgpu/src/kernels/unary_op_util.ts
  tfjs-backend-webgpu/src/register_all_kernels.ts
  tfjs-backend-webgpu/src/setup_test.ts
Labels: cla: yes

#5647 [webgpu] Add WGSL shader for Tanh
  tfjs-backend-webgpu/src/kernels/unary_op_util.ts
  tfjs-backend-webgpu/src/setup_test.ts
Labels: cla: yes

#5649 webgpu: add flipLeftRight and rotate operators
  tfjs-backend-webgpu/src/kernels/FlipLeftRight.ts
  tfjs-backend-webgpu/src/kernels/RotateWithOffset.ts
  tfjs-backend-webgpu/src/kernels/flip_left_right_webgpu.ts
  tfjs-backend-webgpu/src/kernels/rotate_webgpu.ts
  tfjs-backend-webgpu/src/register_all_kernels.ts
  tfjs-backend-webgpu/src/setup_test.ts
Labels: cla: yes

#5637 Add cases for Conv2DMMVec4Program and Conv2dNaiveProgram
  tfjs-backend-webgpu/src/kernels/conv2d_webgpu_test.ts
Labels: cla: yes

#5614 Update tfjs-automl to 1.3.0.
  tfjs-automl/package.json
  tfjs-automl/src/version.ts
Labels: cla: yes, INTERNAL

#5615 Add automl to the release script
  scripts/release-util.ts
Labels: cla: yes

#5658 Add automl to release notes script
  scripts/release_notes/release_notes.ts
Labels: cla: yes

#5629 [webgpu] Add support for SparseToDense
  tfjs-backend-webgpu/src/kernels/SparseToDense.ts
  tfjs-backend-webgpu/src/kernels/scatter_webgpu.ts
  tfjs-backend-webgpu/src/register_all_kernels.ts
  tfjs-backend-webgpu/src/setup_test.ts
Labels: cla: yes

#5646 [webgpu] Fix matmul_small_output program assert error
  tfjs-backend-webgpu/src/kernels/BatchMatMul_impl.ts
  tfjs-backend-webgpu/src/kernels/matmul_small_output_size_webgpu.ts
Labels: cla: yes

#5643 Webgpu feature scatter nd
  tfjs-backend-webgpu/src/kernels/ScatterNd.ts
  tfjs-backend-webgpu/src/kernels/scatter_webgpu.ts
  tfjs-backend-webgpu/src/register_all_kernels.ts
  tfjs-backend-webgpu/src/setup_test.ts
Labels: cla: yes

#5598 webgpu: Batch several dispatching calls into one pass
  tfjs-backend-webgpu/src/backend_webgpu.ts
  tfjs-backend-webgpu/src/flags_webgpu.ts
Labels: cla: yes

#5622 [wgsl] Refine pow
  tfjs-backend-webgpu/src/kernels/binary_op_util.ts
  tfjs-backend-webgpu/src/shader_preprocessor.ts
Labels: cla: yes

#5640 Base the release docker off of debian
  WORKSPACE
  dockers/release-docker/Dockerfile
  tfjs-converter/README.md
  tfjs-node/scripts/ensure-cpu-gpu-packages-align.js
  tfjs-tflite/package.json
  tfjs-tflite/yarn.lock
Labels: cla: yes

#5669 Use the release docker for all cloudbuild steps
  cloudbuild.yml
  scripts/cloudbuild_general_config.yml
  scripts/cloudbuild_tfjs_core_expected.yml
  scripts/cloudbuild_tfjs_node_expected.yml
  tfjs-automl/cloudbuild.yml
  tfjs-backend-wasm/cloudbuild.yml
  tfjs-backend-webgpu/cloudbuild.yml
  tfjs-converter/cloudbuild.yml
  tfjs-converter/cloudbuild_nightly.yml
  tfjs-core/cloudbuild.yml
  tfjs-data/cloudbuild.yml
  tfjs-inference/cloudbuild.yml
  tfjs-layers/cloudbuild.yml
  tfjs-react-native/cloudbuild.yml
  tfjs-vis/cloudbuild.yml
  tfjs/cloudbuild.yml
Labels: cla: yes

#5665 webgpu: Use a larger cpu forward threshold
  tfjs-backend-webgpu/src/backend_webgpu.ts
  tfjs-backend-webgpu/src/flags_webgpu.ts
Labels: cla: yes

#5667 WebGPU: Optimize ScatterNd
  tfjs-backend-webgpu/src/kernels/scatter_webgpu.ts
  tfjs-backend-webgpu/src/setup_test.ts
Labels: cla: yes

#5671 Upgrade rules_nodejs to 4.2.0
  BAZEL_MIGRATION.md
  WORKSPACE
  package.json
  tfjs-backend-cpu/BUILD.bazel
  tfjs-backend-webgl/BUILD.bazel
  tfjs-backend-webgl/src/BUILD.bazel
  tfjs-converter/BUILD.bazel
  tfjs-core/BUILD.bazel
  tfjs-tflite/BUILD.bazel
  tools/defaults.bzl
  yarn.lock
Labels: cla: yes, bazel

#5604 [tflite] Remove unneeded download step from readme
  tfjs-tflite/README.md
Labels: cla: yes

#5673 Fix Bazel not running tests tagged with "nightly" in nightly
  scripts/cloudbuild_general_config.yml
  scripts/cloudbuild_tfjs_core_expected.yml
  scripts/cloudbuild_tfjs_node_expected.yml
Labels: cla: yes

#5676 [webgpu] Mark build-npm.sh as executable
  tfjs-backend-webgpu/scripts/build-npm.sh
Labels: cla: yes

#5681 Update tfjs-backend-webgpu to 0.0.1-alpha.8.
  tfjs-backend-webgpu/package.json
  tfjs-backend-webgpu/src/version.ts
  tfjs-backend-webgpu/yarn.lock
Labels: cla: yes, INTERNAL
