Repository tensorflow/tfjs, pull requests merged in 2021-03, with the labels that each got.

#4717 Enable flaky tests for tfjs union
  tfjs/scripts/test-ci.sh
Labels: cla: yes

#4235 Fix wasm strided slice with new axis
  tfjs-backend-wasm/src/kernels/StridedSlice.ts
  tfjs-core/src/ops/strided_slice_test.ts
Labels: cla: yes

#4755 Add LookupTableSize and LookupTableSizeV2 ops
  tfjs-converter/docs/supported_ops.md
  tfjs-converter/metadata/kernel2op.json
  tfjs-converter/python/tensorflowjs/op_list/hash_table.json
  tfjs-converter/src/executor/hash_table.ts
  tfjs-converter/src/executor/model_analysis.ts
  tfjs-converter/src/metadata_test.ts
  tfjs-converter/src/operations/executors/hash_table_executor.ts
  tfjs-converter/src/operations/executors/hash_table_executor_test.ts
  tfjs-converter/src/operations/op_list/hash_table.ts
Labels: cla: no

#4772 Update dockerfiles to support emsdk
  dockers/release-docker/Dockerfile
  dockers/wasm-docker/Dockerfile
Labels: cla: yes

#4773 Fix python in the CI dockerfile
  dockers/wasm-docker/Dockerfile
Labels: cla: yes

#4767 webgpu: add control barrier for read-write operation
  tfjs-backend-webgpu/src/kernels/reduce_webgpu.ts
Labels: cla: yes

#4779 [webgl] use uniform for pad constants
  tfjs-backend-webgl/src/kernels/PadV2.ts
  tfjs-backend-webgl/src/pad_gpu.ts
  tfjs-backend-webgl/src/pad_packed_gpu.ts
  tfjs-core/src/ops/fill_test.ts
  tfjs-core/src/ops/pad_test.ts
Labels: cla: yes

#4752 [webgpu] Add ceil, floor, expm1, rsqrt
  tfjs-backend-webgpu/src/kernels/Ceil.ts
  tfjs-backend-webgpu/src/kernels/Expm1.ts
  tfjs-backend-webgpu/src/kernels/Floor.ts
  tfjs-backend-webgpu/src/kernels/Rsqrt.ts
  tfjs-backend-webgpu/src/register_all_kernels.ts
  tfjs-backend-webgpu/src/setup_test.ts
Labels: cla: yes

#4753 Keep values on CPU
  tfjs-backend-webgpu/src/backend_webgpu.ts
Labels: cla: yes

#4783 [webgl]fixed pad unpacked shader failure
  tfjs-backend-webgl/src/pad_gpu.ts
Labels: cla: yes

#4785 [webgpu] Add support for Elu
  tfjs-backend-webgpu/src/kernels/Elu.ts
  tfjs-backend-webgpu/src/register_all_kernels.ts
  tfjs-backend-webgpu/src/setup_test.ts
Labels: cla: yes

#4784 [webgl] Rotate performance fix
  tfjs-backend-webgl/src/kernels/RotateWithOffset.ts
  tfjs-backend-webgl/src/rotate_gpu.ts
Labels: cla: yes

#4781 webgpu: Use uniform for pad/fill constants
  tfjs-backend-webgpu/src/backend_webgpu.ts
  tfjs-backend-webgpu/src/kernels/ArgMax.ts
  tfjs-backend-webgpu/src/kernels/ArgMin.ts
  tfjs-backend-webgpu/src/kernels/AvgPool.ts
  tfjs-backend-webgpu/src/kernels/Conv2D.ts
  tfjs-backend-webgpu/src/kernels/DepthwiseConv2dNative.ts
  tfjs-backend-webgpu/src/kernels/Fill.ts
  tfjs-backend-webgpu/src/kernels/FusedConv2D.ts
  tfjs-backend-webgpu/src/kernels/FusedDepthwiseConv2D.ts
  tfjs-backend-webgpu/src/kernels/MaxPool.ts
  tfjs-backend-webgpu/src/kernels/PadV2.ts
  tfjs-backend-webgpu/src/kernels/fill_webgpu.ts
  tfjs-backend-webgpu/src/kernels/pad_webgpu.ts
  tfjs-backend-webgpu/src/setup_test.ts
Labels: cla: yes

#4788 [webgpu] Add support for OnesLike
  tfjs-backend-webgpu/src/kernels/OnesLike.ts
  tfjs-backend-webgpu/src/register_all_kernels.ts
  tfjs-backend-webgpu/src/setup_test.ts
Labels: cla: yes

#4770 Add image.transform.
  tfjs-backend-cpu/src/kernels/Transform.ts
  tfjs-backend-cpu/src/register_all_kernels.ts
  tfjs-backend-webgl/src/kernels/Transform.ts
  tfjs-backend-webgl/src/register_all_kernels.ts
  tfjs-backend-webgl/src/transform_gpu.ts
  tfjs-core/src/kernel_names.ts
  tfjs-core/src/ops/image/transform.ts
  tfjs-core/src/ops/image/transform_test.ts
  tfjs-core/src/ops/ops.ts
  tfjs-core/src/tests.ts
  tfjs-node/src/run_tests.ts
Labels: cla: yes

#4789 [webgpu] Add unpack
  tfjs-backend-webgpu/src/kernels/Pack.ts
  tfjs-backend-webgpu/src/kernels/Unpack.ts
  tfjs-backend-webgpu/src/register_all_kernels.ts
  tfjs-backend-webgpu/src/setup_test.ts
Labels: cla: yes

#4795 Update monorepo to 3.3.0.
  tfjs-backend-cpu/package.json
  tfjs-backend-cpu/src/version.ts
  tfjs-backend-wasm/package.json
  tfjs-backend-wasm/src/version.ts
  tfjs-backend-webgl/package.json
  tfjs-backend-webgl/src/version.ts
  tfjs-converter/package.json
  tfjs-converter/python/tensorflowjs/version.py
  tfjs-converter/src/version.ts
  tfjs-core/package.json
  tfjs-core/src/version.ts
  tfjs-data/package.json
  tfjs-data/src/version.ts
  tfjs-layers/package.json
  tfjs-layers/src/version.ts
  tfjs-node-gpu/package.json
  tfjs-node/package.json
  tfjs-node/src/version.ts
  tfjs/package.json
  tfjs/src/version.ts
Labels: INTERNAL, cla: yes

#4797 Update lockfiles branch tfjs_3.3.0_lockfiles lock files.
  tfjs-backend-cpu/yarn.lock
  tfjs-backend-wasm/yarn.lock
  tfjs-backend-webgl/yarn.lock
  tfjs-converter/yarn.lock
  tfjs-data/yarn.lock
  tfjs-layers/yarn.lock
  tfjs-node-gpu/yarn.lock
  tfjs-node/yarn.lock
  tfjs/yarn.lock
Labels: INTERNAL, cla: yes

#4798 Update WASM backend's README to explain how to fix a potential error when used with Angular
  tfjs-backend-wasm/README.md
Labels: cla: yes

#4786 [webgpu] Add string support
  tfjs-backend-webgpu/src/backend_webgpu.ts
  tfjs-backend-webgpu/src/kernel_utils/shared.ts
  tfjs-backend-webgpu/src/kernels/Concat_impl.ts
  tfjs-backend-webgpu/src/setup_test.ts
  tfjs-backend-webgpu/src/webgpu_util.ts
Labels: cla: yes

#4805 Update tfjs-react-native README to add steps to fix a build error when using expo for web
  tfjs-react-native/README.md
Labels: cla: yes

#4792 Add Learning Tensorflow.JS Book
  GALLERY.md
Labels: cla: yes

#4807 webgpu: Fix the shared memory exceeds limit in some situation
  tfjs-backend-webgpu/src/kernels/matmul_packed_vec4_webgpu.ts
Labels: cla: yes

#4801 [webgpu] Fix avg|maxPool parameters order in uniform
  tfjs-backend-webgpu/src/kernels/AvgPool.ts
  tfjs-backend-webgpu/src/kernels/MaxPool.ts
  tfjs-backend-webgpu/src/kernels/pool2d_webgpu.ts
  tfjs-backend-webgpu/src/kernels/pool_filtersizeone_webgpu.ts
Labels: cla: yes

#4791 [webgpu] Add gather operator
  tfjs-backend-webgpu/src/kernel_utils/shared.ts
  tfjs-backend-webgpu/src/kernels/GatherV2.ts
  tfjs-backend-webgpu/src/kernels/gather_webgpu.ts
  tfjs-backend-webgpu/src/register_all_kernels.ts
  tfjs-backend-webgpu/src/setup_test.ts
Labels: cla: yes

#4782 webgpu: add mean and prod operators
  tfjs-backend-webgpu/src/kernel_utils/reduce.ts
  tfjs-backend-webgpu/src/kernel_utils/shared.ts
  tfjs-backend-webgpu/src/kernels/Max.ts
  tfjs-backend-webgpu/src/kernels/Mean.ts
  tfjs-backend-webgpu/src/kernels/Min.ts
  tfjs-backend-webgpu/src/kernels/Prod.ts
  tfjs-backend-webgpu/src/kernels/Sum.ts
  tfjs-backend-webgpu/src/kernels/reduce_webgpu.ts
  tfjs-backend-webgpu/src/register_all_kernels.ts
  tfjs-backend-webgpu/src/setup_test.ts
Labels: cla: yes

#4825 allow correctness test in the benchmark tool for custom model
  e2e/benchmarks/local-benchmark/index.html
  e2e/benchmarks/model_config.js
Labels: cla: yes

#4827 Fix a bug in toNestedArray where it doesn't handle complex tensors properly
  tfjs-core/src/tensor.ts
  tfjs-core/src/tensor_test.ts
  tfjs-core/src/util_base.ts
  tfjs-core/src/util_test.ts
Labels: cla: yes

#4821 [webgpu] Update and add webgpu scripts for release
  tfjs-backend-webgpu/package.json
  tfjs-backend-webgpu/rollup.config.js
  tfjs-backend-webgpu/scripts/build-npm.sh
Labels: cla: yes

#4799 [wasm] Add all/any kernels
  tfjs-backend-wasm/src/cc/BUILD
  tfjs-backend-wasm/src/cc/kernels/All.cc
  tfjs-backend-wasm/src/cc/kernels/Any.cc
  tfjs-backend-wasm/src/kernels/All.ts
  tfjs-backend-wasm/src/kernels/Any.ts
  tfjs-backend-wasm/src/register_all_kernels.ts
  tfjs-backend-wasm/src/setup_test.ts
Labels: cla: yes

#4817 Detect react native in 'isMobile'
  tfjs-core/src/device_util.ts
  tfjs-core/src/device_util_test.ts
Labels: cla: yes

#4804 [wasm] Add mirrorPad kernel
  tfjs-backend-wasm/src/cc/BUILD
  tfjs-backend-wasm/src/cc/kernels/MirrorPad.cc
  tfjs-backend-wasm/src/kernels/MirrorPad.ts
  tfjs-backend-wasm/src/register_all_kernels.ts
  tfjs-backend-wasm/src/setup_test.ts
Labels: cla: yes

#4834 Add Swish to activation config
  tfjs-layers/src/keras_format/activation_config.ts
Labels: cla: yes

#4836 webgpu: Fix the delayed mode memory leak issue
  tfjs-backend-webgpu/src/backend_webgpu.ts
Labels: cla: yes

#4850 [e2e] Make e2e environment setup scripts works on Windows
  e2e/scripts/setup-py-env.sh
  e2e/scripts/test.sh
Labels: cla: yes

#4857 [e2e] Fix e2e virtualenv in nightly CI
  e2e/scripts/setup-py-env.sh
Labels: cla: yes

#4858 add support for isNan op
  tfjs-converter/docs/supported_ops.md
  tfjs-converter/metadata/kernel2op.json
  tfjs-converter/python/tensorflowjs/op_list/basic_math.json
  tfjs-converter/python/tensorflowjs/op_list/hash_table.json
  tfjs-converter/src/operations/executors/basic_math_executor.ts
  tfjs-converter/src/operations/executors/basic_math_executor_test.ts
  tfjs-converter/src/operations/op_list/basic_math.ts
Labels: cla: yes

#4854 webgpu: Fix the maxpool error
  tfjs-backend-webgpu/src/kernels/pool2d_webgpu.ts
Labels: cla: yes

#4835 Fix include path in `.vscode/c_cpp_properties.json`
  tfjs-backend-wasm/.vscode/c_cpp_properties.json
Labels: cla: yes

#4849 [tfjs-node] Make `yarn build` works on Windows
  tfjs-node-gpu/package.json
  tfjs-node/package.json
Labels: cla: yes

#4859 Skip import paths that cannot be resolved in the custom module CLI tool
  tfjs/tools/custom_module/custom_module.ts
  tfjs/tools/custom_module/custom_module_test.ts
  tfjs/tools/custom_module/esm_module_provider.ts
  tfjs/tools/custom_module/types.ts
Labels: cla: yes

#4866 [vis] Bump vega to 5.20.0
  tfjs-vis/package.json
  tfjs-vis/yarn.lock
Labels: cla: yes

#4790 [tfjs-core] Performance issue with tf.signal.stft (#4623)
  tfjs-core/src/ops/signal/stft.ts
Labels: cla: yes

#4875 Move cloud functions to central location and update googleapis
  scripts/cloud_funcs/README.md
  scripts/cloud_funcs/send_email/.gcloudignore
  scripts/cloud_funcs/send_email/config.json
  scripts/cloud_funcs/send_email/index.js
  scripts/cloud_funcs/send_email/package-lock.json
  scripts/cloud_funcs/send_email/package.json
  scripts/cloud_funcs/send_email/yarn.lock
  scripts/cloud_funcs/sync_reactnative/.gcloudignore
  scripts/cloud_funcs/sync_reactnative/index.js
  scripts/cloud_funcs/sync_reactnative/package.json
  scripts/cloud_funcs/trigger_nightly/.gcloudignore
  scripts/cloud_funcs/trigger_nightly/index.js
  scripts/cloud_funcs/trigger_nightly/package.json
  tfjs-core/scripts/cloud_funcs/trigger_nightly/index.js
  tfjs-core/scripts/cloud_funcs/trigger_nightly/package-lock.json
  tfjs/scripts/cloud_funcs/README.md
  tfjs/scripts/cloud_funcs/trigger_nightly/.gcloudignore
  tfjs/scripts/cloud_funcs/trigger_nightly/package.json
Labels: cla: yes

#4769 Use official emsdk bazel toolchain
  .bazelrc
  .gitignore
  WORKSPACE
  tfjs-backend-wasm/scripts/build-ci.sh
  tfjs-backend-wasm/scripts/build-wasm.sh
  tfjs-backend-wasm/scripts/create-worker-module.js
  tfjs-backend-wasm/src/cc/BUILD
  tfjs-backend-wasm/src/cc/binary.cc
  tfjs-backend-wasm/src/cc/kernels/All.cc
  tfjs-backend-wasm/src/cc/kernels/Any.cc
  tfjs-backend-wasm/src/cc/kernels/CropAndResize.cc
  tfjs-backend-wasm/src/cc/kernels/FloorDiv.cc
  tfjs-backend-wasm/src/cc/kernels/Max.cc
  tfjs-backend-wasm/src/cc/kernels/Mean.cc
  tfjs-backend-wasm/src/cc/kernels/Min.cc
  tfjs-backend-wasm/src/cc/kernels/Pow.cc
  tfjs-backend-wasm/src/cc/kernels/Prod.cc
  tfjs-backend-wasm/src/cc/kernels/Sum.cc
  tfjs-backend-wasm/src/cc/non_max_suppression_impl.cc
  tfjs-backend-wasm/yarn.lock
  toolchain/BUILD
  toolchain/cc_toolchain_config.bzl
  toolchain/emar.sh
  toolchain/emcc.sh
  toolchain/false.sh
Labels: cla: yes

#4872 Fix where op
  tfjs-core/src/ops/where.ts
  tfjs-core/src/ops/where_test.ts
Labels: cla: yes

#4869 fix sec vulnerabilities for all packages
  e2e/package.json
  e2e/yarn.lock
  package.json
  tfjs-automl/package.json
  tfjs-automl/yarn.lock
  tfjs-backend-cpu/package.json
  tfjs-backend-cpu/yarn.lock
  tfjs-backend-nodegl/package.json
  tfjs-backend-nodegl/yarn.lock
  tfjs-backend-wasm/package.json
  tfjs-backend-wasm/yarn.lock
  tfjs-backend-webgl/package.json
  tfjs-backend-webgl/yarn.lock
  tfjs-backend-webgpu/package.json
  tfjs-backend-webgpu/yarn.lock
  tfjs-converter/package.json
  tfjs-converter/src/operations/executors/convolution_executor.ts
  tfjs-converter/yarn.lock
  tfjs-core/package.json
  tfjs-core/yarn.lock
  tfjs-data/package.json
  tfjs-data/yarn.lock
  tfjs-inference/package.json
  tfjs-inference/yarn.lock
  tfjs-layers/package.json
  tfjs-layers/yarn.lock
  tfjs-node-gpu/package.json
  tfjs-node-gpu/yarn.lock
  tfjs-node/package.json
  tfjs-node/yarn.lock
  tfjs-react-native/package.json
  tfjs-react-native/src/platform_react_native.ts
  tfjs-react-native/yarn.lock
  tfjs-vis/package.json
  tfjs-vis/yarn.lock
  yarn.lock
Labels: cla: yes

#4885 more sec update
  scripts/cloud_funcs/send_email/package-lock.json
  scripts/cloud_funcs/send_email/package.json
  scripts/cloud_funcs/send_email/yarn.lock
  tfjs-backend-nodegl/package.json
  tfjs-backend-nodegl/yarn.lock
  tfjs-vis/package.json
  tfjs-vis/yarn.lock
  tfjs/package.json
  tfjs/yarn.lock
Labels: cla: yes

#4890 Adding mode to h5py.File to dismiss deprecation warning
  tfjs-converter/python/tensorflowjs/converters/keras_h5_conversion.py
Labels: cla: yes

#4891 fix cloud funcs sec vulnerabilities
  scripts/cloud_funcs/send_email/yarn.lock
Labels: cla: yes
