Repository tensorflow/tfjs, pull requests merged in 2021-05, with the labels that each got.

#5020 Fix SparseFillEmptyRows output shape bug
  tfjs-backend-cpu/src/kernels/SparseFillEmptyRows_impl.ts
  tfjs-core/src/ops/sparse/sparse_fill_empty_rows.ts
  tfjs-core/src/ops/sparse/sparse_fill_empty_rows_test.ts
Labels: cla: yes

#5018 Add kernel SparseSegmentSum for CPU and WebGL backend
  tfjs-backend-cpu/src/kernels/SparseSegmentReduction_impl.ts
  tfjs-backend-cpu/src/kernels/SparseSegmentSum.ts
  tfjs-backend-cpu/src/register_all_kernels.ts
  tfjs-backend-cpu/src/shared.ts
  tfjs-backend-webgl/src/kernel_utils/shared.ts
  tfjs-backend-webgl/src/kernels/SparseSegmentSum.ts
  tfjs-backend-webgl/src/register_all_kernels.ts
  tfjs-core/src/kernel_names.ts
  tfjs-core/src/ops/ops.ts
  tfjs-core/src/ops/sparse/sparse_segment_sum.ts
  tfjs-core/src/ops/sparse/sparse_segment_sum_test.ts
  tfjs-core/src/tests.ts
  tfjs-node/src/run_tests.ts
Labels: cla: yes

#5024 create node bundle for automl
  tfjs-automl/package.json
  tfjs-automl/rollup.config.js
Labels: cla: yes

#5028 align allbacks with tensorflow on NaN propogation with min/max ops
  tfjs-backend-cpu/src/kernels/Max_impl.ts
  tfjs-backend-cpu/src/kernels/Min.ts
  tfjs-backend-wasm/src/cc/kernels/Max.cc
  tfjs-backend-wasm/src/cc/kernels/Min.cc
  tfjs-backend-wasm/src/setup_test.ts
  tfjs-backend-webgl/src/reduce_gpu.ts
  tfjs-core/src/ops/max_test.ts
  tfjs-core/src/ops/min_test.ts
  tfjs-node/src/run_tests.ts
Labels: cla: yes

#5026 Add support for SparseSegmentSum conversion
  tfjs-converter/metadata/kernel2op.json
  tfjs-converter/python/tensorflowjs/op_list/sparse.json
  tfjs-converter/src/operations/executors/sparse_executor.ts
  tfjs-converter/src/operations/executors/sparse_executor_test.ts
  tfjs-converter/src/operations/op_list/sparse.ts
Labels: cla: yes

#5029 Add tfjs-tflite unit to the release process
  scripts/publish-npm.ts
  scripts/release-util.ts
  scripts/release_notes/release_notes.ts
  tfjs-tflite/package.json
  tfjs-tflite/src/tflite_model.ts
  tfjs-tflite/tsconfig.json
Labels: cla: yes

#5032 bump tfjs-automl version to 1.2.0
  tfjs-automl/package.json
  tfjs-automl/src/version.ts
Labels: cla: yes

#5025 Add kernel SparseSegmentMean for CPU and WebGL backend
  tfjs-backend-cpu/src/kernels/SparseSegmentMean.ts
  tfjs-backend-cpu/src/kernels/SparseSegmentReduction_impl.ts
  tfjs-backend-cpu/src/register_all_kernels.ts
  tfjs-backend-webgl/src/kernels/SparseSegmentMean.ts
  tfjs-backend-webgl/src/register_all_kernels.ts
  tfjs-core/src/kernel_names.ts
  tfjs-core/src/ops/ops.ts
  tfjs-core/src/ops/sparse/sparse_segment_mean.ts
  tfjs-core/src/ops/sparse/sparse_segment_mean_test.ts
  tfjs-core/src/tests.ts
  tfjs-node/src/run_tests.ts
Labels: cla: yes

#5037 Add support for SparseSegmentMean conversion
  tfjs-converter/metadata/kernel2op.json
  tfjs-converter/python/tensorflowjs/op_list/sparse.json
  tfjs-converter/src/operations/executors/sparse_executor.ts
  tfjs-converter/src/operations/executors/sparse_executor_test.ts
  tfjs-converter/src/operations/op_list/sparse.ts
Labels: cla: yes

#5039 [tflite] Fix the wrong script src in README
  tfjs-tflite/README.md
Labels: cla: yes

#5041 patch the mem leak fix to 3.3.0
  tfjs-node-gpu/package.json
  tfjs-node/binding/tfjs_backend.cc
  tfjs-node/package.json
  tfjs-node/src/version.ts
Labels: cla: yes

#5003 [webgl] Merge nightly CI karma tests for more parallelism
  tfjs-backend-webgl/scripts/test-ci.sh
Labels: cla: yes

#5036 [tfjs-node] update node-pre-gyp package
  tfjs-node-gpu/package.json
  tfjs-node-gpu/yarn.lock
  tfjs-node/package.json
  tfjs-node/src/index.ts
  tfjs-node/src/tfjs_binding_test.ts
  tfjs-node/yarn.lock
Labels: cla: yes

#5016 [WebGPU] Expand texture usage for fromPixels
  tfjs-backend-webgpu/src/kernels/FromPixels_utils/from_pixels_webgpu.ts
Labels: cla: yes

#5043 [tfjs-converter] heuristically determine the signature name
  tfjs-converter/python/tensorflowjs/converters/tf_saved_model_conversion_v2.py
Labels: cla: yes

#4993 [webgpu] Simplify shader key of slice and cropAndResize
  tfjs-backend-webgpu/src/kernels/CropAndResize.ts
  tfjs-backend-webgpu/src/kernels/Slice.ts
  tfjs-backend-webgpu/src/kernels/StridedSlice.ts
  tfjs-backend-webgpu/src/kernels/crop_and_resize_webgpu.ts
  tfjs-backend-webgpu/src/kernels/slice_webgpu.ts
  tfjs-backend-webgpu/src/kernels/strided_slice_webgpu.ts
Labels: cla: yes

#5038 Update dependencies to 3.6.0
  tfjs-automl/package.json
  tfjs-automl/src/object_detection_test.ts
Labels: cla: no

#5059 [webgpu] Add resizeNearestNeighbor support
  tfjs-backend-webgpu/src/kernels/ResizeNearestNeighbor.ts
  tfjs-backend-webgpu/src/kernels/resize_nearest_neighbor_webgpu.ts
  tfjs-backend-webgpu/src/register_all_kernels.ts
  tfjs-backend-webgpu/src/setup_test.ts
Labels: cla: yes

#5058 [webgpu] Add support for sqrt
  tfjs-backend-webgpu/src/kernels/Sqrt.ts
  tfjs-backend-webgpu/src/kernels/unary_op_webgpu.ts
  tfjs-backend-webgpu/src/register_all_kernels.ts
  tfjs-backend-webgpu/src/setup_test.ts
Labels: cla: yes

#5062 webgpu: upgrade @webgpu/types
  tfjs-backend-webgpu/package.json
  tfjs-backend-webgpu/src/index.ts
  tfjs-backend-webgpu/src/kernels/webgpu_program.ts
  tfjs-backend-webgpu/yarn.lock
Labels: cla: yes

#5061 webgpu: Add Transform kernel
  tfjs-backend-webgpu/src/kernels/Transform.ts
  tfjs-backend-webgpu/src/kernels/transform_webgpu.ts
  tfjs-backend-webgpu/src/register_all_kernels.ts
  tfjs-backend-webgpu/src/setup_test.ts
Labels: cla: yes

#5052 Add kernel StringToHashBucketFast for CPU and WebGL backend
  package.json
  tfjs-backend-cpu/src/kernels/StringToHashBucketFast.ts
  tfjs-backend-cpu/src/kernels/StringToHashBucketFast_impl.ts
  tfjs-backend-cpu/src/register_all_kernels.ts
  tfjs-backend-cpu/src/shared.ts
  tfjs-backend-webgl/src/kernel_utils/shared.ts
  tfjs-backend-webgl/src/kernels/StringToHashBucketFast.ts
  tfjs-backend-webgl/src/register_all_kernels.ts
  tfjs-backend-webgl/tsconfig.test.json
  tfjs-backend-webgl/yarn.lock
  tfjs-converter/src/operations/op_list/op_list_test.ts
  tfjs-converter/yarn.lock
  tfjs-core/BUILD.bazel
  tfjs-core/package.json
  tfjs-core/src/hash_util.ts
  tfjs-core/src/hash_util_test.ts
  tfjs-core/src/kernel_names.ts
  tfjs-core/src/ops/ops.ts
  tfjs-core/src/ops/string/string_to_hash_bucket_fast.ts
  tfjs-core/src/ops/string/string_to_hash_bucket_fast_test.ts
  tfjs-core/src/tests.ts
  tfjs-core/src/util.ts
  tfjs-core/yarn.lock
  tfjs-data/yarn.lock
  tfjs-layers/rollup.config.js
  tfjs-layers/yarn.lock
  tfjs-node-gpu/tsconfig.json
  tfjs-node-gpu/yarn.lock
  tfjs-node/src/callbacks.ts
  tfjs-node/src/io/file_system_test.ts
  tfjs-node/src/run_tests.ts
  tfjs-node/tsconfig.json
  tfjs-node/yarn.lock
  tfjs/rollup.config.js
  tfjs/yarn.lock
  tsconfig.json
  tsconfig.test.json
  yarn.lock
Labels: cla: no

#5068 fix imports for release ts files
  scripts/publish-npm.ts
  scripts/release-tfjs.ts
  scripts/release-util.ts
  scripts/release-website.ts
  scripts/release.ts
Labels: cla: yes

#5069 Update tfjs-tflite to 0.0.1-alpha.4.
  tfjs-tflite/package.json
  tfjs-tflite/src/version.ts
  tfjs-tflite/yarn.lock
Labels: INTERNAL, cla: yes

#5070 Fixes for the release scripts
  scripts/release-util.ts
  scripts/release_notes/release_notes.ts
Labels: cla: yes

#5067 Add support for StringToHashBucketFast conversion
  tfjs-converter/metadata/kernel2op.json
  tfjs-converter/python/tensorflowjs/op_list/string.json
  tfjs-converter/src/operations/executors/string_executor.ts
  tfjs-converter/src/operations/executors/string_executor_test.ts
  tfjs-converter/src/operations/op_list/string.ts
  tfjs-converter/src/operations/op_mapper_schema.ts
  tfjs-converter/src/operations/operation_executor.ts
  tfjs-converter/src/operations/types.ts
Labels: cla: yes

#5074 uses require instead of enable esmoduleinterop flag
  scripts/publish-npm.ts
  scripts/release-tfjs.ts
  scripts/release-util.ts
  scripts/release-website.ts
  scripts/release.ts
  tfjs-backend-cpu/yarn.lock
  tfjs-converter/src/operations/op_list/op_list_test.ts
  tfjs-core/scripts/test-ci.sh
  tfjs-core/src/hash_util.ts
  tfjs-layers/rollup.config.js
  tfjs-node-gpu/tsconfig.json
  tfjs-node/src/callbacks.ts
  tfjs-node/src/io/file_system_test.ts
  tfjs-node/tsconfig.json
  tfjs/rollup.config.js
  tsconfig.json
  tsconfig.test.json
Labels: cla: yes

#5065 webgpu: fix/suppress some failure cases
  tfjs-backend-webgpu/src/backend_webgpu.ts
  tfjs-backend-webgpu/src/backend_webgpu_test.ts
  tfjs-backend-webgpu/src/kernels/reduce_webgpu.ts
  tfjs-backend-webgpu/src/setup_test.ts
  tfjs-backend-webgpu/src/shader_preprocessor.ts
Labels: cla: yes

#5057 [webgpu] Add support for gatherND
  tfjs-backend-webgpu/src/kernels/GatherNd.ts
  tfjs-backend-webgpu/src/kernels/gather_nd_webgpu.ts
  tfjs-backend-webgpu/src/register_all_kernels.ts
  tfjs-backend-webgpu/src/setup_test.ts
Labels: cla: yes

#5001 [webgpu] Reuse GPUBindGroupLayout and GPUPipelineLayout
  tfjs-backend-webgpu/src/backend_webgpu.ts
  tfjs-backend-webgpu/src/kernels/FromPixelsImageBitmap.ts
  tfjs-backend-webgpu/src/kernels/FromPixels_utils/from_pixels_webgpu.ts
  tfjs-backend-webgpu/src/kernels/webgpu_program.ts
Labels: cla: yes

#5076 webgpu: run concat on cpu if possible
  tfjs-backend-webgpu/src/kernels/Concat_impl.ts
Labels: cla: yes

#5078 Fix CVE-2021-23362 in tfjs-automl
  tfjs-automl/yarn.lock
Labels: cla: yes

#5082 [webgpu] Fix invalid WGPUBindingType
  tfjs-backend-webgpu/src/backend_webgpu.ts
Labels: cla: yes

#5085 Fix CI failure for requiring the long package.
  tfjs-core/src/hash_util.ts
  tfjs/rollup.config.js
Labels: cla: yes

#5090 [tfjs-converter] check function def for unsupported ops
  tfjs-converter/python/tensorflowjs/converters/tf_saved_model_conversion_v2.py
Labels: cla: yes

#5089 Add kernel StringSplit for CPU and WebGL backend
  tfjs-backend-cpu/src/kernels/StringSplit.ts
  tfjs-backend-cpu/src/kernels/StringSplit_impl.ts
  tfjs-backend-cpu/src/register_all_kernels.ts
  tfjs-backend-cpu/src/shared.ts
  tfjs-backend-webgl/src/kernel_utils/shared.ts
  tfjs-backend-webgl/src/kernels/StringSplit.ts
  tfjs-backend-webgl/src/register_all_kernels.ts
  tfjs-core/src/kernel_names.ts
  tfjs-core/src/ops/ops.ts
  tfjs-core/src/ops/string/string_split.ts
  tfjs-core/src/ops/string/string_split_test.ts
  tfjs-core/src/tests.ts
  tfjs-node/src/run_tests.ts
Labels: cla: yes

#5106 [WebGL] expose CPU_HANDOFF_SIZE_THRESHOLD as a configurable flag
  tfjs-backend-webgl/src/backend_webgl.ts
  tfjs-backend-webgl/src/flags_webgl.ts
  tfjs-backend-webgl/src/flags_webgl_test.ts
  tfjs-backend-webgpu/src/backend_webgpu.ts
Labels: cla: yes

#5107 Add support for StringSplit conversion
  tfjs-converter/metadata/kernel2op.json
  tfjs-converter/python/tensorflowjs/op_list/string.json
  tfjs-converter/src/operations/executors/string_executor.ts
  tfjs-converter/src/operations/executors/string_executor_test.ts
  tfjs-converter/src/operations/op_list/string.ts
Labels: cla: yes

#5102 Add kernel StringNGrams for CPU and WebGL backend
  tfjs-backend-cpu/src/kernels/StringNGrams.ts
  tfjs-backend-cpu/src/kernels/StringNGrams_impl.ts
  tfjs-backend-cpu/src/register_all_kernels.ts
  tfjs-backend-cpu/src/shared.ts
  tfjs-backend-webgl/src/kernel_utils/shared.ts
  tfjs-backend-webgl/src/kernels/StringNGrams.ts
  tfjs-backend-webgl/src/register_all_kernels.ts
  tfjs-core/src/kernel_names.ts
  tfjs-core/src/ops/ops.ts
  tfjs-core/src/ops/string/string_n_grams.ts
  tfjs-core/src/ops/string/string_n_grams_test.ts
  tfjs-core/src/tests.ts
  tfjs-node/src/run_tests.ts
Labels: cla: yes

#5109 Add support for StringNGrams conversion
  tfjs-converter/metadata/kernel2op.json
  tfjs-converter/python/tensorflowjs/op_list/string.json
  tfjs-converter/src/operations/executors/string_executor.ts
  tfjs-converter/src/operations/executors/string_executor_test.ts
  tfjs-converter/src/operations/op_list/string.ts
Labels: cla: yes

#5104 webgpu: Add Conv2DBackpropInput kernel
  tfjs-backend-webgpu/src/kernels/Conv2DBackpropInput.ts
  tfjs-backend-webgpu/src/kernels/conv_backprop_webgpu.ts
  tfjs-backend-webgpu/src/register_all_kernels.ts
  tfjs-backend-webgpu/src/setup_test.ts
Labels: cla: yes

#5108 Make tfjs-node create a new TFJSBackend for each environment
  tfjs-node/binding/tfjs_backend.h
  tfjs-node/binding/tfjs_binding.cc
Labels: cla: yes

#5097 Update README of WASM backend
  tfjs-backend-wasm/README.md
Labels: cla: yes

#5095 Add instructions for how to see Google Cloud Build logs
  CONTRIBUTING.md
Labels: cla: yes

#5096 [tfjs-layers] remove dataSync call from tfjs-layers math util methods
  tfjs-layers/src/utils/math_utils.ts
Labels: cla: yes

#5114 Add missing op categories in converter and tests
  tfjs-converter/scripts/gen_doc.ts
  tfjs-converter/src/operations/op_list/op_list_test.ts
  tfjs-converter/src/operations/operation_executor_test.ts
  tfjs-converter/src/operations/operation_mapper.ts
  tfjs-converter/src/operations/operation_mapper_test.ts
  tfjs-converter/src/operations/types.ts
Labels: cla: yes

#5086 Fix CVE-2021-23362 in tfjs-backend-webgpu
  tfjs-backend-webgpu/yarn.lock
Labels: cla: yes

#5087 Fix CVE-2021-23362 in tfjs-backend-webgl
  tfjs-backend-webgl/yarn.lock
Labels: cla: yes

#5088 Fix CVE-2021-23362 in tfjs-backend-cpu
  tfjs-backend-cpu/yarn.lock
Labels: cla: yes

#5101 webgpu: Remove cpu backend
  tfjs-backend-webgpu/src/backend_webgpu.ts
Labels: cla: yes

#5119 webgpu: Add CPU_HANDOFF_SIZE_THRESHOLD
  tfjs-backend-webgpu/src/flags_webgpu.ts
Labels: cla: yes

#5083 [webgpu] Add shared memory flag to binary op shader key
  tfjs-backend-webgpu/src/kernels/binary_op_shared_webgpu.ts
Labels: cla: yes

#5127 [converter] Support function execution with named output indexing
  tfjs-converter/metadata/kernel2op.json
  tfjs-converter/python/tensorflowjs/op_list/sparse.json
  tfjs-converter/python/tensorflowjs/op_list/string.json
  tfjs-converter/src/operations/executors/string_executor_test.ts
  tfjs-converter/src/operations/executors/utils.ts
  tfjs-converter/src/operations/op_list/string.ts
  tfjs-converter/src/operations/op_mapper_schema.ts
  tfjs-converter/src/operations/operation_mapper.ts
  tfjs-converter/src/operations/operation_mapper_test.ts
  tfjs-converter/src/operations/types.ts
Labels: cla: yes

#5105 webgpu: Optimize getSamplerAtOutputCoords
  tfjs-backend-webgpu/src/backend_webgpu.ts
  tfjs-backend-webgpu/src/kernels/clip_vec4_webgpu.ts
  tfjs-backend-webgpu/src/kernels/clip_webgpu.ts
  tfjs-backend-webgpu/src/kernels/unary_op_webgpu.ts
  tfjs-backend-webgpu/src/kernels/webgpu_program.ts
  tfjs-backend-webgpu/src/shader_preprocessor.ts
Labels: cla: yes

#5098 Use googleapis.com instead of tfhub.dev for models
  e2e/benchmarks/model_config.js
Labels: cla: yes

#5131 webgpu: Fix the mirrorPad error
  tfjs-backend-webgpu/src/kernels/MirrorPad.ts
  tfjs-backend-webgpu/src/kernels/mirror_pad_webgpu.ts
  tfjs-backend-webgpu/src/setup_test.ts
Labels: cla: yes

#5125 [webgpu] Update yarn.lock for package types/long
  tfjs-backend-webgpu/yarn.lock
Labels: cla: yes

#5121 [webgpu] Fix nan errors
  tfjs-backend-webgpu/src/glsl_version.ts
  tfjs-backend-webgpu/src/kernels/binary_ops.ts
  tfjs-backend-webgpu/src/setup_test.ts
  tfjs-backend-webgpu/src/shader_preprocessor.ts
Labels: cla: yes

#5129 webgpu: Add vector*matrix kernel
  tfjs-backend-webgpu/src/kernels/BatchMatMul_impl.ts
  tfjs-backend-webgpu/src/kernels/matmul_packed_vec4_webgpu.ts
  tfjs-backend-webgpu/src/kernels/matmul_packed_webgpu.ts
Labels: cla: yes

#5135 Added string support for logical binary ops, gatherND, and StridedSlice
  tfjs-backend-cpu/src/kernels/Add.ts
  tfjs-backend-cpu/src/kernels/Atan2.ts
  tfjs-backend-cpu/src/kernels/GatherNd.ts
  tfjs-backend-cpu/src/kernels/GatherNd_Impl.ts
  tfjs-backend-cpu/src/kernels/Maximum.ts
  tfjs-backend-cpu/src/kernels/Minimum.ts
  tfjs-backend-cpu/src/kernels/Mod.ts
  tfjs-backend-cpu/src/kernels/Multiply.ts
  tfjs-backend-cpu/src/kernels/SquaredDifference.ts
  tfjs-backend-cpu/src/kernels/Sub.ts
  tfjs-backend-cpu/src/shared.ts
  tfjs-backend-cpu/src/utils/binary_impl.ts
  tfjs-backend-cpu/src/utils/binary_types.ts
  tfjs-backend-cpu/src/utils/binary_utils.ts
  tfjs-backend-wasm/src/setup_test.ts
  tfjs-backend-webgl/src/kernel_utils/kernel_funcs_utils.ts
  tfjs-backend-webgl/src/kernel_utils/shared.ts
  tfjs-backend-webgl/src/kernels/Equal.ts
  tfjs-backend-webgl/src/kernels/GatherNd.ts
  tfjs-backend-webgl/src/kernels/GreaterEqual.ts
  tfjs-backend-webgl/src/kernels/LessEqual.ts
  tfjs-backend-webgl/src/kernels/NotEqual.ts
  tfjs-core/src/ops/equal.ts
  tfjs-core/src/ops/equal_test.ts
  tfjs-core/src/ops/greater.ts
  tfjs-core/src/ops/greater_equal.ts
  tfjs-core/src/ops/greater_equal_test.ts
  tfjs-core/src/ops/greater_test.ts
  tfjs-core/src/ops/less.ts
  tfjs-core/src/ops/less_equal.ts
  tfjs-core/src/ops/less_equal_test.ts
  tfjs-core/src/ops/less_test.ts
  tfjs-core/src/ops/not_equal.ts
  tfjs-core/src/ops/not_equal_test.ts
  tfjs-core/src/ops/strided_slice.ts
  tfjs-node/src/run_tests.ts
Labels: cla: yes
