Repository tensorflow/tfjs, pull requests merged in 2021-08, with the labels that each got.

#5367 Add retry benchmark capabilities and jasmine tests
  e2e/benchmarks/browserstack-benchmark/README.md
  e2e/benchmarks/browserstack-benchmark/app.js
  e2e/benchmarks/browserstack-benchmark/app_node_test.js
  e2e/benchmarks/browserstack-benchmark/cloudbuild.yml
Labels: cla: yes

#5407 fix(typo): in comment; TensorFow -> TensorFlow
  tfjs-layers/src/models.ts
Labels: cla: yes

#5379 Fix `yarn build` command under tfjs-backend-webgl folder
  tfjs-backend-webgl/package.json
Labels: cla: yes

#5406 [webgl] Allow Sigmoid to run on packed data
  tfjs-backend-cpu/src/kernels/Sigmoid.ts
  tfjs-backend-cpu/src/shared.ts
  tfjs-backend-webgl/src/kernel_utils/shared.ts
  tfjs-backend-webgl/src/kernels/Sigmoid.ts
Labels: cla: yes

#5391 Add multiple device and model benchmarking capability and fix Firestore API key reference in cloudbuild
  e2e/benchmarks/browserstack-benchmark/README.md
  e2e/benchmarks/browserstack-benchmark/app.js
  e2e/benchmarks/browserstack-benchmark/app_node_test.js
  e2e/benchmarks/browserstack-benchmark/browser_list.json
  e2e/benchmarks/browserstack-benchmark/firestore.js
  e2e/benchmarks/browserstack-benchmark/preconfigured_browser.json
Labels: cla: yes

#5376 [tflite] Fix script tags order and load example in README
  tfjs-tflite/README.md
Labels: cla: yes

#5416 Use absolute import for version_test
  tfjs-backend-cpu/BUILD.bazel
  tfjs-backend-webgl/BUILD.bazel
  tfjs-backend-webgl/src/BUILD.bazel
  tfjs-core/BUILD.bazel
  tfjs-core/src/version_test.ts
Labels: bazel, cla: yes

#5361 Run enumerate-tests with Bazel
  tfjs-core/BUILD.bazel
  tfjs-core/package.json
  tfjs-core/scripts/BUILD.bazel
  tfjs-core/src/BUILD.bazel
  tfjs-core/src/tests.ts
  tools/BUILD.bazel
  tools/enumerate-tests.ts
  tools/enumerate_tests.bzl
Labels: bazel, cla: yes

#5358 Migrate tfjs-tflite package to bazel
  e2e/scripts/publish-tfjs-ci.sh
  link-package/package.json
  link-package/yarn.lock
  scripts/cloudbuild_tfjs_core_expected.yml
  scripts/package_dependencies.json
  scripts/publish-npm.ts
  tfjs-backend-cpu/package.json
  tfjs-tflite/BUILD.bazel
  tfjs-tflite/cloudbuild.yml
  tfjs-tflite/demo/README.md
  tfjs-tflite/demo/package.json
  tfjs-tflite/demo/yarn.lock
  tfjs-tflite/package.json
  tfjs-tflite/scripts/BUILD.bazel
  tfjs-tflite/scripts/download-tflite-web-api.sh
  tfjs-tflite/scripts/publish-npm.sh
  tfjs-tflite/scripts/test-ci.sh
  tfjs-tflite/src/BUILD.bazel
  tfjs-tflite/src/setup_test.ts
  tfjs-tflite/src/tflite_web_api_client.js
  tfjs-tflite/wasm/BUILD.bazel
  tfjs-tflite/yarn.lock
  yarn.lock
Labels: bazel, cla: yes

#5419 Fix the typo webgo->webgl
  link-package/package.json
  tfjs-backend-webgl/yarn.lock
Labels: cla: yes

#5424 Fix enumerate_tests.bzl on Windows
  tools/enumerate-tests.ts
  tools/enumerate_tests.bzl
Labels: bazel, cla: yes

#5417 Use correct externals and globals for webgl bundle
  tfjs-backend-webgl/BUILD.bazel
Labels: bazel, cla: yes

#5422 [webgl] Use uniforms for depthwise conv2d/reshape
  tfjs-backend-webgl/src/backend_webgl.ts
  tfjs-backend-webgl/src/conv_gpu_depthwise.ts
  tfjs-backend-webgl/src/conv_packed_gpu_depthwise.ts
  tfjs-backend-webgl/src/decode_matrix_gpu.ts
  tfjs-backend-webgl/src/decode_matrix_packed_gpu.ts
  tfjs-backend-webgl/src/kernel_utils/reshape.ts
  tfjs-backend-webgl/src/kernels/DepthwiseConv2dNative.ts
  tfjs-backend-webgl/src/kernels/FusedDepthwiseConv2D.ts
  tfjs-backend-webgl/src/reshape_packed_gpu.ts
  tfjs-backend-webgl/src/shader_compiler.ts
  tfjs-backend-webgl/src/shader_compiler_util.ts
Labels: cla: yes

#5426 Update BAZEL_MIGRATION.md
  BAZEL_MIGRATION.md
Labels: cla: yes

#5423 Fix GCP Timeout for BrowserStack Nightly Benchmarks
  e2e/benchmarks/browserstack-benchmark/app.js
  e2e/benchmarks/browserstack-benchmark/app_node_test.js
  e2e/benchmarks/browserstack-benchmark/cloudbuild.yml
  e2e/benchmarks/browserstack-benchmark/firestore.js
  e2e/benchmarks/browserstack-benchmark/karma.conf.js
  e2e/benchmarks/browserstack-benchmark/package.json
Labels: cla: yes

#5427 Update README.md
  tfjs-node/README.md
Labels: cla: yes

#5428 [webgpu] Remove tfjs-backend-webgl and tfjs-converter dependency
  scripts/cloudbuild_tfjs_core_expected.yml
  scripts/package_dependencies.json
  tfjs-backend-webgpu/package.json
  tfjs-backend-webgpu/src/backend_webgpu_test.ts
  tfjs-backend-webgpu/src/benchmark_models_test.ts
  tfjs-backend-webgpu/src/setup_test.ts
  tfjs-backend-webgpu/yarn.lock
Labels: bazel, cla: yes

#5443 Extend default web test timeout to 15 minutes
  tools/karma_template.conf.js
  tools/tfjs_web_test.bzl
Labels: cla: yes

#5444 [tfjs-data] Fix an issue caused by incorrectly cloning certain iterator
  tfjs-backend-webgl/yarn.lock
  tfjs-data/src/datasets/csv_dataset_test.ts
  tfjs-data/src/iterators/lazy_iterator_test.ts
  tfjs-data/src/util/deep_map.ts
Labels: cla: yes

#5322 [webgpu] Add binary WGSL support
  tfjs-backend-webgpu/src/kernels/activation_util.ts
  tfjs-backend-webgpu/src/kernels/binary_op_complex_webgpu.ts
  tfjs-backend-webgpu/src/kernels/binary_op_shared_webgpu.ts
  tfjs-backend-webgpu/src/kernels/binary_op_util.ts
  tfjs-backend-webgpu/src/kernels/binary_op_vec4_webgpu.ts
  tfjs-backend-webgpu/src/kernels/binary_op_webgpu.ts
  tfjs-backend-webgpu/src/kernels/unary_op_webgpu.ts
  tfjs-backend-webgpu/src/shader_preprocessor_wgsl.ts
  tfjs-backend-webgpu/src/webgpu_util_wgsl.ts
Labels: cla: yes

#5430 Use ImportToTexture to handle video in FromPixels
  tfjs-backend-webgpu/src/backend_webgpu.ts
  tfjs-backend-webgpu/src/flags_webgpu.ts
  tfjs-backend-webgpu/src/kernels/FromPixels.ts
  tfjs-backend-webgpu/src/kernels/FromPixelsExternalImage.ts
  tfjs-backend-webgpu/src/kernels/FromPixels_utils/from_pixels_import_webgpu.ts
  tfjs-backend-webgpu/src/kernels/FromPixels_utils/from_pixels_webgpu.ts
  tfjs-backend-webgpu/src/shader_preprocessor_wgsl.ts
  tfjs-backend-webgpu/src/webgpu_util.ts
Labels: cla: yes

#5455 Use a different symlink prefix for wasm builds
  tfjs-backend-wasm/scripts/build-wasm.sh
Labels: cla: yes

#5457 [tflite] Update google storage location
  tfjs-tflite/scripts/download-tflite-web-api.sh
Labels: cla: yes

#5451 Make Bazel npm outputs match current packages
  BAZEL_MIGRATION.md
  e2e/scripts/test-ci.sh
  e2e/scripts/test.sh
  e2e/webpack_test/app.js
  e2e/webpack_test/package.json
  e2e/webpack_test/webpack.config.js
  e2e/webpack_test/yarn.lock
  tfjs-backend-cpu/BUILD.bazel
  tfjs-backend-cpu/package.json
  tfjs-backend-webgl/BUILD.bazel
  tfjs-backend-webgl/package.json
  tfjs-core/BUILD.bazel
  tfjs-core/package.json
  tfjs-core/src/BUILD.bazel
  tfjs-layers/yarn.lock
  tfjs-tflite/BUILD.bazel
  tfjs-tflite/package.json
  tools/BUILD.bazel
  tools/copy_to_dist.bzl
  tools/enumerate-tests.ts
  tools/make_version_test_file.bzl
  tools/make_version_test_file.ts
  tools/ts_library_outputs.bzl
Labels: cla: yes

#5462 [webgpu] Fix wrongly modified NaN type
  tfjs-backend-webgpu/src/shader_preprocessor_wgsl.ts
Labels: cla: yes

#5474 [docs] Fix wrong ELU op definiton
  tfjs-core/src/ops/elu.ts
Labels: cla: yes

#5477 [wasm] Make it more obvious for calling setWasmPaths when WASM backend is loaded from script tag
  tfjs-backend-wasm/README.md
Labels: cla: yes

#5431 Switch between local build and remote build for benchmark tests
  e2e/benchmarks/local-benchmark/README.md
  e2e/benchmarks/local-benchmark/index.html
Labels: cla: yes

#5476 Revert "Build tfjs-backend-webgl with Bazel (#5339)"
  e2e/package.json
  e2e/scripts/publish-tfjs-ci.sh
  link-package/package.json
  link-package/yarn.lock
  package.json
  scripts/cloudbuild_tfjs_core_expected.yml
  scripts/cloudbuild_tfjs_node_expected.yml
  scripts/package_dependencies.json
  scripts/publish-npm.ts
  tfjs-backend-webgl/BUILD.bazel
  tfjs-backend-webgl/cloudbuild.yml
  tfjs-backend-webgl/package.json
  tfjs-backend-webgl/src/BUILD.bazel
  tfjs-backend-webgl/src/conv_packed_gpu_depthwise.ts
  tfjs-backend-webgl/src/kernels/Conv2D_test.ts
  tfjs-layers/package.json
  tfjs/package.json
  yarn.lock
Labels: cla: yes

#5478 [core] Add fallback logic for `isMobile`
  tfjs-core/src/device_util.ts
Labels: cla: yes

#4636 Add broadcast args
  tfjs-backend-cpu/src/kernels/BroadcastArgs.ts
  tfjs-backend-cpu/src/register_all_kernels.ts
  tfjs-backend-webgl/src/setup_test.ts
  tfjs-converter/docs/supported_ops.md
  tfjs-converter/metadata/kernel2op.json
  tfjs-converter/package.json
  tfjs-converter/python/tensorflowjs/op_list/transformation.json
  tfjs-converter/src/operations/executors/transformation_executor.ts
  tfjs-converter/src/operations/executors/transformation_executor_test.ts
  tfjs-converter/src/operations/op_list/transformation.ts
  tfjs-converter/yarn.lock
  tfjs-core/src/kernel_names.ts
  tfjs-core/src/ops/broadcast_args.ts
  tfjs-core/src/ops/broadcast_args_test.ts
  tfjs-core/src/ops/ops.ts
  tfjs-node/src/kernels/BroadcastArgs.ts
  tfjs-node/src/register_all_kernels.ts
Labels: cla: yes

#5480 [webgl] Temporarily disable WEBGL_USE_SHAPES_UNIFORMS tests
  tfjs-backend-webgl/scripts/test-ci.sh
Labels: cla: yes

#5437 Unpack input in ArgMin/Max WebGL kernel
  tfjs-backend-webgl/src/kernel_utils/arg_min_max.ts
  tfjs-backend-webgl/src/kernels/ArgMax_test.ts
  tfjs-backend-webgl/src/kernels/ArgMin_test.ts
Labels: cla: yes

#5483 webgl: Fix the incorrect result for blazeface
  tfjs-backend-webgl/src/im2col_packed_gpu.ts
  tfjs-backend-webgl/src/kernels/Conv2D_impl.ts
Labels: cla: yes

#5472 Fix FromPixels type checker to avoid error in worker
  tfjs-backend-webgpu/src/kernels/FromPixels.ts
Labels: cla: yes

#5500 [tfjs-webgl] fix depthwise conv2d bug
  tfjs-backend-webgl/src/conv_packed_gpu_depthwise.ts
  tfjs-core/src/ops/depthwise_conv2d_test.ts
Labels: cla: yes

#5499 Update package.json
  tfjs-node-gpu/package.json
  tfjs-node/package.json
Labels: cla: yes

#5369 [webgpu] Add conv2d vec4 and matmul vec4 WGSL support
  tfjs-backend-webgpu/src/kernels/BatchMatMul_impl.ts
  tfjs-backend-webgpu/src/kernels/Conv2D.ts
  tfjs-backend-webgpu/src/kernels/FusedConv2D.ts
  tfjs-backend-webgpu/src/kernels/binary_op_util.ts
  tfjs-backend-webgpu/src/kernels/conv2d_mm_vec4_webgpu.ts
  tfjs-backend-webgpu/src/kernels/matmul_packed_vec4_webgpu.ts
Labels: cla: yes

#5403 [webgpu] Add depthwise and other 21 programs WGSL support
  tfjs-backend-webgpu/src/kernels/addn_packed_webgpu.ts
  tfjs-backend-webgpu/src/kernels/batchnorm_webgpu.ts
  tfjs-backend-webgpu/src/kernels/clip_vec4_webgpu.ts
  tfjs-backend-webgpu/src/kernels/clip_webgpu.ts
  tfjs-backend-webgpu/src/kernels/concat_webgpu.ts
  tfjs-backend-webgpu/src/kernels/crop_and_resize_webgpu.ts
  tfjs-backend-webgpu/src/kernels/depthwise_conv2d_webgpu.ts
  tfjs-backend-webgpu/src/kernels/fill_webgpu.ts
  tfjs-backend-webgpu/src/kernels/gather_nd_webgpu.ts
  tfjs-backend-webgpu/src/kernels/gather_webgpu.ts
  tfjs-backend-webgpu/src/kernels/mirror_pad_webgpu.ts
  tfjs-backend-webgpu/src/kernels/pad_webgpu.ts
  tfjs-backend-webgpu/src/kernels/pool2d_webgpu.ts
  tfjs-backend-webgpu/src/kernels/pool_filtersizeone_webgpu.ts
  tfjs-backend-webgpu/src/kernels/pool_webgpu_test.ts
  tfjs-backend-webgpu/src/kernels/resize_bilinear_webgpu.ts
  tfjs-backend-webgpu/src/kernels/select_webgpu.ts
  tfjs-backend-webgpu/src/kernels/slice_webgpu.ts
  tfjs-backend-webgpu/src/kernels/strided_slice_webgpu.ts
  tfjs-backend-webgpu/src/kernels/tile_webgpu.ts
  tfjs-backend-webgpu/src/kernels/transform_webgpu.ts
  tfjs-backend-webgpu/src/kernels/transpose_shared_webgpu.ts
  tfjs-backend-webgpu/src/kernels/transpose_webgpu.ts
  tfjs-backend-webgpu/src/setup_test.ts
  tfjs-core/src/ops/avg_pool_test.ts
  tfjs-core/src/ops/clip_by_value_test.ts
Labels: cla: yes

#5510 [webgl] Fixed nightly test failure
  tfjs-backend-webgl/karma.conf.js
  tfjs-core/src/ops/from_pixels_async_test.ts
  tfjs-core/src/ops/from_pixels_test.ts
Labels: cla: yes

#5514 webgl: Use imod instead of mod
  tfjs-backend-webgl/src/im2col_packed_gpu.ts
  tfjs-backend-webgl/src/kernels/Conv2D_impl.ts
Labels: cla: yes

#5509 Fix string split call stack overflow
  tfjs-backend-cpu/src/kernels/StringSplit_impl.ts
  tfjs-core/src/ops/string/string_split_test.ts
Labels: cla: yes

#5511 [webgpu] Fix clipByValue vec4 error
  tfjs-backend-webgpu/src/kernels/clip_vec4_webgpu.ts
Labels: cla: yes

#5502 webgl: Fix the incorrect result with shapes uniforms
  tfjs-backend-webgl/scripts/test-ci.sh
  tfjs-backend-webgl/src/gpgpu_math.ts
  tfjs-backend-webgl/src/shader_compiler.ts
Labels: cla: yes

#5523 Minor fix for the NamedTensorInfoMap type.
  tfjs-core/src/kernel_registry.ts
Labels: cla: yes

#5521 webgpu: Fix the memory leak for Cast
  tfjs-backend-webgpu/karma.conf.js
  tfjs-backend-webgpu/src/kernels/Cast.ts
  tfjs-backend-webgpu/src/setup_test.ts
Labels: cla: yes

#5526 [webgpu] Fix warning that buffer binding size cannot be zero.
  tfjs-backend-webgpu/src/backend_webgpu.ts
  tfjs-backend-webgpu/src/kernels/FromPixels.ts
  tfjs-backend-webgpu/src/kernels/FromPixelsExternalImage.ts
  tfjs-backend-webgpu/src/setup_test.ts
Labels: cla: yes

#5505 [webgpu] update warning message to guide user enable timestamp-query …
  tfjs-backend-webgpu/src/index.ts
Labels: cla: yes

#5519 [webgpu] Fix exceed dispatch size on WGSL
  tfjs-backend-webgpu/src/kernels/addn_packed_webgpu.ts
  tfjs-backend-webgpu/src/kernels/batchnorm_webgpu.ts
  tfjs-backend-webgpu/src/kernels/binary_op_complex_webgpu.ts
  tfjs-backend-webgpu/src/kernels/binary_op_shared_webgpu.ts
  tfjs-backend-webgpu/src/kernels/binary_op_vec4_webgpu.ts
  tfjs-backend-webgpu/src/kernels/binary_op_webgpu.ts
  tfjs-backend-webgpu/src/kernels/clip_vec4_webgpu.ts
  tfjs-backend-webgpu/src/kernels/clip_webgpu.ts
  tfjs-backend-webgpu/src/kernels/concat_webgpu.ts
  tfjs-backend-webgpu/src/kernels/crop_and_resize_webgpu.ts
  tfjs-backend-webgpu/src/kernels/depthwise_conv2d_webgpu.ts
  tfjs-backend-webgpu/src/kernels/fill_webgpu.ts
  tfjs-backend-webgpu/src/kernels/gather_nd_webgpu.ts
  tfjs-backend-webgpu/src/kernels/gather_webgpu.ts
  tfjs-backend-webgpu/src/kernels/mirror_pad_webgpu.ts
  tfjs-backend-webgpu/src/kernels/pad_webgpu.ts
  tfjs-backend-webgpu/src/kernels/pool2d_webgpu.ts
  tfjs-backend-webgpu/src/kernels/pool_filtersizeone_webgpu.ts
  tfjs-backend-webgpu/src/kernels/resize_bilinear_webgpu.ts
  tfjs-backend-webgpu/src/kernels/select_webgpu.ts
  tfjs-backend-webgpu/src/kernels/slice_webgpu.ts
  tfjs-backend-webgpu/src/kernels/strided_slice_webgpu.ts
  tfjs-backend-webgpu/src/kernels/tile_webgpu.ts
  tfjs-backend-webgpu/src/kernels/transform_webgpu.ts
  tfjs-backend-webgpu/src/kernels/transpose_shared_webgpu.ts
  tfjs-backend-webgpu/src/kernels/transpose_webgpu.ts
  tfjs-backend-webgpu/src/kernels/unary_op_webgpu.ts
  tfjs-backend-webgpu/src/shader_preprocessor_wgsl.ts
Labels: cla: yes

#5525 webgl: Enable single run for yarn test
  tfjs-backend-webgl/karma.conf.js
Labels: cla: yes

#5503 [webgpu] Add time query profiling for fromPixels op
  tfjs-backend-webgpu/src/backend_webgpu.ts
  tfjs-backend-webgpu/src/kernels/FromPixelsExternalImage.ts
Labels: cla: yes

#5524 improving error message when input or dataset output shape does not match the inputShape
  tfjs-layers/src/engine/training.ts
  tfjs-layers/src/engine/training_test.ts
Labels: cla: yes

#5556 Fix publish script for Bazel packages
  scripts/publish-npm.ts
Labels: cla: yes

#5555 Update lockfiles branch tfjs_3.9.0_lockfiles lock files.
  tfjs-backend-wasm/yarn.lock
  tfjs-backend-webgl/yarn.lock
  tfjs-converter/yarn.lock
  tfjs-data/yarn.lock
  tfjs-layers/yarn.lock
  tfjs-node-gpu/yarn.lock
  tfjs-node/yarn.lock
  tfjs/yarn.lock
Labels: cla: yes, INTERNAL

#5342 webgpu: optimize matmul with small output size
  tfjs-backend-webgpu/src/kernels/BatchMatMul_impl.ts
  tfjs-backend-webgpu/src/kernels/matmul_small_output_size_webgpu.ts
Labels: cla: yes

#5535 [webgpu] Add depthwise3x3/argminmax/reduce/resize_nearest_neighbor WGSL support
  tfjs-backend-webgpu/src/kernels/argminmax_webgpu.ts
  tfjs-backend-webgpu/src/kernels/depthwise_conv2d_3x3_webgpu.ts
  tfjs-backend-webgpu/src/kernels/depthwise_conv2d_webgpu.ts
  tfjs-backend-webgpu/src/kernels/reduce_webgpu.ts
  tfjs-backend-webgpu/src/kernels/resize_nearest_neighbor_webgpu.ts
  tfjs-backend-webgpu/src/shader_preprocessor_wgsl.ts
Labels: cla: yes

#5558 Update CONTRIBUTING_MISSING_OP.md
  CONTRIBUTING_MISSING_OP.md
  README.md
Labels: cla: yes
