Repository tensorflow/tfjs, pull requests merged in 2021-12, with the labels that each got.

#5899 [tfjs-node] support M1 with TF darwin-arm64 build
  tfjs-node/scripts/deps-constants.js
  tfjs-node/scripts/install.js
Labels: cla: yes

#5870 [benchmark] Add initial support for tflite models
  e2e/benchmarks/local-benchmark/index.html
  e2e/benchmarks/local-benchmark/index.js
  e2e/benchmarks/local-benchmark/main.css
  e2e/benchmarks/model_config.js
  e2e/scripts/deploy-benchmarks.sh
Labels: cla: yes

#5905 [webgpu] Add program label for shader
  tfjs-backend-webgpu/src/kernels/webgpu_program.ts
Labels: cla: yes

#5911 [tflite] Add profiling related APIs to tfjs-tflite
  tfjs-tflite/README.md
  tfjs-tflite/scripts/download-tflite-web-api.sh
  tfjs-tflite/src/tflite_model.ts
  tfjs-tflite/src/tflite_model_test.ts
  tfjs-tflite/src/types/tflite_web_model_runner.ts
Labels: cla: yes

#5916 Update tfjs-tflite to 0.0.1-alpha.8.
  tfjs-tflite/package.json
  tfjs-tflite/src/version.ts
  tfjs-tflite/yarn.lock
Labels: cla: yes, INTERNAL

#5917 [benchmark] Support collecting and showing per-op stats (latency for now) for tflite models in benchmark tool
  e2e/benchmarks/benchmark_util.js
  e2e/benchmarks/local-benchmark/index.html
  e2e/benchmarks/model_config.js
Labels: cla: yes

#5926 Update monorepo to 3.12.0.
  tfjs-backend-cpu/package.json
  tfjs-backend-cpu/src/version.ts
  tfjs-backend-wasm/package.json
  tfjs-backend-wasm/src/version.ts
  tfjs-backend-webgl/package.json
  tfjs-backend-webgl/src/version.ts
  tfjs-converter/package.json
  tfjs-converter/python/BUILD
  tfjs-converter/python/tensorflowjs/version.py
  tfjs-converter/src/version.ts
  tfjs-core/package.json
  tfjs-core/src/version.ts
  tfjs-data/package.json
  tfjs-data/src/version.ts
  tfjs-layers/package.json
  tfjs-layers/src/version.ts
  tfjs-node-gpu/package.json
  tfjs-node/package.json
  tfjs-node/src/version.ts
  tfjs/package.json
  tfjs/src/version.ts
Labels: INTERNAL

#5929 Update lockfiles branch tfjs_3.12.0_lockfiles lock files.
  tfjs-backend-cpu/yarn.lock
  tfjs-backend-wasm/yarn.lock
  tfjs-backend-webgl/yarn.lock
  tfjs-converter/yarn.lock
  tfjs-data/yarn.lock
  tfjs-layers/yarn.lock
  tfjs-node-gpu/yarn.lock
  tfjs-node/yarn.lock
  tfjs/yarn.lock
Labels: INTERNAL
