Repository tensorflow/tfjs, pull requests merged in 2021-01, with the labels that each got.

#4455 refactor runKernel/runKernelFunc signature and internals.
  tfjs-core/src/engine.ts
  tfjs-core/src/kernel_registry_test.ts
Labels: cla: yes

#4469 remove mkdirp dependency in custom_module
  tfjs/package.json
  tfjs/tools/custom_module/cli.ts
  tfjs/tools/custom_module/esm_module_provider.ts
  tfjs/tools/custom_module/model_parser.ts
  tfjs/tools/custom_module/util.ts
  tfjs/yarn.lock
Labels: cla: yes

#4470 remove ops from backend interface [3.x_dev]
  tfjs-core/src/backends/backend.ts
  tfjs-core/src/backends/backend_util.ts
Labels: cla: yes

#4471 add fesm browser builds to packages [3.x_dev]
  rollup.config.helpers.js
  tfjs-backend-cpu/rollup.config.js
  tfjs-backend-wasm/package.json
  tfjs-backend-wasm/rollup.config.js
  tfjs-backend-wasm/yarn.lock
  tfjs-backend-webgl/rollup.config.js
  tfjs-converter/rollup.config.js
  tfjs-core/rollup.config.js
  tfjs-data/rollup.config.js
  tfjs-layers/rollup.config.js
  tfjs/rollup.config.js
Labels: cla: yes

#4486 [wasm] Implement the Round kernel
  tfjs-backend-wasm/src/cc/kernels/Round.cc
  tfjs-backend-wasm/src/kernels/Round.ts
  tfjs-backend-wasm/src/register_all_kernels.ts
  tfjs-backend-wasm/src/setup_test.ts
Labels: cla: yes

#4487 make RNNCell more compatible with ts 4.0
  tfjs-layers/src/layers/recurrent.ts
  tfjs-layers/src/layers/recurrent_test.ts
Labels: cla: yes

#4485 initialize/set backend in runKernelFunc
  tfjs-core/src/engine.ts
Labels: cla: yes

#4490 fix worker test [3.x_dev]
  tfjs-core/src/worker_test.ts
Labels: cla: yes

#4374 Use CopyImageBitmapToTexture for webgpu backend
  tfjs-backend-webgl/src/kernels/FromPixels.ts
  tfjs-backend-webgpu/src/kernels/FromPixels.ts
  tfjs-backend-webgpu/src/kernels/FromPixelsAsync.ts
  tfjs-backend-webgpu/src/kernels/FromPixelsImageBitmap.ts
  tfjs-backend-webgpu/src/kernels/FromPixels_utils/from_pixels_webgpu.ts
  tfjs-core/src/kernel_names.ts
  tfjs-core/src/ops/browser.ts
  tfjs-core/src/ops/from_pixels_test.ts
Labels: cla: yes

#4478 [webgl] Fixed split issue with negative axis.
  tfjs-backend-wasm/src/kernels/SplitV.ts
  tfjs-backend-webgl/src/kernels/SplitV.ts
  tfjs-core/src/ops/split_test.ts
Labels: cla: yes

#4496 enable createImageBitmap test only for chrome
  tfjs-core/src/ops/from_pixels_test.ts
Labels: cla: yes

#4495 Update monorepo to 3.0.0-rc.0.
  tfjs-backend-cpu/package.json
  tfjs-backend-cpu/src/version.ts
  tfjs-backend-wasm/package.json
  tfjs-backend-wasm/src/version.ts
  tfjs-backend-webgl/package.json
  tfjs-backend-webgl/src/version.ts
  tfjs-converter/package.json
  tfjs-converter/python/tensorflowjs/version.py
  tfjs-converter/src/version.ts
  tfjs-core/package.json
  tfjs-core/src/version.ts
  tfjs-data/package.json
  tfjs-data/src/version.ts
  tfjs-layers/package.json
  tfjs-layers/src/version.ts
  tfjs-node-gpu/package.json
  tfjs-node/package.json
  tfjs-node/src/version.ts
  tfjs/package.json
  tfjs/src/version.ts
Labels: INTERNAL, cla: yes

#4501 Update lockfiles branch tfjs_3.0.0-rc.0_lockfiles lock files.
  tfjs-backend-cpu/yarn.lock
  tfjs-backend-wasm/yarn.lock
  tfjs-backend-webgl/yarn.lock
  tfjs-converter/yarn.lock
  tfjs-data/yarn.lock
  tfjs-layers/yarn.lock
  tfjs-node-gpu/yarn.lock
  tfjs-node/yarn.lock
  tfjs/yarn.lock
Labels: INTERNAL, cla: yes

#4503 Update monorepo to 2.8.3.
  tfjs-backend-cpu/package.json
  tfjs-backend-cpu/src/version.ts
  tfjs-backend-wasm/package.json
  tfjs-backend-wasm/src/version.ts
  tfjs-backend-webgl/package.json
  tfjs-backend-webgl/src/version.ts
  tfjs-converter/package.json
  tfjs-converter/python/tensorflowjs/version.py
  tfjs-converter/src/version.ts
  tfjs-core/package.json
  tfjs-core/src/version.ts
  tfjs-data/package.json
  tfjs-data/src/version.ts
  tfjs-layers/package.json
  tfjs-layers/src/version.ts
  tfjs-node-gpu/package.json
  tfjs-node/package.json
  tfjs-node/src/version.ts
  tfjs/package.json
  tfjs/src/version.ts
Labels: INTERNAL, cla: yes

#4505 Update lockfiles branch tfjs_2.8.3_lockfiles lock files.
  tfjs-backend-cpu/yarn.lock
  tfjs-backend-wasm/yarn.lock
  tfjs-backend-webgl/yarn.lock
  tfjs-converter/yarn.lock
  tfjs-data/yarn.lock
  tfjs-layers/yarn.lock
  tfjs-node-gpu/yarn.lock
  tfjs-node/yarn.lock
  tfjs/yarn.lock
Labels: INTERNAL, cla: yes

#4504 implement step for wasm
  tfjs-backend-wasm/src/cc/BUILD
  tfjs-backend-wasm/src/cc/kernels/Step.cc
  tfjs-backend-wasm/src/kernels/Step.ts
  tfjs-backend-wasm/src/register_all_kernels.ts
  tfjs-backend-wasm/src/setup_test.ts
  tfjs-core/src/ops/step_test.ts
Labels: cla: yes

#4506 Update layers browserstack configurations.
  tfjs-layers/karma.conf.js
Labels: cla: yes

#4513 Add safeguard to initializer field.
  tfjs-converter/python/tensorflowjs/converters/tf_saved_model_conversion_v2.py
Labels: cla: yes

#4512 Update tfjs-inference
  tfjs-inference/package.json
  tfjs-inference/src/file_handler.ts
  tfjs-inference/src/file_handler_test.ts
  tfjs-inference/src/index.ts
  tfjs-inference/yarn.lock
Labels: cla: yes

#4492 webgpu: Fix the incorrect use of setFlags
  tfjs-backend-webgpu/src/index.ts
  tfjs-backend-webgpu/src/setup_test.ts
Labels: cla: yes

#4518 Avoid building tfjs-core twice in CI
  tfjs-core/cloudbuild.yml
  tfjs-core/package.json
Labels: cla: yes

#4499 Update FromPixelsImageBitmap Pipeline Cache Strategy
  tfjs-backend-webgpu/src/backend_webgpu.ts
  tfjs-backend-webgpu/src/kernels/FromPixelsImageBitmap.ts
  tfjs-backend-webgpu/src/kernels/FromPixels_utils/from_pixels_webgpu.ts
  tfjs-core/src/ops/from_pixels_test.ts
Labels: cla: yes

#4482 [webgpu] Support fused conv2d vec4
  tfjs-backend-webgpu/src/backend_webgpu.ts
  tfjs-backend-webgpu/src/kernels/conv2d_mm_vec4_webgpu.ts
  tfjs-backend-webgpu/src/kernels/unary_op_webgpu.ts
Labels: cla: yes

#4468 webgpu: add fusedDepthwiseConv2D operator
  tfjs-backend-webgpu/src/kernels/FusedDepthwiseConv2D.ts
  tfjs-backend-webgpu/src/kernels/depthwise_conv2d_webgpu.ts
  tfjs-backend-webgpu/src/kernels/unary_op_webgpu.ts
  tfjs-backend-webgpu/src/register_all_kernels.ts
  tfjs-backend-webgpu/src/setup_test.ts
Labels: cla: yes

#4519 Style fix to be consistent with g3.
  tfjs-inference/python/inference.py
  tfjs-inference/src/index.ts
Labels: cla: yes

#4523 Always test generate-cloudbuild against the golden files
  scripts/cloudbuild.yml
  scripts/cloudbuild_general_config.yml
  scripts/cloudbuild_tfjs_core_expected.yml
  scripts/cloudbuild_tfjs_node_expected.yml
  scripts/package_dependencies.json
  tfjs-inference/cloudbuild.yml
  tfjs-inference/package.json
Labels: cla: yes

#4526 sync master to 3.x_dev
  scripts/cloudbuild.yml
  scripts/cloudbuild_general_config.yml
  scripts/cloudbuild_tfjs_core_expected.yml
  scripts/cloudbuild_tfjs_node_expected.yml
  scripts/package_dependencies.json
  tfjs-backend-wasm/src/cc/BUILD
  tfjs-backend-wasm/src/cc/kernels/Step.cc
  tfjs-backend-wasm/src/kernels/SplitV.ts
  tfjs-backend-wasm/src/kernels/Step.ts
  tfjs-backend-wasm/src/register_all_kernels.ts
  tfjs-backend-wasm/src/setup_test.ts
  tfjs-backend-webgl/src/kernels/Bincount.ts
  tfjs-backend-webgl/src/kernels/Concat_impl.ts
  tfjs-backend-webgl/src/kernels/DenseBincount.ts
  tfjs-backend-webgl/src/kernels/FromPixels.ts
  tfjs-backend-webgl/src/kernels/SplitV.ts
  tfjs-backend-webgl/src/kernels/Tile.ts
  tfjs-backend-webgl/src/kernels/TopK.ts
  tfjs-backend-webgpu/src/backend_webgpu.ts
  tfjs-backend-webgpu/src/index.ts
  tfjs-backend-webgpu/src/kernels/FromPixels.ts
  tfjs-backend-webgpu/src/kernels/FromPixelsAsync.ts
  tfjs-backend-webgpu/src/kernels/FromPixelsImageBitmap.ts
  tfjs-backend-webgpu/src/kernels/FromPixels_utils/from_pixels_webgpu.ts
  tfjs-backend-webgpu/src/kernels/FusedDepthwiseConv2D.ts
  tfjs-backend-webgpu/src/kernels/conv2d_mm_vec4_webgpu.ts
  tfjs-backend-webgpu/src/kernels/depthwise_conv2d_webgpu.ts
  tfjs-backend-webgpu/src/kernels/unary_op_webgpu.ts
  tfjs-backend-webgpu/src/register_all_kernels.ts
  tfjs-backend-webgpu/src/setup_test.ts
  tfjs-converter/python/tensorflowjs/converters/tf_saved_model_conversion_v2.py
  tfjs-core/cloudbuild.yml
  tfjs-core/package.json
  tfjs-core/src/engine.ts
  tfjs-core/src/kernel_names.ts
  tfjs-core/src/ops/bincount_test.ts
  tfjs-core/src/ops/browser.ts
  tfjs-core/src/ops/dense_bincount_test.ts
  tfjs-core/src/ops/from_pixels_test.ts
  tfjs-core/src/ops/split_test.ts
  tfjs-core/src/ops/step_test.ts
  tfjs-core/src/ops/topk_test.ts
  tfjs-inference/cloudbuild.yml
  tfjs-inference/package.json
  tfjs-inference/python/inference.py
  tfjs-inference/src/file_handler.ts
  tfjs-inference/src/file_handler_test.ts
  tfjs-inference/src/index.ts
  tfjs-inference/yarn.lock
  tfjs-layers/karma.conf.js
  tfjs/integration_tests/python/requirements.txt
Labels: cla: no

#4521 webgpu: Fix shader compile error when using fused conv2d
  tfjs-backend-webgpu/src/backend_webgpu.ts
  tfjs-backend-webgpu/src/kernels/unary_op_webgpu.ts
  tfjs-core/src/ops/fused/fused_conv2d_test.ts
Labels: cla: yes

#4528 [wasm] Fix "_scriptDir not defined" error when used in webworker
  tfjs-backend-wasm/src/backend_wasm.ts
  tfjs-backend-wasm/src/cc/BUILD
  tfjs-backend-wasm/toolchain/emscripten_threaded_module_prejs.js
Labels: cla: yes

#4527 remove deprecated ops and params [3.x_dev]
  tfjs-backend-cpu/src/kernels/AvgPool3D.ts
  tfjs-backend-cpu/src/kernels/AvgPool3DGrad.ts
  tfjs-backend-cpu/src/kernels/MaxPool3D.ts
  tfjs-backend-cpu/src/kernels/MaxPool3DGrad.ts
  tfjs-core/src/gradients/AvgPool3D_grad.ts
  tfjs-core/src/gradients/MaxPool3D_grad.ts
  tfjs-core/src/kernel_names.ts
  tfjs-core/src/ops/avg_pool_3d.ts
  tfjs-core/src/ops/avg_pool_3d_grad.ts
  tfjs-core/src/ops/max_pool_3d.ts
  tfjs-core/src/ops/max_pool_3d_grad.ts
  tfjs-core/src/public/chained_ops/depthwise_conv2D_deprecated.ts
  tfjs-core/src/public/chained_ops/register_all_chained_ops.ts
  tfjs-core/src/public/chained_ops/register_all_chained_ops_test.ts
  tfjs-node/src/kernels/AvgPool3D.ts
  tfjs-node/src/kernels/AvgPool3DGrad.ts
  tfjs-node/src/kernels/MaxPool3D.ts
  tfjs-node/src/kernels/MaxPool3DGrad.ts
Labels: cla: yes

#4533 Update monorepo to 2.8.4.
  tfjs-backend-cpu/package.json
  tfjs-backend-cpu/src/version.ts
  tfjs-backend-wasm/package.json
  tfjs-backend-wasm/src/version.ts
  tfjs-backend-webgl/package.json
  tfjs-backend-webgl/src/version.ts
  tfjs-converter/package.json
  tfjs-converter/python/tensorflowjs/version.py
  tfjs-converter/src/version.ts
  tfjs-core/package.json
  tfjs-core/src/version.ts
  tfjs-data/package.json
  tfjs-data/src/version.ts
  tfjs-layers/package.json
  tfjs-layers/src/version.ts
  tfjs-node-gpu/package.json
  tfjs-node/package.json
  tfjs-node/src/version.ts
  tfjs/package.json
  tfjs/src/version.ts
Labels: INTERNAL, cla: yes

#4535 Update lockfiles branch tfjs_2.8.4_lockfiles lock files.
  tfjs-backend-cpu/yarn.lock
  tfjs-backend-wasm/yarn.lock
  tfjs-backend-webgl/yarn.lock
  tfjs-converter/yarn.lock
  tfjs-data/yarn.lock
  tfjs-layers/yarn.lock
  tfjs-node-gpu/yarn.lock
  tfjs-node/yarn.lock
  tfjs/yarn.lock
Labels: INTERNAL, cla: yes

#4536 sync master to 3.x_dev
  tfjs-backend-wasm/src/backend_wasm.ts
  tfjs-backend-webgpu/src/backend_webgpu.ts
  tfjs-backend-webgpu/src/kernels/unary_op_webgpu.ts
  tfjs-core/src/engine.ts
  tfjs-core/src/ops/fused/fused_conv2d_test.ts
Labels: cla: no

#4538 Update package.json
  tfjs-node-gpu/package.json
  tfjs-node/package.json
Labels: cla: yes

#4541 Update monorepo to 3.0.0-rc.1.
  tfjs-backend-cpu/package.json
  tfjs-backend-cpu/src/version.ts
  tfjs-backend-wasm/package.json
  tfjs-backend-wasm/src/version.ts
  tfjs-backend-webgl/package.json
  tfjs-backend-webgl/src/version.ts
  tfjs-converter/package.json
  tfjs-converter/python/tensorflowjs/version.py
  tfjs-converter/src/version.ts
  tfjs-core/package.json
  tfjs-core/src/version.ts
  tfjs-data/package.json
  tfjs-data/src/version.ts
  tfjs-layers/package.json
  tfjs-layers/src/version.ts
  tfjs-node-gpu/package.json
  tfjs-node/package.json
  tfjs-node/src/version.ts
  tfjs/package.json
  tfjs/src/version.ts
Labels: INTERNAL, cla: yes

#4446 Add shuffleCombo
  tfjs-core/src/util_base.ts
  tfjs-core/src/util_test.ts
Labels: cla: yes

#4562 Fix WASM JS script not working after minification
  rollup.config.helpers.js
  tfjs-backend-wasm/README.md
  tfjs-backend-wasm/package.json
  tfjs-backend-wasm/rollup.config.js
  tfjs-backend-wasm/scripts/build-wasm.sh
  tfjs-backend-wasm/scripts/patch-threaded-simd-module.js
  tfjs-backend-wasm/src/backend_wasm.ts
Labels: cla: yes

#4563 Fix memory leak for complex tensors
  tfjs-backend-cpu/src/kernels/Complex_test.ts
  tfjs-backend-cpu/src/kernels/STFT_test.ts
  tfjs-backend-webgl/src/backend_webgl.ts
  tfjs-backend-webgl/src/kernels/Complex_test.ts
  tfjs-backend-webgl/src/kernels/FFT_impl.ts
  tfjs-backend-webgl/src/kernels/STFT_test.ts
  tfjs-backend-webgl/src/kernels/Slice.ts
  tfjs-core/src/backends/backend.ts
  tfjs-core/src/engine.ts
  tfjs-core/src/engine_test.ts
Labels: cla: yes

#4564 Fix memory leak for complex tensors (#4563)
  tfjs-backend-cpu/src/kernels/Complex_test.ts
  tfjs-backend-cpu/src/kernels/STFT_test.ts
  tfjs-backend-webgl/src/backend_webgl.ts
  tfjs-backend-webgl/src/kernels/Complex_test.ts
  tfjs-backend-webgl/src/kernels/FFT_impl.ts
  tfjs-backend-webgl/src/kernels/STFT_test.ts
  tfjs-backend-webgl/src/kernels/Slice.ts
  tfjs-core/src/backends/backend.ts
  tfjs-core/src/engine.ts
  tfjs-core/src/engine_test.ts
Labels: cla: no

#4569 Cherry pick PR 4562 into master to fix WASM not working after minification
  rollup.config.helpers.js
  tfjs-backend-wasm/README.md
  tfjs-backend-wasm/rollup.config.js
  tfjs-backend-wasm/scripts/build-wasm.sh
  tfjs-backend-wasm/scripts/patch-threaded-simd-module.js
  tfjs-backend-wasm/src/backend_wasm.ts
Labels: cla: yes

#4571 Update monorepo to 2.8.5.
  tfjs-backend-cpu/package.json
  tfjs-backend-cpu/src/version.ts
  tfjs-backend-wasm/package.json
  tfjs-backend-wasm/src/version.ts
  tfjs-backend-webgl/package.json
  tfjs-backend-webgl/src/version.ts
  tfjs-converter/package.json
  tfjs-converter/python/tensorflowjs/version.py
  tfjs-converter/src/version.ts
  tfjs-core/package.json
  tfjs-core/src/version.ts
  tfjs-data/package.json
  tfjs-data/src/version.ts
  tfjs-layers/package.json
  tfjs-layers/src/version.ts
  tfjs-node-gpu/package.json
  tfjs-node/package.json
  tfjs-node/src/version.ts
  tfjs/package.json
  tfjs/src/version.ts
Labels: INTERNAL, cla: yes

#4561 Update lockfiles branch tfjs_3.0.0-rc.1_lockfiles lock files.
  tfjs-backend-cpu/yarn.lock
  tfjs-backend-wasm/yarn.lock
  tfjs-backend-webgl/yarn.lock
  tfjs-converter/yarn.lock
  tfjs-data/yarn.lock
  tfjs-layers/yarn.lock
  tfjs-node-gpu/yarn.lock
  tfjs-node/yarn.lock
  tfjs/yarn.lock
Labels: INTERNAL, cla: yes

#4573 Update lockfiles branch tfjs_2.8.5_lockfiles lock files.
  tfjs-backend-cpu/yarn.lock
  tfjs-backend-wasm/yarn.lock
  tfjs-backend-webgl/yarn.lock
  tfjs-converter/yarn.lock
  tfjs-data/yarn.lock
  tfjs-layers/yarn.lock
  tfjs-node-gpu/yarn.lock
  tfjs-node/yarn.lock
  tfjs/yarn.lock
Labels: INTERNAL, cla: yes

#4532 WebGPU: Add computeWorkGroupSizeForMatMul helper function
  tfjs-backend-webgpu/src/kernels/matmul_packed_vec4_webgpu.ts
  tfjs-backend-webgpu/src/webgpu_util.ts
Labels: cla: yes

#4583 Update README.md
  tfjs-converter/README.md
Labels: cla: yes

#4577 webgpu: add fusedBatchMatmul
  tfjs-backend-webgpu/src/backend_webgpu.ts
  tfjs-backend-webgpu/src/flags_webgpu.ts
  tfjs-backend-webgpu/src/kernels/conv2d_mm_webgpu.ts
  tfjs-backend-webgpu/src/kernels/conv2d_naive_webgpu.ts
  tfjs-backend-webgpu/src/kernels/matmul_packed_vec4_webgpu.ts
  tfjs-backend-webgpu/src/kernels/matmul_packed_webgpu.ts
  tfjs-backend-webgpu/src/kernels/matmul_webgpu.ts
  tfjs-backend-webgpu/src/setup_test.ts
Labels: cla: yes

#4576 Support input size for e2e
  e2e/benchmarks/local-benchmark/index.html
  e2e/benchmarks/model_config.js
Labels: cla: yes

#4575 Update dataset_stub.ts
  tfjs-layers/src/engine/dataset_stub.ts
Labels: cla: yes

#4582 add return type for kernelNames getter
  tfjs-core/src/engine.ts
Labels: cla: yes

#4588 Update README.md
  tfjs-converter/README.md
Labels: cla: yes

#4597 Update monorepo to 3.0.0.
  tfjs-backend-cpu/package.json
  tfjs-backend-cpu/src/version.ts
  tfjs-backend-wasm/package.json
  tfjs-backend-wasm/src/version.ts
  tfjs-backend-webgl/package.json
  tfjs-backend-webgl/src/version.ts
  tfjs-converter/package.json
  tfjs-converter/python/tensorflowjs/version.py
  tfjs-converter/src/version.ts
  tfjs-core/package.json
  tfjs-core/src/version.ts
  tfjs-data/package.json
  tfjs-data/src/version.ts
  tfjs-layers/package.json
  tfjs-layers/src/version.ts
  tfjs-node-gpu/package.json
  tfjs-node/package.json
  tfjs-node/src/version.ts
  tfjs/package.json
  tfjs/src/version.ts
Labels: INTERNAL, cla: yes

#4590 Remove tfjs-core as tfjs-node(-gpu) dependency
  scripts/cloudbuild_tfjs_core_expected.yml
  scripts/cloudbuild_tfjs_node_expected.yml
  scripts/package_dependencies.json
  scripts/release-util.ts
  tfjs-node-gpu/package.json
  tfjs-node/package.json
  tfjs-node/src/kernels/Identity.ts
  tfjs-node/src/kernels/Pack.ts
  tfjs-node/src/register_all_kernels.ts
Labels: cla: yes

#4598 Update lockfiles branch tfjs_3.0.0_lockfiles lock files.
  tfjs-backend-cpu/yarn.lock
  tfjs-backend-wasm/yarn.lock
  tfjs-backend-webgl/yarn.lock
  tfjs-converter/yarn.lock
  tfjs-data/yarn.lock
  tfjs-layers/yarn.lock
  tfjs-node-gpu/yarn.lock
  tfjs-node/yarn.lock
  tfjs/yarn.lock
Labels: INTERNAL, cla: yes

#4599 docs: remove duplicate documentation line
  tfjs-react-native/README.md
Labels: cla: yes

#4602 fix webgl cumsum kernel
  tfjs-backend-webgl/src/kernels/Cumsum.ts
  tfjs-core/src/ops/cumsum_test.ts
Labels: cla: yes

#4601 update tfjs-vis devDependency to tfjs 3.0.0
  tfjs-vis/demos/api/README.md
  tfjs-vis/demos/api/package.json
  tfjs-vis/demos/api/yarn.lock
  tfjs-vis/demos/mnist/README.md
  tfjs-vis/demos/mnist/package.json
  tfjs-vis/demos/mnist/yarn.lock
  tfjs-vis/demos/mnist_internals/README.md
  tfjs-vis/demos/mnist_internals/package.json
  tfjs-vis/demos/mnist_internals/yarn.lock
  tfjs-vis/package.json
  tfjs-vis/yarn.lock
Labels: cla: yes

#4585 webgpu: Refactor WebGPUProgram (part 1)
  tfjs-backend-webgpu/src/kernels/binary_op_shared_webgpu.ts
  tfjs-backend-webgpu/src/kernels/binary_op_vec4_webgpu.ts
  tfjs-backend-webgpu/src/kernels/binary_op_webgpu.ts
  tfjs-backend-webgpu/src/kernels/conv2d_mm_vec4_webgpu.ts
  tfjs-backend-webgpu/src/kernels/conv2d_mm_webgpu.ts
  tfjs-backend-webgpu/src/kernels/conv2d_naive_webgpu.ts
  tfjs-backend-webgpu/src/kernels/matmul_packed_vec4_webgpu.ts
  tfjs-backend-webgpu/src/kernels/matmul_packed_webgpu.ts
  tfjs-backend-webgpu/src/kernels/maxpool_filtersizeone_webgpu.ts
  tfjs-backend-webgpu/src/kernels/pool2d_webgpu.ts
  tfjs-backend-webgpu/src/kernels/unary_op_webgpu.ts
  tfjs-backend-webgpu/src/kernels/webgpu_program.ts
  tfjs-backend-webgpu/src/shader_preprocessor.ts
Labels: cla: yes

#4584 Support bodypix input size
  e2e/benchmarks/local-benchmark/index.html
  e2e/benchmarks/model_config.js
Labels: cla: yes

#4607 tfjs-vis heatmap: disable vega-lite sorting of ticklabels
  tfjs-vis/demos/api/index.html
  tfjs-vis/src/render/heatmap.ts
Labels: cla: yes

#4608 Update tfjs-vis to 1.5.0.
  tfjs-vis/package.json
  tfjs-vis/src/version.ts
Labels: INTERNAL, cla: yes

#4604 webgpu: Refactor WebGPUProgram (part 2)
  tfjs-backend-webgpu/src/kernels/FromPixels_utils/from_pixels_webgpu.ts
  tfjs-backend-webgpu/src/kernels/argminmax_webgpu.ts
  tfjs-backend-webgpu/src/kernels/batchnorm_webgpu.ts
  tfjs-backend-webgpu/src/kernels/binary_op_shared_webgpu.ts
  tfjs-backend-webgpu/src/kernels/binary_op_vec4_webgpu.ts
  tfjs-backend-webgpu/src/kernels/binary_op_webgpu.ts
  tfjs-backend-webgpu/src/kernels/clip_vec4_webgpu.ts
  tfjs-backend-webgpu/src/kernels/clip_webgpu.ts
  tfjs-backend-webgpu/src/kernels/concat_webgpu.ts
  tfjs-backend-webgpu/src/kernels/conv2d_mm_vec4_webgpu.ts
  tfjs-backend-webgpu/src/kernels/conv2d_mm_webgpu.ts
  tfjs-backend-webgpu/src/kernels/conv2d_naive_webgpu.ts
  tfjs-backend-webgpu/src/kernels/crop_and_resize_webgpu.ts
  tfjs-backend-webgpu/src/kernels/depthwise_conv2d_webgpu.ts
  tfjs-backend-webgpu/src/kernels/fill_webgpu.ts
  tfjs-backend-webgpu/src/kernels/im2col_webgpu.ts
  tfjs-backend-webgpu/src/kernels/matmul_packed_vec4_webgpu.ts
  tfjs-backend-webgpu/src/kernels/matmul_packed_webgpu.ts
  tfjs-backend-webgpu/src/kernels/mirror_pad_webgpu.ts
  tfjs-backend-webgpu/src/kernels/pad_webgpu.ts
  tfjs-backend-webgpu/src/kernels/pool2d_webgpu.ts
  tfjs-backend-webgpu/src/kernels/reduce_webgpu.ts
  tfjs-backend-webgpu/src/kernels/resize_bilinear_webgpu.ts
  tfjs-backend-webgpu/src/kernels/select_webgpu.ts
  tfjs-backend-webgpu/src/kernels/slice_webgpu.ts
  tfjs-backend-webgpu/src/kernels/strided_slice_webgpu.ts
  tfjs-backend-webgpu/src/kernels/transpose_shared_webgpu.ts
  tfjs-backend-webgpu/src/kernels/transpose_webgpu.ts
  tfjs-backend-webgpu/src/kernels/unary_op_webgpu.ts
  tfjs-backend-webgpu/src/kernels/webgpu_program.ts
  tfjs-backend-webgpu/src/shader_preprocessor.ts
Labels: cla: yes

#4613 revert custom bundle tests to be regression tests
  e2e/integration_tests/custom_bundle_test.ts
  e2e/scripts/test-ci.sh
Labels: cla: yes

#4612 remove modularization helper scripts
  tfjs-backend-webgl/package.json
  tfjs-backend-webgl/scripts/extract-kernel.ts
  tfjs-backend-webgl/yarn.lock
  tfjs-core/package.json
  tfjs-core/scripts/extract_op.ts
  tfjs-core/yarn.lock
  tfjs-node-gpu/package.json
  tfjs-node-gpu/yarn.lock
  tfjs-node/package.json
  tfjs-node/scripts/extract-kernel.ts
  tfjs-node/yarn.lock
Labels: cla: yes

#4614 Mark imports as ignored in the browser
  tfjs-core/package.json
  tfjs/package.json
Labels: cla: yes
