Repository tensorflow/tfjs, pull requests merged in 2021-06, with the labels that each got.

#5157 Allow string inputs in gatherND
  tfjs-core/src/ops/gather_nd.ts
Labels: cla: yes

#5148 webgpu: Fix the reduce shader key
  tfjs-backend-webgpu/src/kernel_utils/reduce.ts
  tfjs-backend-webgpu/src/kernels/reduce_webgpu.ts
Labels: cla: yes

#5155 webgpu: Optimize Conv2DBackpropInput
  tfjs-backend-webgpu/src/flags_webgpu.ts
  tfjs-backend-webgpu/src/kernels/Conv2DBackpropInput.ts
  tfjs-backend-webgpu/src/kernels/conv2d_naive_webgpu.ts
  tfjs-backend-webgpu/src/kernels/conv_backprop_mm_webgpu.ts
Labels: cla: yes

#5130 webgpu: Add Pow kernel
  tfjs-backend-webgpu/src/kernels/Pow.ts
  tfjs-backend-webgpu/src/kernels/binary_ops.ts
  tfjs-backend-webgpu/src/register_all_kernels.ts
  tfjs-backend-webgpu/src/setup_test.ts
Labels: cla: yes

#5152 Allow up to TF-Hub==0.12
  tfjs-converter/python/requirements.txt
Labels: cla: yes

#4910 Fuse depthwise conv2d with activation function without biasAdd
  tfjs-converter/python/tensorflowjs/converters/fuse_depthwise_conv2d.py
  tfjs-converter/python/tensorflowjs/converters/fuse_depthwise_conv2d_test.py
  tfjs-converter/src/operations/executors/convolution_executor.ts
  tfjs-converter/src/operations/executors/convolution_executor_test.ts
Labels: cla: yes

#5079 [node] Add `SummaryFileWriter.histogram` TensorBoard logging
  tfjs-node/src/callbacks.ts
  tfjs-node/src/nodejs_kernel_backend.ts
  tfjs-node/src/proto/api.proto
  tfjs-node/src/proto/api_pb.js
  tfjs-node/src/tensorboard.ts
  tfjs-node/src/tensorboard_test.ts
Labels: cla: yes

#5168 Update monorepo to 3.7.0.
  tfjs-backend-cpu/package.json
  tfjs-backend-cpu/src/version.ts
  tfjs-backend-wasm/package.json
  tfjs-backend-wasm/src/version.ts
  tfjs-backend-webgl/package.json
  tfjs-backend-webgl/src/version.ts
  tfjs-converter/package.json
  tfjs-converter/python/tensorflowjs/version.py
  tfjs-converter/src/version.ts
  tfjs-core/package.json
  tfjs-core/src/version.ts
  tfjs-data/package.json
  tfjs-data/src/version.ts
  tfjs-layers/package.json
  tfjs-layers/src/version.ts
  tfjs-node-gpu/package.json
  tfjs-node/package.json
  tfjs-node/src/version.ts
  tfjs/package.json
  tfjs/src/version.ts
Labels: INTERNAL, cla: yes

#5164 webgpu: Fix the OOB error in transform/slice/stridedSlice
  tfjs-backend-webgpu/karma.conf.js
  tfjs-backend-webgpu/src/kernels/slice_webgpu.ts
  tfjs-backend-webgpu/src/kernels/strided_slice_webgpu.ts
  tfjs-backend-webgpu/src/kernels/transform_webgpu.ts
Labels: cla: yes

#5170 Update lockfiles branch tfjs_3.7.0_lockfiles lock files.
  tfjs-backend-cpu/yarn.lock
  tfjs-backend-wasm/yarn.lock
  tfjs-backend-webgl/yarn.lock
  tfjs-converter/yarn.lock
  tfjs-data/yarn.lock
  tfjs-layers/yarn.lock
  tfjs-node-gpu/yarn.lock
  tfjs-node/yarn.lock
  tfjs/yarn.lock
Labels: INTERNAL, cla: yes

#5165 webgpu: Fix a potential bug in vector*matrix
  tfjs-backend-webgpu/src/kernels/matmul_packed_webgpu.ts
Labels: cla: yes

#5175 Upgrade webgpu to 0.0.1-alpha.6
  tfjs-backend-webgpu/package.json
  tfjs-backend-webgpu/yarn.lock
Labels: cla: yes

#5176 Upgrade webgpu to 0.0.1-alpha.7
  tfjs-backend-webgpu/package.json
Labels: cla: yes

#5177 Add support for webgpu to release_notes script
  scripts/release_notes/release_notes.ts
Labels: cla: yes

#5187 Adds Google Pixel 5 support to BrowserStack Benchmark
  e2e/benchmarks/browserstack-benchmark/browser_list.json
Labels: cla: yes

#5178 Add iPhone 12 support for e2e browserstack benchmark
  e2e/benchmarks/browserstack-benchmark/browser_list.json
Labels: cla: yes

#5189 Added HumanGPS: Geodesic PreServing Feature for Dense Human Correspondences
  GALLERY.md
Labels: cla: yes

#5147 [e2e] Add pose-detection models to e2e benchmark
  e2e/benchmarks/local-benchmark/index.html
  e2e/benchmarks/model_config.js
Labels: cla: yes

#5193 Fix webgl backend memory leak in firefox
  tfjs-backend-webgl/src/backend_webgl.ts
Labels: cla: yes

#5185 Supported conv2dTranspose with explicit paddings.
  tfjs-core/src/ops/conv2d_transpose.ts
  tfjs-core/src/ops/conv2d_transpose_test.ts
  tfjs-node/src/run_tests.ts
Labels: cla: yes

#5169 Update WASM README about setting up cross-origin isolation
  tfjs-backend-wasm/README.md
Labels: cla: yes

#5186 [webgpu] Add op tile
  tfjs-backend-webgpu/src/kernel_utils/shared.ts
  tfjs-backend-webgpu/src/kernels/Tile.ts
  tfjs-backend-webgpu/src/kernels/tile_webgpu.ts
  tfjs-backend-webgpu/src/register_all_kernels.ts
  tfjs-backend-webgpu/src/setup_test.ts
Labels: cla: yes

#5190 [webgpu] Enable bool and add op logicalAnd
  tfjs-backend-webgpu/src/backend_webgpu.ts
  tfjs-backend-webgpu/src/kernels/LogicalAnd.ts
  tfjs-backend-webgpu/src/kernels/argminmax_webgpu.ts
  tfjs-backend-webgpu/src/kernels/binary_op_vec4_webgpu.ts
  tfjs-backend-webgpu/src/kernels/binary_op_webgpu.ts
  tfjs-backend-webgpu/src/kernels/binary_ops.ts
  tfjs-backend-webgpu/src/kernels/reduce_webgpu.ts
  tfjs-backend-webgpu/src/register_all_kernels.ts
  tfjs-backend-webgpu/src/setup_test.ts
  tfjs-backend-webgpu/src/shader_preprocessor.ts
Labels: cla: yes

#5204 [tfjs-node] upgrade tensorflow deps to 2.5 and built raspberry pi 2.5 binary
  tfjs-node/scripts/deps-constants.js
  tfjs-node/scripts/install.js
Labels: cla: yes

#5171 libtensorflow path name replacing
  tfjs-node/binding.gyp
Labels: cla: no

#5195 Localize BrowserStack dependencies, add build-deps capability
  e2e/benchmarks/browserstack-benchmark/README.md
  e2e/benchmarks/browserstack-benchmark/index.html
  e2e/benchmarks/browserstack-benchmark/package.json
Labels: cla: yes

#5196 Add --help menu to BrowserStack benchmark
  e2e/benchmarks/browserstack-benchmark/app.js
Labels: cla: yes

#5202 Use CopyExternalImageToTexture() in FromPixels
  tfjs-backend-webgpu/src/kernels/FromPixels.ts
  tfjs-backend-webgpu/src/kernels/FromPixelsExternalImage.ts
Labels: cla: yes

#5208 [webgpu] Simplify activation shader key
  tfjs-backend-webgpu/src/backend_webgpu.ts
  tfjs-backend-webgpu/src/kernels/BatchMatMul_impl.ts
  tfjs-backend-webgpu/src/kernels/FusedConv2D.ts
  tfjs-backend-webgpu/src/kernels/FusedDepthwiseConv2D.ts
  tfjs-backend-webgpu/src/kernels/activation_util.ts
  tfjs-backend-webgpu/src/kernels/conv2d_mm_vec4_webgpu.ts
  tfjs-backend-webgpu/src/kernels/conv2d_mm_webgpu.ts
  tfjs-backend-webgpu/src/kernels/conv2d_naive_webgpu.ts
  tfjs-backend-webgpu/src/kernels/depthwise_conv2d_webgpu.ts
  tfjs-backend-webgpu/src/kernels/matmul_packed_vec4_webgpu.ts
  tfjs-backend-webgpu/src/kernels/matmul_packed_webgpu.ts
Labels: cla: yes

#5209 webgpu: Optimize depthwise conv2d
  tfjs-backend-webgpu/src/kernels/DepthwiseConv2dNative.ts
  tfjs-backend-webgpu/src/kernels/FusedDepthwiseConv2D.ts
  tfjs-backend-webgpu/src/kernels/depthwise_conv2d_3x3_webgpu.ts
Labels: cla: yes

#5228 Replace deprecated package '@react-native-community/async-storage'
  tfjs-react-native/integration_rn59/android/settings.gradle
  tfjs-react-native/integration_rn59/ios/Podfile
  tfjs-react-native/integration_rn59/ios/Podfile.lock
  tfjs-react-native/integration_rn59/package.json
  tfjs-react-native/package.json
  tfjs-react-native/rollup.config.js
  tfjs-react-native/src/async_storage_io.ts
Labels: cla: yes

#5222 [webgpu] Simplify shader key of binary op and unary op
  tfjs-backend-webgpu/src/kernel_utils/int.ts
  tfjs-backend-webgpu/src/kernel_utils/kernel_funcs_utils.ts
  tfjs-backend-webgpu/src/kernels/Abs.ts
  tfjs-backend-webgpu/src/kernels/Add.ts
  tfjs-backend-webgpu/src/kernels/Ceil.ts
  tfjs-backend-webgpu/src/kernels/Elu.ts
  tfjs-backend-webgpu/src/kernels/Equal.ts
  tfjs-backend-webgpu/src/kernels/Exp.ts
  tfjs-backend-webgpu/src/kernels/Expm1.ts
  tfjs-backend-webgpu/src/kernels/Floor.ts
  tfjs-backend-webgpu/src/kernels/FloorDiv.ts
  tfjs-backend-webgpu/src/kernels/Greater.ts
  tfjs-backend-webgpu/src/kernels/GreaterEqual.ts
  tfjs-backend-webgpu/src/kernels/Less.ts
  tfjs-backend-webgpu/src/kernels/LessEqual.ts
  tfjs-backend-webgpu/src/kernels/Log.ts
  tfjs-backend-webgpu/src/kernels/LogicalAnd.ts
  tfjs-backend-webgpu/src/kernels/Maximum.ts
  tfjs-backend-webgpu/src/kernels/Minimum.ts
  tfjs-backend-webgpu/src/kernels/Multiply.ts
  tfjs-backend-webgpu/src/kernels/Neg.ts
  tfjs-backend-webgpu/src/kernels/NotEqual.ts
  tfjs-backend-webgpu/src/kernels/Pow.ts
  tfjs-backend-webgpu/src/kernels/Prelu.ts
  tfjs-backend-webgpu/src/kernels/RealDiv.ts
  tfjs-backend-webgpu/src/kernels/Relu.ts
  tfjs-backend-webgpu/src/kernels/Relu6.ts
  tfjs-backend-webgpu/src/kernels/Rsqrt.ts
  tfjs-backend-webgpu/src/kernels/Sigmoid.ts
  tfjs-backend-webgpu/src/kernels/Sqrt.ts
  tfjs-backend-webgpu/src/kernels/Square.ts
  tfjs-backend-webgpu/src/kernels/SquaredDifference.ts
  tfjs-backend-webgpu/src/kernels/Sub.ts
  tfjs-backend-webgpu/src/kernels/Tanh.ts
  tfjs-backend-webgpu/src/kernels/activation_util.ts
  tfjs-backend-webgpu/src/kernels/binary_op_complex_webgpu.ts
  tfjs-backend-webgpu/src/kernels/binary_op_shared_webgpu.ts
  tfjs-backend-webgpu/src/kernels/binary_op_util.ts
  tfjs-backend-webgpu/src/kernels/binary_op_vec4_webgpu.ts
  tfjs-backend-webgpu/src/kernels/binary_op_webgpu.ts
  tfjs-backend-webgpu/src/kernels/binary_ops.ts
  tfjs-backend-webgpu/src/kernels/unary_op_util.ts
  tfjs-backend-webgpu/src/kernels/unary_op_webgpu.ts
Labels: cla: yes

#5225 [webgpu] Upgrade clang-format version from 1.2.4 to 1.5.0
  tfjs-backend-webgpu/package.json
  tfjs-backend-webgpu/yarn.lock
Labels: cla: yes

#5230 Set up local jasmine tests for benchmark tools
  e2e/benchmarks/browserstack-benchmark/app_node_test.js
  e2e/benchmarks/browserstack-benchmark/package.json
  e2e/benchmarks/browserstack-benchmark/yarn.lock
Labels: cla: yes

#5232 [tfjs-converter] sync g3 changes for BUILD file
  tfjs-converter/python/tensorflowjs/converters/BUILD
Labels: cla: yes

#5238 Prevent BrowserStack access during tests
  e2e/benchmarks/browserstack-benchmark/app.js
Labels: cla: yes

#5075 Add WebGPU support for e2e benchmarks
  e2e/benchmarks/benchmark_util.js
  e2e/benchmarks/local-benchmark/index.html
  e2e/benchmarks/local-benchmark/index.js
Labels: cla: yes

#5233 Switch WebGL TopK algorithm to use bitonic
  tfjs-backend-cpu/src/kernels/TopK_impl.ts
  tfjs-backend-wasm/src/cc/kernels/TopK.cc
  tfjs-backend-webgl/src/kernels/TopK.ts
  tfjs-backend-webgl/src/top_k_gpu.ts
  tfjs-core/src/ops/topk.ts
  tfjs-core/src/ops/topk_test.ts
Labels: cla: yes

#5236 Switch CPU TopK Algorithm to use Floyd-Rivest
  tfjs-backend-cpu/src/kernels/TopK_impl.ts
  tfjs-core/src/ops/topk_test.ts
  tfjs-core/src/util_base.ts
Labels: cla: yes

#5218 [webgpu] Check if runtime support WebGPU before initial a WebGPU backend
  tfjs-backend-webgpu/src/backend_webgpu.ts
  tfjs-backend-webgpu/src/index.ts
  tfjs-backend-webgpu/src/webgpu_util.ts
Labels: cla: yes

#5244 Switch WASM TopK Algorithm to use Floyd-Rivest
  tfjs-backend-wasm/src/cc/kernels/TopK.cc
Labels: cla: yes

#5217 Update react-native monorepo dependencies to 3.7.0
  tfjs-react-native/integration_rn59/components/tfjs_unit_test_runner.tsx
  tfjs-react-native/integration_rn59/package.json
  tfjs-react-native/integration_rn59/test/integration_test.ts
  tfjs-react-native/integration_rn59/yarn.lock
  tfjs-react-native/package.json
  tfjs-react-native/yarn.lock
Labels: cla: yes

#5247 Update tfjs-react-native to 0.6.0.
  tfjs-react-native/package.json
  tfjs-react-native/src/version.ts
  tfjs-react-native/yarn.lock
Labels: INTERNAL, cla: yes

#5251 Add the missing backend initialization in runKernel
  tfjs-core/src/engine.ts
Labels: cla: yes

#5229 Add synchronous --outfile option to BrowserStack benchmark
  .gitignore
  e2e/README.md
  e2e/benchmarks/browserstack-benchmark/README.md
  e2e/benchmarks/browserstack-benchmark/app.js
  e2e/benchmarks/browserstack-benchmark/app_node_test.js
Labels: cla: yes

#5253 [webgpu] Add case for matmul and conv2d to test special path
  tfjs-backend-webgpu/src/kernels/conv2d_webgpu_test.ts
  tfjs-backend-webgpu/src/matmul_test.ts
Labels: cla: yes

#5239 Localize BrowserStack Karma config
  e2e/benchmarks/browserstack-benchmark/karma.conf.js
  e2e/benchmarks/browserstack-benchmark/package.json
  e2e/benchmarks/browserstack-benchmark/yarn.lock
Labels: cla: yes

#5261 Add FlipLeftRight NodeJS kernel.
  tfjs-node/src/kernels/FlipLeftRight.ts
  tfjs-node/src/register_all_kernels.ts
  tfjs-node/src/run_tests.ts
Labels: cla: yes

#5260 Cosh branch
  tfjs-backend-wasm/package.json
  tfjs-backend-wasm/src/cc/BUILD
  tfjs-backend-wasm/src/cc/kernels/Cosh.cc
  tfjs-backend-wasm/src/kernels/Cosh.ts
  tfjs-backend-wasm/src/register_all_kernels.ts
  tfjs-backend-wasm/src/setup_test.ts
  tfjs-backend-wasm/yarn.lock
Labels: cla: yes

#5263 Revert "Add FlipLeftRight NodeJS kernel."
  tfjs-node/src/kernels/FlipLeftRight.ts
  tfjs-node/src/register_all_kernels.ts
  tfjs-node/src/run_tests.ts
Labels: cla: yes

#5243 Adds --benchmarks command line argument
  e2e/benchmarks/browserstack-benchmark/README.md
  e2e/benchmarks/browserstack-benchmark/app.js
  e2e/benchmarks/browserstack-benchmark/app_node_test.js
  e2e/benchmarks/browserstack-benchmark/preconfigured_browser.json
  e2e/benchmarks/browserstack-benchmark/test_config.json
Labels: cla: yes
